// Video Report — orchestration provider.
//
// Assembles the full VideoReportData for a report: builds narration scenes
// deterministically, reuses a cached TTS job when present (or generates one),
// parses subtitles, and assigns scene timings.

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/models/survey_models.dart';
import '../profile/profile_providers.dart';
import '../survey/survey_providers.dart';
import 'data/video_report_repository.dart';
import 'logic/narration_script_builder.dart';
import 'logic/scene_timeline.dart';
import 'models/video_report_models.dart';

/// Builds the assembled [VideoReportData] for [reportId].
///
/// Scenes are ALWAYS built deterministically from the report data. We reuse
/// only the cached audio + srt from a completed job, never its stored
/// narration_script — so the on-screen scene text stays in sync with the
/// current builder logic even if a job was generated by an older version.
final videoReportDataProvider =
    FutureProvider.family<VideoReportData, String>((ref, reportId) async {
  final report = await ref.watch(surveyRepositoryProvider).getReport(reportId);
  if (report == null) throw Exception('Report not found');

  final narratives = await ref.watch(narrativesProvider.future);
  final locale = ref.watch(appLocaleProvider);

  // Await the profile so userName resolves from a stable value (avoids an
  // extra rebuild when the profile transitions loading → data).
  final profile = await ref.watch(ccProfileProvider.future);
  final userName = (profile['full_name'] as String?) ??
      (profile['email'] as String?) ??
      '';

  final surveyType =
      (report.subScores != null && report.subScores!.isNotEmpty)
          ? SurveyType.premium
          : SurveyType.free;

  final scenes = const NarrationScriptBuilder().build(
    report: report,
    narratives: narratives,
    userName: userName,
    locale: locale,
    surveyType: surveyType,
  );

  final repo = ref.watch(videoReportRepositoryProvider);

  var raw = await repo.findCompletedJob(reportId);
  raw ??= await repo.createAndWait(
    reportId: reportId,
    userId: report.userId,
    text: scenes.map((s) => s.text).join(' '),
    narrationScript: {
      // Mark this job as mobile-generated so findCompletedJob can reuse it
      // later (and so web-Gemini jobs stay out of the mobile cache path).
      'source': kMobileNarrationSource,
      'scenes':
          scenes.map((s) => {'id': s.id.name, 'text': s.text}).toList(),
    },
    language: locale,
  );

  final cues = parseSrt(raw.srt ?? '');
  // Fallback when the job carries no duration: 4s per scene.
  final durationMs = raw.durationMs ?? (scenes.length * 4000);
  final timed = assignSceneTimings(
    scenes: scenes,
    cues: cues,
    audioDurationMs: durationMs,
  );

  return VideoReportData(
    scenes: timed,
    cues: cues,
    audioUrl: repo.proxiedAudioUrl(raw.audioUrl),
    audioDurationMs: durationMs,
  );
});
