#!/usr/bin/env python3
"""
gen_wr_mood_content_sql.py
==========================
Sinh khối SQL seed cho public.wr_mood_content từ assets/seed/wr_mood_content.json.

Nguồn chuẩn là file JSON; khối SQL trong migration chỉ là bản dịch. Đội nội dung
sửa JSON (thay body thật, thêm script lồng tiếng, đổi placeholder về false) rồi
chạy lại script này.

  python3 tool/gen_wr_mood_content_sql.py

Kiến trúc Dữ liệu Hai Lớp v1.6 §8.1 (schema), §8.2 (hiện trạng nội dung),
§XII.3 (script chỉ dùng nội bộ, không trả về cho app).
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
JSON_DEFAULT = REPO_ROOT / "assets" / "seed" / "wr_mood_content.json"
MIGRATION_DEFAULT = (
    REPO_ROOT / "supabase" / "migrations"
    / "20260728000001_wr_mood_content_v1_6.sql"
)

SEED_START = "-- SEED_START (generated by gen_wr_mood_content_sql.py)"
SEED_END = "-- SEED_END"

# Sáu nhóm từ 25/08/2026 (changelog mockup 24/08 §3). Thứ tự khớp lưới check-in
# ở Home: nhóm cảm xúc khó khăn trước, nhóm tích cực sau.
MOODS = ("stress", "tired", "foggy", "outofsync", "ok", "happy")


def pg_literal(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


ON_CONFLICT = {
    # Seed lần đầu: bảng vừa tạo, không được đè lên nội dung đã có.
    "insert": "on conflict (mood, sort_order) do nothing;",
    # Cập nhật nội dung: các hàng cũ đã nằm sẵn trên cơ sở dữ liệu thật, nên
    # phải ghi đè theo (mood, sort_order). Giữ nguyên id để đường dẫn sâu
    # /wr/mood-content/<id> đang lưu ở đâu đó không chết.
    "upsert": (
        "on conflict (mood, sort_order) do update set\n"
        "  title       = excluded.title,\n"
        "  kind        = excluded.kind,\n"
        "  duration    = excluded.duration,\n"
        "  type        = excluded.type,\n"
        "  body        = excluded.body,\n"
        "  script      = excluded.script,\n"
        "  placeholder = excluded.placeholder,\n"
        "  updated_at  = now();"
    ),
}


def gen_inserts(rows: list, mode: str = "insert") -> list[str]:
    lines = [
        "insert into public.wr_mood_content",
        "  (mood, sort_order, title, kind, duration, type, body, script, placeholder)",
        "values",
    ]
    body_rows = []
    for r in rows:
        body_rows.append(
            f"  ({pg_literal(r['mood'])}, "
            f"{pg_literal(r['sort_order'])}, "
            f"{pg_literal(r['title'])},\n"
            f"   {pg_literal(r['kind'])}, "
            f"{pg_literal(r['duration'])}, "
            f"{pg_literal(r['type'])},\n"
            f"   {pg_literal(r['body'])},\n"
            f"   {pg_literal(r.get('script'))}, "
            f"{pg_literal(r['placeholder'])})"
        )
    lines.append(",\n".join(body_rows))
    lines.append(ON_CONFLICT[mode])
    return lines


def validate(rows: list) -> None:
    """Chặn những sai lệch so với §8.1/§8.2 ngay từ lúc sinh SQL."""
    errors = []

    for mood in MOODS:
        group = [r for r in rows if r["mood"] == mood]
        readings = [r for r in group if r["type"] == "reading"]
        # Toàn văn v2: đúng 5 BÀI ĐỌC mỗi cảm xúc, và chúng phải nằm ở
        # sort_order 1..5. Home chỉ hiện mục đầu nhóm (§8.3), nên nếu một mục
        # audio còn nháp lọt lên slot 1 thì bản release lọc nó đi và Home mất
        # hẳn thẻ gợi ý.
        if len(readings) != 5:
            errors.append(f"{mood}: có {len(readings)} bài đọc, phải đủ 5")
        reading_orders = sorted(r["sort_order"] for r in readings)
        if reading_orders != list(range(1, len(readings) + 1)):
            errors.append(
                f"{mood}: bài đọc phải chiếm sort_order 1..5, đang là {reading_orders}"
            )
        orders = sorted(r["sort_order"] for r in group)
        if orders != list(range(1, len(group) + 1)):
            errors.append(f"{mood}: sort_order phải liên tục từ 1, đang là {orders}")

    for r in rows:
        tag = f"{r['mood']}#{r['sort_order']}"
        # Từ 25/08/2026 chỉ còn BÀI ĐỌC (changelog 24/08 §4: "chuyển toàn bộ mục
        # trước đây là HEALING AUDIO sang BÀI ĐỌC — vì giai đoạn hiện tại chỉ
        # sản xuất được nội dung dạng bài đọc, chưa thu âm"). Cột `script` và
        # nhánh audio ở app vẫn giữ, nhưng dữ liệu thì không còn hàng nào.
        if r["type"] != "reading":
            errors.append(f"{tag}: chỉ còn type 'reading' (§4), đang là {r['type']!r}")
        if r["kind"] != "BÀI ĐỌC":
            errors.append(f"{tag}: chỉ còn kind 'BÀI ĐỌC' (§4), đang là {r['kind']!r}")
        # §8.1: script chỉ dành cho HEALING AUDIO, null với BÀI ĐỌC.
        if r["type"] == "reading" and r.get("script"):
            errors.append(f"{tag}: BÀI ĐỌC không được có script (§8.1)")
        if not str(r.get("body") or "").strip():
            errors.append(f"{tag}: body rỗng")

    unknown = {r["mood"] for r in rows} - set(MOODS)
    if unknown:
        errors.append(f"mood lạ: {sorted(unknown)} (§8.1 chỉ có {list(MOODS)})")

    if errors:
        for e in errors:
            print(f"[ERROR] {e}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", default=str(JSON_DEFAULT))
    parser.add_argument("--migration", default=str(MIGRATION_DEFAULT))
    parser.add_argument("--mode", default="insert", choices=sorted(ON_CONFLICT))
    args = parser.parse_args()

    rows = json.loads(Path(args.json).read_text(encoding="utf-8"))
    validate(rows)

    sql_block = "\n".join(
        [SEED_START, ""] + gen_inserts(rows, args.mode) + ["", SEED_END]
    )

    migration_path = Path(args.migration)
    if not migration_path.exists():
        print(f"[ERROR] Không tìm thấy migration: {migration_path}",
              file=sys.stderr)
        sys.exit(1)

    text = migration_path.read_text(encoding="utf-8")
    if SEED_START in text and SEED_END in text:
        before = text[: text.index(SEED_START)]
        after = text[text.index(SEED_END) + len(SEED_END):]
        text = before + sql_block + after
    else:
        text = text.rstrip() + "\n\n" + sql_block + "\n"

    migration_path.write_text(text, encoding="utf-8")

    drafts = sum(1 for r in rows if r["placeholder"])
    print(f"[OK] Seed SQL -> {migration_path}", file=sys.stderr)
    print(f"     mục      : {len(rows)}", file=sys.stderr)
    print(f"     còn nháp : {drafts} (placeholder=true, chưa phát hành được)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
