#!/usr/bin/env python3
"""
gen_wr_mood_content_sql.py
==========================
Sinh khối SQL seed cho public.wr_mood_content từ assets/seed/wr_mood_content.json.

Nguồn chuẩn là file JSON; khối SQL trong migration chỉ là bản dịch. Đội nội dung
sửa JSON (thay body thật, thêm script lồng tiếng, đổi placeholder về false) rồi
chạy lại script này.

  python3 tool/gen_wr_mood_content_sql.py

Kiến trúc Dữ liệu Hai Lớp v1.6 §8.1 (schema), §8.2 (hiện trạng nội dung),
§XII.3 (script chỉ dùng nội bộ, không trả về cho app).
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
JSON_DEFAULT = REPO_ROOT / "assets" / "seed" / "wr_mood_content.json"
MIGRATION_DEFAULT = (
    REPO_ROOT / "supabase" / "migrations"
    / "20260728000001_wr_mood_content_v1_6.sql"
)

SEED_START = "-- SEED_START (generated by gen_wr_mood_content_sql.py)"
SEED_END = "-- SEED_END"

MOODS = ("stress", "tired", "ok", "happy")


def pg_literal(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def gen_inserts(rows: list) -> list[str]:
    lines = [
        "insert into public.wr_mood_content",
        "  (mood, sort_order, title, kind, duration, type, body, script, placeholder)",
        "values",
    ]
    body_rows = []
    for r in rows:
        body_rows.append(
            f"  ({pg_literal(r['mood'])}, "
            f"{pg_literal(r['sort_order'])}, "
            f"{pg_literal(r['title'])},\n"
            f"   {pg_literal(r['kind'])}, "
            f"{pg_literal(r['duration'])}, "
            f"{pg_literal(r['type'])},\n"
            f"   {pg_literal(r['body'])},\n"
            f"   {pg_literal(r.get('script'))}, "
            f"{pg_literal(r['placeholder'])})"
        )
    lines.append(",\n".join(body_rows))
    lines.append("on conflict (mood, sort_order) do nothing;")
    return lines


def validate(rows: list) -> None:
    """Chặn những sai lệch so với §8.1/§8.2 ngay từ lúc sinh SQL."""
    errors = []

    for mood in MOODS:
        group = [r for r in rows if r["mood"] == mood]
        # §8.2: đủ 5 mục mỗi cảm xúc. Thiếu thì màn Thư viện hụt nhóm.
        if len(group) != 5:
            errors.append(f"{mood}: có {len(group)} mục, phải đủ 5 (§8.2)")
        orders = sorted(r["sort_order"] for r in group)
        if orders != list(range(1, len(group) + 1)):
            errors.append(f"{mood}: sort_order phải liên tục từ 1, đang là {orders}")

    for r in rows:
        tag = f"{r['mood']}#{r['sort_order']}"
        if r["type"] not in ("reading", "audio"):
            errors.append(f"{tag}: type phải là reading hoặc audio")
        if r["kind"] not in ("BÀI ĐỌC", "HEALING AUDIO"):
            errors.append(f"{tag}: kind lạ {r['kind']!r}")
        # §8.1: script chỉ dành cho HEALING AUDIO, null với BÀI ĐỌC.
        if r["type"] == "reading" and r.get("script"):
            errors.append(f"{tag}: BÀI ĐỌC không được có script (§8.1)")
        if not str(r.get("body") or "").strip():
            errors.append(f"{tag}: body rỗng")

    unknown = {r["mood"] for r in rows} - set(MOODS)
    if unknown:
        errors.append(f"mood lạ: {sorted(unknown)} (§8.1 chỉ có {list(MOODS)})")

    if errors:
        for e in errors:
            print(f"[ERROR] {e}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", default=str(JSON_DEFAULT))
    parser.add_argument("--migration", default=str(MIGRATION_DEFAULT))
    args = parser.parse_args()

    rows = json.loads(Path(args.json).read_text(encoding="utf-8"))
    validate(rows)

    sql_block = "\n".join([SEED_START, ""] + gen_inserts(rows) + ["", SEED_END])

    migration_path = Path(args.migration)
    if not migration_path.exists():
        print(f"[ERROR] Không tìm thấy migration: {migration_path}",
              file=sys.stderr)
        sys.exit(1)

    text = migration_path.read_text(encoding="utf-8")
    if SEED_START in text and SEED_END in text:
        before = text[: text.index(SEED_START)]
        after = text[text.index(SEED_END) + len(SEED_END):]
        text = before + sql_block + after
    else:
        text = text.rstrip() + "\n\n" + sql_block + "\n"

    migration_path.write_text(text, encoding="utf-8")

    drafts = sum(1 for r in rows if r["placeholder"])
    print(f"[OK] Seed SQL -> {migration_path}", file=sys.stderr)
    print(f"     mục      : {len(rows)}", file=sys.stderr)
    print(f"     còn nháp : {drafts} (placeholder=true, chưa phát hành được)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
