#!/usr/bin/env python3
"""
gen_wr_seed_sql.py
==================
Read assets/seed/wr_situations.json + wr_stories.json
and emit safe SQL INSERT statements (appended into migration).

Usage:
  python3 tool/gen_wr_seed_sql.py
  python3 tool/gen_wr_seed_sql.py \
      --situations assets/seed/wr_situations.json \
      --stories assets/seed/wr_stories.json

Output is written to stdout; migration file is updated in-place.
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SIT_DEFAULT = REPO_ROOT / "assets" / "seed" / "wr_situations.json"
STO_DEFAULT = REPO_ROOT / "assets" / "seed" / "wr_stories.json"

MIGRATION = REPO_ROOT / "supabase" / "migrations" / "20260721000000_create_wr_reflection_content.sql"

SEED_START = "-- SEED_START (generated by gen_wr_seed_sql.py)"
SEED_END = "-- SEED_END"


def pg_literal(v) -> str:
    """Return a safe PostgreSQL literal for value v."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        if not v:
            return "ARRAY[]::text[]"
        escaped = [pg_literal(item) for item in v]
        return "ARRAY[" + ", ".join(escaped) + "]"
    # String: use dollar-quoting won't work inline; use standard E-string escaping
    s = str(v)
    # Escape single quotes by doubling them
    s = s.replace("'", "''")
    return f"'{s}'"


def gen_situations_inserts(situations: list) -> list[str]:
    lines = []
    lines.append("-- wr_situations seed")
    lines.append("insert into public.wr_situations")
    lines.append("  (code, text, sca_dimension, human_need, expected_outcome, sca_perspective, wave)")
    lines.append("values")
    rows = []
    for s in situations:
        row = (
            f"  ({pg_literal(s['code'])}, "
            f"{pg_literal(s['text'])}, "
            f"{pg_literal(s['sca_dimension'])}, "
            f"{pg_literal(s.get('human_need'))}, "
            f"{pg_literal(s.get('expected_outcome'))}, "
            f"{pg_literal(s.get('sca_perspective'))}, "
            f"{pg_literal(s['wave'])})"
        )
        rows.append(row)
    lines.append(",\n".join(rows))
    lines.append("on conflict (code) do nothing;")
    return lines


def gen_stories_inserts(stories: list) -> list[str]:
    lines = []
    lines.append("-- wr_stories seed")
    lines.append("insert into public.wr_stories")
    lines.append("  (story_id, title, sca_dimension, human_need, situation,")
    lines.append("   emotion_tags, behavior_tags, career_stages, difficulty_level,")
    lines.append("   story_content, reflection_question, self_reflection, aha_message, practice_action)")
    lines.append("values")
    rows = []
    for s in stories:
        row = (
            f"  ({pg_literal(s['story_id'])}, "
            f"{pg_literal(s['title'])}, "
            f"{pg_literal(s['sca_dimension'])}, "
            f"{pg_literal(s.get('human_need'))}, "
            f"{pg_literal(s.get('situation'))},\n"
            f"   {pg_literal(s.get('emotion_tags', []))}, "
            f"{pg_literal(s.get('behavior_tags', []))}, "
            f"{pg_literal(s.get('career_stages', []))}, "
            f"{pg_literal(s.get('difficulty_level'))},\n"
            f"   {pg_literal(s['story_content'])}, "
            f"{pg_literal(s.get('reflection_question'))}, "
            f"{pg_literal(s.get('self_reflection'))}, "
            f"{pg_literal(s.get('aha_message'))}, "
            f"{pg_literal(s.get('practice_action'))})"
        )
        rows.append(row)
    lines.append(",\n".join(rows))
    lines.append("on conflict (story_id) do nothing;")
    return lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--situations", default=str(SIT_DEFAULT))
    parser.add_argument("--stories", default=str(STO_DEFAULT))
    parser.add_argument(
        "--migration",
        default=str(MIGRATION),
        help="Migration file whose SEED_START/SEED_END block gets rewritten.",
    )
    parser.add_argument(
        "--prefix",
        default=None,
        help=(
            "Chỉ sinh các bản ghi có code/story_id bắt đầu bằng tiền tố này "
            "(ví dụ 'P-' cho nhóm tình huống tích cực v1.6 §2.3). "
            "Bỏ qua để sinh toàn bộ. Dùng khi một đợt nội dung mới cần nằm ở "
            "migration riêng thay vì viết đè lên migration đã chạy trên DB."
        ),
    )
    args = parser.parse_args()

    with open(args.situations, encoding="utf-8") as f:
        situations = json.load(f)
    with open(args.stories, encoding="utf-8") as f:
        stories = json.load(f)

    if args.prefix:
        situations = [s for s in situations
                      if s["code"].startswith(args.prefix)]
        stories = [s for s in stories
                   if s["story_id"].startswith(args.prefix)]
        if not situations and not stories:
            print(f"[ERROR] Không có bản ghi nào khớp tiền tố {args.prefix!r}",
                  file=sys.stderr)
            sys.exit(1)

    migration_path = Path(args.migration)

    lines = []
    lines.append(SEED_START)
    lines.append("")
    lines.extend(gen_situations_inserts(situations))
    lines.append("")
    lines.extend(gen_stories_inserts(stories))
    lines.append("")
    lines.append(SEED_END)

    sql_block = "\n".join(lines)

    # Read migration file and replace seed block
    if not migration_path.exists():
        print(f"[ERROR] Migration file not found: {migration_path}",
              file=sys.stderr)
        sys.exit(1)

    migration_text = migration_path.read_text(encoding="utf-8")

    if SEED_START in migration_text and SEED_END in migration_text:
        # Replace existing block
        before = migration_text[: migration_text.index(SEED_START)]
        after_end = migration_text.index(SEED_END) + len(SEED_END)
        after = migration_text[after_end:]
        new_text = before + sql_block + after
    else:
        # Append
        new_text = migration_text.rstrip() + "\n\n" + sql_block + "\n"

    migration_path.write_text(new_text, encoding="utf-8")
    print(f"[OK] Seed SQL written to {migration_path}", file=sys.stderr)
    print(f"     situations: {len(situations)}", file=sys.stderr)
    print(f"     stories   : {len(stories)}", file=sys.stderr)


if __name__ == "__main__":
    main()
