-- WorkReflection: tình huống tích cực P-01 → P-10.
-- Nguồn: Kiến trúc Dữ liệu Hai Lớp v1.6 §2.3 + Sprint 2 Mockup (5).
--
-- Vì sao cần: DataSpec v3 và Career Situation Library chỉ chứa tình huống dạng
-- vấn đề (nguồn gốc là công cụ chẩn đoán SCA cho tổ chức). Người dùng check-in
-- "khá ổn" hoặc "đang vui" mà vẫn bị gợi ý tình huống vấn đề thì thấy gượng ép.
--
-- Hai nhóm, theo §2.3:
--   P-ACHIEVE (P-01 → P-05) : thành tựu   → cảm xúc "Đang vui"
--   P-STEADY  (P-06 → P-10) : ổn định     → cảm xúc "Khá ổn"
--
-- Toàn bộ nội dung ở ngôi "tôi" theo §9.2 — đây là tiếng nói nội tâm của người
-- dùng, không phải lời nhắc từ ứng dụng.
--
-- ⚠ DB dùng chung với web app. Migration này chỉ NỚI RỘNG check constraint
--   (additive, không phá dữ liệu cũ) và THÊM dòng mới. Web app không ghi giá trị
--   P-* nên không bị ảnh hưởng; nhưng truy vấn liệt kê toàn bộ wr_stories bên web
--   sẽ thấy thêm 10 dòng này.

-- ---------------------------------------------------------------------------
-- 1. Nới check constraint: thêm P-ACHIEVE / P-STEADY vào miền giá trị dim.
--    §2.2: dim là "S1..A4, hoặc P-ACHIEVE / P-STEADY cho tình huống tích cực".
-- ---------------------------------------------------------------------------

alter table public.wr_situations
  drop constraint if exists wr_situations_sca_dimension_check;
alter table public.wr_situations
  add constraint wr_situations_sca_dimension_check
  check (sca_dimension in (
    'S1','S2','S3','C1','C2','C3','A1','A2','A3','A4',
    'P-ACHIEVE','P-STEADY'
  ));

alter table public.wr_stories
  drop constraint if exists wr_stories_sca_dimension_check;
alter table public.wr_stories
  add constraint wr_stories_sca_dimension_check
  check (sca_dimension in (
    'S1','S2','S3','C1','C2','C3','A1','A2','A3','A4',
    'P-ACHIEVE','P-STEADY'
  ));

-- Career Memory ghi lại dim của tình huống đã phản tư → cũng phải nhận P-*.
alter table public.wr_career_memory_events
  drop constraint if exists wr_career_memory_events_sca_dimension_check;
alter table public.wr_career_memory_events
  add constraint wr_career_memory_events_sca_dimension_check
  check (sca_dimension in (
    'S1','S2','S3','C1','C2','C3','A1','A2','A3','A4',
    'P-ACHIEVE','P-STEADY'
  ));

-- Đếm tình huống lặp lại cũng lưu dim.
alter table public.wr_pattern_counts
  drop constraint if exists wr_pattern_counts_sca_dimension_check;
alter table public.wr_pattern_counts
  add constraint wr_pattern_counts_sca_dimension_check
  check (sca_dimension in (
    'S1','S2','S3','C1','C2','C3','A1','A2','A3','A4',
    'P-ACHIEVE','P-STEADY'
  ));

-- ---------------------------------------------------------------------------
-- 2. Nội dung — sinh từ assets/seed/*.json, KHÔNG sửa tay khối dưới đây.
--
--    Nguồn chuẩn là hai file JSON; khối SQL này chỉ là bản dịch. Sửa JSON rồi
--    chạy lại:
--
--      python3 tool/gen_wr_seed_sql.py --prefix P- \
--        --migration supabase/migrations/20260728000000_wr_positive_situations_v1_6.sql
--
--    wr_situations giữ nhãn chip ngắn cho bước Notice; wr_stories giữ đủ 5
--    trường nội dung của §2.2. wave 1 vì check-in "vui" và "khá ổn" là hai
--    trong bốn lựa chọn ở Home, nhóm này phải có mặt ngay đợt đầu.
-- ---------------------------------------------------------------------------

-- SEED_START (generated by gen_wr_seed_sql.py)

-- wr_situations seed
insert into public.wr_situations
  (code, text, sca_dimension, human_need, expected_outcome, sca_perspective, wave)
values
  ('P-01', 'Tôi vừa hoàn thành một việc khó hơn mong đợi', 'P-ACHIEVE', 'phat_trien', 'Tôi muốn giữ lại cách mình đã vượt qua việc này, để lần sau lặp lại được', 'Thành công trôi qua nhanh hơn khó khăn trong trí nhớ. Dừng lại ghi nhận một lần làm tốt cũng là phản chiếu, không phải tự mãn.', 1),
  ('P-02', 'Tôi được ghi nhận tích cực từ cấp trên', 'P-ACHIEVE', 'phat_trien', 'Tôi muốn tin vào lời ghi nhận đó thay vì gạt đi', 'Ghi nhận từ bên ngoài chỉ đọng lại khi người nhận cũng tự công nhận điều đó cho mình. Nếu không, nó trôi qua như một câu xã giao.', 1),
  ('P-03', 'Tôi giúp được đồng nghiệp gỡ một vấn đề khó', 'P-ACHIEVE', 'phat_trien', 'Tôi muốn hiểu rõ hơn giá trị mình mang lại cho người khác', 'Giá trị lớn nhất trong hỗ trợ thường không phải câu trả lời, mà là sự có mặt đủ lâu để người kia tự tìm ra câu trả lời của họ.', 1),
  ('P-04', 'Tôi được tăng lương hoặc thăng chức', 'P-ACHIEVE', 'phat_trien', 'Tôi muốn cho phép mình vui trọn vẹn trước khi nghĩ đến áp lực tiếp theo', 'Kết quả tốt kéo theo kỳ vọng mới rất nhanh. Dừng lại ăn mừng là một phần của hành trình, không phải sự xao nhãng.', 1),
  ('P-05', 'Tôi nhận được lời cảm ơn bất ngờ từ ai đó', 'P-ACHIEVE', 'phat_trien', 'Tôi muốn nhìn thấy giá trị của những đóng góp mình vẫn cho là nhỏ', 'Những điều mình cho là bình thường đôi khi lại là điều người khác nhớ lâu nhất.', 1),
  ('P-06', 'Công việc hôm nay diễn ra đúng như tôi mong đợi', 'P-STEADY', 'phat_trien', 'Tôi muốn biết điều gì đã khiến hôm nay suôn sẻ, để giữ lại', 'Sự ổn định thường bị xem là hiển nhiên, trong khi nó là kết quả của rất nhiều điều đã được làm đúng phía sau.', 1),
  ('P-07', 'Tôi cảm thấy làm chủ được nhịp độ công việc của mình', 'P-STEADY', 'phat_trien', 'Tôi muốn giữ được nhịp độ này lâu hơn một ngày', 'Làm chủ nhịp độ không phải làm ít hơn, mà là biết điều gì thực sự cần sự chú ý của mình lúc này.', 1),
  ('P-08', 'Tôi vừa học được một điều nhỏ nhưng hữu ích', 'P-STEADY', 'phat_trien', 'Tôi muốn giữ lại bài học nhỏ này thay vì để nó trôi qua', 'Phần lớn sự tiến bộ không đến từ những bước ngoặt lớn, mà từ rất nhiều điều nhỏ được tích lũy.', 1),
  ('P-09', 'Tôi có một cuộc trò chuyện tốt với đồng nghiệp', 'P-STEADY', 'phat_trien', 'Tôi muốn dành đủ chỗ cho những kết nối nhẹ nhàng như vậy', 'Quan hệ tốt trong công việc hiếm khi được xây từ những cuộc họp lớn, mà từ rất nhiều cuộc trò chuyện nhỏ.', 1),
  ('P-10', 'Hôm nay không có gì đặc biệt, nhưng tôi thấy ổn', 'P-STEADY', 'phat_trien', 'Tôi muốn công nhận cả những ngày bình thường, không chỉ những ngày biến động', 'Không phải mọi trải nghiệm đáng ghi nhớ đều kịch tính. Đôi khi sự bình yên cũng là một dữ liệu quan trọng.', 1)
on conflict (code) do nothing;

-- wr_stories seed
insert into public.wr_stories
  (story_id, title, sca_dimension, human_need, situation,
   emotion_tags, behavior_tags, career_stages, difficulty_level,
   story_content, reflection_question, self_reflection, aha_message, practice_action)
values
  ('P-01', 'Tôi vừa hoàn thành một việc khó hơn mong đợi', 'P-ACHIEVE', 'phat_trien', 'Hoàn thành việc khó hơn mong đợi',
   ARRAY['nhẹ nhõm', 'tự hào', 'bất ngờ'], ARRAY['ghi nhận thành quả', 'rút kinh nghiệm'], ARRAY[]::text[], NULL,
   'Tôi đã lo lắng trước khi bắt đầu.
Deadline gấp.
Yêu cầu không rõ ràng lúc đầu.
Nhưng tôi đã hoàn thành, và kết quả tốt hơn tôi nghĩ.', 'Điều gì đã giúp tôi vượt qua được việc này?', 'Tôi có thường dừng lại để ghi nhận những lúc mình làm tốt không?', 'Thành công dễ trôi qua nhanh hơn khó khăn trong trí nhớ. Dừng lại một chút để giữ nó lại cũng là một hình thức phản chiếu.', 'Ghi lại điều cụ thể tôi đã làm đúng trong việc này, để lần sau có thể lặp lại.'),
  ('P-02', 'Tôi được ghi nhận tích cực từ cấp trên', 'P-ACHIEVE', 'phat_trien', 'Được ghi nhận từ cấp quản lý',
   ARRAY['vui', 'bất ngờ', 'ngờ vực'], ARRAY['tiếp nhận ghi nhận', 'tự đánh giá'], ARRAY[]::text[], NULL,
   'Tôi không mong đợi điều đó.
Nhưng trong một cuộc trò chuyện ngắn, quản lý của tôi nói rằng họ đánh giá cao cách tôi xử lý công việc gần đây.', 'Lời ghi nhận đó chạm vào điều gì ở tôi?', 'Tôi có tin vào điều đó, hay có phần nào trong tôi vẫn nghi ngờ?', 'Ghi nhận từ người khác có giá trị, nhưng ý nghĩa thật sự đến khi tôi cũng tự công nhận điều đó cho chính mình.', 'Viết lại chính xác lời ghi nhận đó, và một câu tôi tự nói với mình để giữ lại cảm giác này.'),
  ('P-03', 'Tôi giúp được đồng nghiệp gỡ một vấn đề khó', 'P-ACHIEVE', 'phat_trien', 'Hỗ trợ đồng nghiệp vượt qua khó khăn',
   ARRAY['ấm áp', 'hữu ích', 'kết nối'], ARRAY['lắng nghe', 'đặt câu hỏi', 'hỗ trợ'], ARRAY[]::text[], NULL,
   'Họ đã mắc kẹt một thời gian.
Tôi không có câu trả lời hoàn hảo, nhưng đặt vài câu hỏi và cùng họ nhìn lại vấn đề.
Cuối cùng họ tự tìm ra hướng đi.', 'Điều gì khiến tôi sẵn sàng dừng lại để giúp, dù có thể mình cũng đang bận?', 'Cảm giác sau khi giúp được ai đó khác gì với việc tự mình hoàn thành một việc?', 'Đôi khi giá trị lớn nhất mình mang lại không phải là câu trả lời, mà là sự có mặt đủ lâu để người khác tự tìm ra câu trả lời của họ.', 'Nhắn cho người đó một câu hỏi thăm xem hướng đi đó có thực sự hiệu quả không.'),
  ('P-04', 'Tôi được tăng lương hoặc thăng chức', 'P-ACHIEVE', 'phat_trien', 'Được tăng lương hoặc thăng chức',
   ARRAY['vui', 'ngỡ ngàng', 'áp lực'], ARRAY['ăn mừng', 'nghĩ về bước tiếp theo'], ARRAY[]::text[], NULL,
   'Sau một thời gian dài làm việc, điều đó cuối cùng cũng đến.
Tôi vui, nhưng cũng có chút ngỡ ngàng, như thể chưa kịp tin.', 'Điều gì trong hành trình vừa qua khiến tôi xứng đáng với điều này?', 'Tôi có đang cho phép mình thật sự vui với điều này không, hay đã vội nghĩ đến áp lực tiếp theo?', 'Kết quả tốt thường kéo theo kỳ vọng mới rất nhanh. Nhưng cho phép mình dừng lại ăn mừng cũng là một phần của hành trình, không phải sự xao nhãng.', 'Làm một điều nhỏ để tự thưởng cho mình trước khi nghĩ đến bước tiếp theo.'),
  ('P-05', 'Tôi nhận được lời cảm ơn bất ngờ từ ai đó', 'P-ACHIEVE', 'phat_trien', 'Nhận lời cảm ơn bất ngờ',
   ARRAY['bất ngờ', 'ấm áp', 'được nhìn thấy'], ARRAY['ghi nhận đóng góp nhỏ'], ARRAY[]::text[], NULL,
   'Tôi không nghĩ việc mình làm đáng để nhắc đến.
Nhưng ai đó chủ động nói lời cảm ơn, và điều đó khiến tôi bất ngờ.', 'Việc gì tôi làm mà tưởng là nhỏ, nhưng lại có ý nghĩa với người khác?', 'Tôi có hay đánh giá thấp những đóng góp thầm lặng của chính mình không?', 'Những điều mình cho là bình thường đôi khi lại là điều người khác nhớ lâu nhất.', 'Ghi lại việc đó, để nhắc mình rằng những đóng góp nhỏ vẫn có giá trị thật.'),
  ('P-06', 'Công việc hôm nay diễn ra đúng như tôi mong đợi', 'P-STEADY', 'phat_trien', 'Một ngày làm việc đúng kế hoạch',
   ARRAY['bình thản', 'hài lòng', 'nhẹ nhõm'], ARRAY['ghi nhận sự ổn định'], ARRAY[]::text[], NULL,
   'Không có gì bất ngờ.
Không có khủng hoảng.
Mọi việc tôi lên kế hoạch đều diễn ra như dự tính.', 'Những ngày như thế này có thường xảy ra với tôi không?', 'Tôi có coi trọng những ngày ổn định, hay chỉ chú ý khi có chuyện xảy ra?', 'Sự ổn định thường bị xem là hiển nhiên, trong khi nó là kết quả của rất nhiều điều đã được làm đúng phía sau.', 'Ghi lại một điều đã góp phần khiến hôm nay suôn sẻ.'),
  ('P-07', 'Tôi cảm thấy làm chủ được nhịp độ công việc của mình', 'P-STEADY', 'phat_trien', 'Làm chủ được nhịp độ công việc',
   ARRAY['chủ động', 'tự tin', 'thư thái'], ARRAY['sắp xếp ưu tiên', 'giữ nhịp'], ARRAY[]::text[], NULL,
   'Tôi không chạy theo deadline.
Tôi biết việc gì cần làm trước, việc gì có thể chờ.
Cảm giác này khá hiếm.', 'Điều gì khác biệt hôm nay so với những ngày tôi cảm thấy bị cuốn đi?', 'Tôi có thể giữ được nhịp độ này trong bao lâu?', 'Làm chủ nhịp độ không có nghĩa là làm ít hơn, mà là biết điều gì thực sự cần sự chú ý của mình lúc này.', 'Ghi lại cách tôi đã sắp xếp công việc hôm nay, để thử lặp lại vào ngày khác.'),
  ('P-08', 'Tôi vừa học được một điều nhỏ nhưng hữu ích', 'P-STEADY', 'phat_trien', 'Học được một điều nhỏ trong công việc',
   ARRAY['tò mò', 'hài lòng', 'sáng tỏ'], ARRAY['ghi lại bài học', 'áp dụng ngay'], ARRAY[]::text[], NULL,
   'Không phải điều gì lớn lao.
Nhưng nó giúp tôi làm một việc quen thuộc theo cách hiệu quả hơn.', 'Điều nhỏ này có thể thay đổi cách tôi làm việc về lâu dài không?', 'Tôi có thường bỏ qua những bài học nhỏ vì chúng không đủ lớn để ghi nhớ không?', 'Phần lớn sự tiến bộ không đến từ những bước ngoặt lớn, mà từ rất nhiều điều nhỏ được tích lũy.', 'Viết lại điều mình vừa học, bằng chính lời của mình.'),
  ('P-09', 'Tôi có một cuộc trò chuyện tốt với đồng nghiệp', 'P-STEADY', 'phat_trien', 'Một cuộc trò chuyện dễ chịu với đồng nghiệp',
   ARRAY['dễ chịu', 'kết nối', 'nhẹ nhõm'], ARRAY['chủ động trò chuyện', 'duy trì kết nối'], ARRAY[]::text[], NULL,
   'Không phải một cuộc họp quan trọng.
Chỉ là một cuộc trò chuyện ngắn, nhưng tôi rời đi với cảm giác dễ chịu.', 'Điều gì khiến cuộc trò chuyện đó khác với những cuộc trao đổi thường ngày?', 'Tôi có đang dành đủ thời gian cho những kết nối như vậy không?', 'Những mối quan hệ tốt trong công việc thường không được xây từ những cuộc họp lớn, mà từ rất nhiều cuộc trò chuyện nhỏ như thế này.', 'Chủ động tạo thêm một cuộc trò chuyện tương tự trong tuần này.'),
  ('P-10', 'Hôm nay không có gì đặc biệt, nhưng tôi thấy ổn', 'P-STEADY', 'phat_trien', 'Một ngày bình thường, không có gì đè nặng',
   ARRAY['bình yên', 'nhẹ nhàng', 'ổn định'], ARRAY['ghi nhận ngày bình thường'], ARRAY[]::text[], NULL,
   'Nếu phải kể lại, tôi sẽ không nhớ nhiều chi tiết.
Nhưng cảm giác chung là nhẹ nhàng, không có gì đè nặng.', 'Tôi có công nhận những ngày không có gì đặc biệt này không, hay chỉ nhớ những ngày nhiều biến động?', 'Điều gì đang diễn ra tốt mà tôi ít khi để ý tới?', 'Không phải mọi trải nghiệm đáng ghi nhớ đều kịch tính. Đôi khi sự bình yên cũng là một dữ liệu quan trọng.', 'Ghi một câu ngắn về cảm giác hôm nay, dù không có gì đặc biệt để kể.')
on conflict (story_id) do nothing;

-- SEED_END
