-- WorkReflection: Thư viện Nội dung Cảm xúc.
-- Kiến trúc Dữ liệu Hai Lớp v1.6 §VIII (thực thể mới), §8.1 schema, §XII.3.
--
-- Mục đích: gợi ý đọc hoặc nghe theo cảm xúc vừa check-in. Tách bạch khỏi
-- Practice Theme — trước đây gợi ý này bị nối nhầm sang tab Phát triển, nhưng
-- hai mạch cảm xúc và phát triển có mục đích khác nhau (§VIII).
--
-- §8.3: KHÔNG phân biệt Free/Paid. Đây là nội dung chăm sóc cảm xúc, không phải
-- trí tuệ rút ra từ dữ liệu cá nhân, nên không thuộc phạm vi phân lớp Hai Lớp.
--
-- ⚠ §XII.3: cột `script` chỉ dùng nội bộ cho đội sản xuất audio. Không được
--   trả về cho app. RLS dưới đây chặn ở tầng cột (xem policy + view).

create table if not exists public.wr_mood_content (
  id          uuid primary key default gen_random_uuid(),
  -- §8.1: khớp trực tiếp với 4 lựa chọn check-in ở Home.
  mood        text not null check (mood in ('stress','tired','ok','happy')),
  -- §8.3: Home hiện đúng mục đầu tiên của nhóm, nên thứ tự là dữ liệu, không
  -- phải chuyện hiển thị. Không có cột này thì "mục đầu tiên" là ngẫu nhiên.
  sort_order  smallint not null,
  title       text not null,
  kind        text not null check (kind in ('BÀI ĐỌC','HEALING AUDIO')),
  duration    text not null,
  type        text not null check (type in ('reading','audio')),
  -- BÀI ĐỌC: toàn văn. HEALING AUDIO: mô tả ngắn 1-2 câu dưới khối trình phát.
  body        text not null,
  -- Kịch bản lồng tiếng đầy đủ, có đánh dấu (dừng N giây). Null với BÀI ĐỌC.
  script      text,
  -- §8.2: true = còn nháp, chưa thu âm/biên tập. Hiển thị nhãn "Nháp".
  placeholder boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (mood, sort_order),
  -- §8.1: script chỉ dành cho HEALING AUDIO.
  constraint wr_mood_content_script_audio_only
    check (script is null or type = 'audio')
);

create index if not exists wr_mood_content_mood_idx
  on public.wr_mood_content (mood, sort_order);

-- ---------------------------------------------------------------------------
-- RLS: nội dung tĩnh, ai đăng nhập cũng đọc được (§8.3 không phân lớp).
--
-- Postgres RLS lọc theo DÒNG, không theo CỘT — nên policy dưới đây không giấu
-- được `script`. Việc giấu cột làm bằng view `wr_mood_content_public`, và
-- client chỉ được cấp quyền trên view đó.
-- ---------------------------------------------------------------------------

alter table public.wr_mood_content enable row level security;

drop policy if exists "wr_mood_content_public_read" on public.wr_mood_content;

create policy "wr_mood_content_public_read"
  on public.wr_mood_content
  for select
  using (auth.role() = 'authenticated');

-- ---------------------------------------------------------------------------
-- View public — §XII.3: "Trường script chỉ dùng nội bộ cho đội sản xuất audio,
-- không render ra API trả về cho app."
--
-- App LUÔN đọc qua view này. Nếu sau này ai đó lỡ trỏ repository thẳng vào
-- bảng gốc, kịch bản lồng tiếng sẽ rò ra client — nên view là ranh giới thật,
-- không phải quy ước đặt tên.
-- ---------------------------------------------------------------------------

create or replace view public.wr_mood_content_public
with (security_invoker = true) as
  select id, mood, sort_order, title, kind, duration, type, body,
         placeholder, created_at, updated_at
  from public.wr_mood_content;

comment on view public.wr_mood_content_public is
  'Thư viện Nội dung Cảm xúc cho app. Cố tình KHÔNG có cột script '
  '(Hai Lớp v1.6 §XII.3 — kịch bản lồng tiếng chỉ dùng nội bộ).';

grant select on public.wr_mood_content_public to authenticated;

-- ---------------------------------------------------------------------------
-- Seed — sinh từ assets/seed/wr_mood_content.json, KHÔNG sửa tay khối dưới.
--
--   python3 tool/gen_wr_mood_content_sql.py
--
-- §8.2: cả 20 mục đang placeholder = true. Chị đang chọn 2 mục mỗi cảm xúc để
-- thu âm/biên tập chính thức trước. Nội dung còn placeholder = true KHÔNG được
-- coi là sẵn sàng phát hành (§XII.3), chỉ dùng để demo luồng.
-- ---------------------------------------------------------------------------

-- SEED_START (generated by gen_wr_mood_content_sql.py)

insert into public.wr_mood_content
  (mood, sort_order, title, kind, duration, type, body, script, placeholder)
values
  ('stress', 1, 'Ba nhịp thở trước khi phản hồi',
   'HEALING AUDIO', '3 phút', 'audio',
   'Một bài hướng dẫn hít thở ngắn, giúp bạn lấy lại nhịp trước khi bước vào một cuộc trao đổi căng thẳng.',
   'Bạn không cần thay đổi tư thế đang ngồi. Chỉ cần để vai được thả lỏng một chút, nếu có thể. (dừng 3 giây)

Hít vào, chậm, qua mũi. (dừng 4 giây) Giữ lại một nhịp. (dừng 2 giây) Rồi thở ra, chậm hơn lúc hít vào. (dừng 5 giây) Cảm nhận vai hạ xuống một chút, ngay khi bạn thở ra. (dừng 3 giây)

Lần thứ hai. Hít vào, để ý xem bụng có phồng lên không. (dừng 4 giây) Giữ. (dừng 2 giây) Thở ra, để hơi thở thoát ra tự nhiên, không cần kiểm soát âm thanh của nó. (dừng 5 giây)

Một lần cuối. Hít vào. (dừng 4 giây) Giữ một nhịp. (dừng 2 giây) Thở ra, lần này dài hơn một chút so với hai lần trước. (dừng 6 giây)

Bạn không cần cảm thấy hoàn toàn bình tĩnh mới được phép tiếp tục. Ba nhịp thở này chỉ cần đủ, để điều bạn sắp nói ra, đến từ một nơi chậm hơn một chút, thay vì từ phản xạ đầu tiên.', true),
  ('stress', 2, 'Buông một việc, chỉ trong 60 giây',
   'HEALING AUDIO', '2 phút', 'audio',
   'Một bài dẫn rất ngắn giúp bạn tạm gác một việc đang chiếm hết tâm trí, để quay lại sau với một cái đầu nhẹ nhõm hơn.',
   NULL, true),
  ('stress', 3, 'Khi áp lực đến từ việc muốn kiểm soát mọi thứ',
   'BÀI ĐỌC', '4 phút đọc', 'reading',
   'Có những ngày căng thẳng đến từ một deadline gấp, một cuộc họp khó, một quyết định lớn cần đưa ra. Nhưng cũng có những ngày căng thẳng đến mà không có lý do rõ ràng nào cả. Không có sự kiện lớn nào xảy ra, chỉ là cảm giác nặng nề kéo dài từ sáng đến tối.

Nếu để ý kỹ hơn, một phần không nhỏ của loại căng thẳng này đến từ việc cố gắng kiểm soát những thứ vốn dĩ không hoàn toàn nằm trong tay mình. Kết quả một cuộc họp. Cách người khác phản ứng. Việc dự án có chạy đúng tiến độ hay không, dù mình đã làm xong phần việc của mình. Không chỉ lo cho phần của mình, mà còn âm thầm ôm luôn phần lo cho những thứ mình không thể quyết định.

Điều này không đến từ việc ai đó yếu đuối hay thiếu kỷ luật. Muốn kiểm soát thường là một phản xạ tự nhiên khi môi trường xung quanh có nhiều điều không chắc chắn. Càng ít cảm thấy an toàn với những gì sẽ xảy ra, người ta càng có xu hướng bám chặt vào những gì mình nghĩ mình kiểm soát được, dù đôi khi đó chỉ là một ảo giác về sự an toàn.

Một ví dụ nhỏ và quen thuộc: khi giao một phần việc cho đồng nghiệp, nhiều người vẫn tiếp tục kiểm tra, nhắc nhở, hoặc âm thầm làm lại phần đó theo cách của mình. Không hẳn vì không tin đồng nghiệp, mà vì cảm giác an tâm chỉ đến khi mọi thứ đi đúng như hình dung trong đầu mình. Nhưng cái giá của sự an tâm đó là năng lượng bị chia nhỏ ra quá nhiều đầu việc, thay vì tập trung vào nơi thực sự cần có mặt.

Một cách để nhận diện áp lực loại này là tự hỏi, điều đang lo thực sự nằm trong khả năng ảnh hưởng của mình đến đâu. Có việc có thể tác động trực tiếp. Có việc chỉ có thể góp phần, còn lại phụ thuộc vào người khác hoặc hoàn cảnh. Và có việc, dù muốn đến mấy, cũng nằm ngoài tầm với. Ba loại này thường bị gộp chung thành một khối lo lắng duy nhất, khiến năng lượng bị dàn trải đều, thay vì dồn vào đúng chỗ có thể tạo ra khác biệt thật sự.

Không phải lúc nào việc buông bớt kiểm soát cũng dễ dàng, đặc biệt với những điều mình thực sự quan tâm. Nhưng đôi khi, chỉ cần gọi tên được phần nào trong nỗi lo hiện tại là điều có thể tác động, và phần nào không, cũng đã đủ để căng thẳng nhẹ đi một chút.',
   NULL, true),
  ('stress', 4, 'Căng thẳng không phải là kẻ thù, chỉ là tín hiệu',
   'BÀI ĐỌC', '3 phút đọc', 'reading',
   'Căng thẳng thường bị xem là điều cần loại bỏ. Nhưng đôi khi nó chỉ đang báo hiệu một điều gì đó cần được chú ý, không phải một kẻ thù cần bị đánh bại.',
   NULL, true),
  ('stress', 5, 'Ba phút lặng trước một cuộc họp khó',
   'HEALING AUDIO', '3 phút', 'audio',
   'Một khoảng lặng ngắn để chuẩn bị tâm thế trước khi bước vào một cuộc trao đổi bạn biết sẽ không dễ dàng.',
   NULL, true),
  ('tired', 1, 'Một khoảng lặng 5 phút',
   'HEALING AUDIO', '5 phút', 'audio',
   'Không cần làm gì thêm trong 5 phút này, chỉ cần để cơ thể và tâm trí được nghỉ trước khi tiếp tục.',
   NULL, true),
  ('tired', 2, 'Kiệt sức không phải là yếu đuối',
   'BÀI ĐỌC', '4 phút đọc', 'reading',
   'Kiệt sức thường bị hiểu nhầm là dấu hiệu của sự yếu đuối. Thực ra nó thường là dấu hiệu bạn đã cố gắng rất nhiều, trong một thời gian rất dài.',
   NULL, true),
  ('tired', 3, 'Âm thanh mưa nhẹ để nghỉ ngơi',
   'HEALING AUDIO', '8 phút', 'audio',
   'Một nền âm thanh mưa nhẹ, phù hợp cho một khoảng nghỉ ngắn giữa ngày hoặc trước khi bắt đầu lại công việc.',
   NULL, true),
  ('tired', 4, 'Khi nào nên nghỉ, khi nào nên tiếp tục',
   'BÀI ĐỌC', '4 phút đọc', 'reading',
   'Không phải lúc nào mệt mỏi cũng có nghĩa là phải dừng lại hoàn toàn. Bài viết này giúp bạn phân biệt giữa mệt cần nghỉ và mệt cần một cách tiếp cận khác.',
   NULL, true),
  ('tired', 5, 'Cho phép mình chậm lại hôm nay',
   'HEALING AUDIO', '4 phút', 'audio',
   'Một bài dẫn nhẹ nhàng nhắc bạn rằng chậm lại một ngày không làm bạn tụt lại phía sau.',
   NULL, true),
  ('ok', 1, 'Điều gì đang vận hành tốt trong bạn?',
   'BÀI ĐỌC', '4 phút đọc', 'reading',
   'Những ngày ổn định là lúc tốt nhất để nhận diện điều gì đang thực sự hiệu quả, trước khi mọi thứ thay đổi trở lại.',
   NULL, true),
  ('ok', 2, 'Nhạc nền tập trung nhẹ nhàng',
   'HEALING AUDIO', '10 phút', 'audio',
   'Một nền âm thanh nhẹ, phù hợp cho một buổi làm việc tập trung khi mọi thứ đang khá ổn.',
   NULL, true),
  ('ok', 3, 'Sự ổn định cũng là một thành tựu',
   'BÀI ĐỌC', '3 phút đọc', 'reading',
   'Những ngày không có biến động thường ít được ghi nhận nhất, dù chúng thường là kết quả của rất nhiều điều đã được làm đúng.',
   NULL, true),
  ('ok', 4, '5 phút định tâm giữa ngày',
   'HEALING AUDIO', '5 phút', 'audio',
   'Một bài dẫn ngắn giúp bạn dừng lại giữa một ngày làm việc bình thường, để cảm nhận rõ hơn trạng thái hiện tại của mình.',
   NULL, true),
  ('ok', 5, 'Những ngày bình thường đáng được ghi nhớ',
   'BÀI ĐỌC', '3 phút đọc', 'reading',
   'Không phải mọi điều đáng nhớ đều kịch tính. Bài viết này nói về giá trị của những ngày không có gì đặc biệt để kể.',
   NULL, true),
  ('happy', 1, 'Ghi lại khoảnh khắc này trước khi nó trôi qua',
   'BÀI ĐỌC', '3 phút đọc', 'reading',
   'Niềm vui thường trôi qua nhanh và ít được ghi nhớ hơn khó khăn. Một vài dòng ngắn có thể giữ lại điều này lâu hơn.',
   NULL, true),
  ('happy', 2, 'Biết ơn trong 2 phút',
   'HEALING AUDIO', '2 phút', 'audio',
   'Một bài dẫn ngắn giúp bạn gọi tên điều đang khiến hôm nay tốt đẹp, để cảm xúc này được ghi nhớ rõ hơn.',
   NULL, true),
  ('happy', 3, 'Niềm vui hôm nay, dữ liệu cho ngày mai',
   'BÀI ĐỌC', '3 phút đọc', 'reading',
   'Những khoảnh khắc vui vẻ hôm nay, nếu được ghi lại, có thể trở thành manh mối quý giá cho việc hiểu điều gì thực sự phù hợp với bạn.',
   NULL, true),
  ('happy', 4, 'Âm thanh ăn mừng nhẹ nhàng',
   'HEALING AUDIO', '3 phút', 'audio',
   'Một bài dẫn ngắn giúp bạn thật sự dừng lại và tận hưởng một tin vui, thay vì vội vàng chuyển sang việc tiếp theo.',
   NULL, true),
  ('happy', 5, 'Ai xứng đáng biết về điều này?',
   'BÀI ĐỌC', '3 phút đọc', 'reading',
   'Đôi khi niềm vui trở nên trọn vẹn hơn khi được chia sẻ. Bài viết ngắn này gợi ý một vài cách để không giữ tin vui một mình.',
   NULL, true)
on conflict (mood, sort_order) do nothing;

-- SEED_END
