-- WorkReflection: wr_situations, wr_stories, wr_career_memory_events
-- Content tables (read-only for authenticated), event table (owner-only RLS)
-- Applies to project sukpcxevcjnhiuyaoqxi (shared with web app)
-- DO NOT push without Fable approval — dry-run only.

create table if not exists public.wr_situations (
  code            text primary key,
  text            text not null,
  sca_dimension   text not null check (sca_dimension in ('S1','S2','S3','C1','C2','C3','A1','A2','A3','A4')),
  human_need      text check (human_need in ('ro_rang','ket_noi','thich_nghi','phat_trien')),
  expected_outcome text,
  sca_perspective  text,
  wave            smallint not null default 3 check (wave between 1 and 3),
  created_at      timestamptz not null default now()
);

create table if not exists public.wr_stories (
  story_id          text primary key,
  title             text not null,
  sca_dimension     text not null check (sca_dimension in ('S1','S2','S3','C1','C2','C3','A1','A2','A3','A4')),
  human_need        text check (human_need in ('ro_rang','ket_noi','thich_nghi','phat_trien')),
  situation         text,
  emotion_tags      text[] not null default '{}',
  behavior_tags     text[] not null default '{}',
  career_stages     text[] not null default '{}',
  difficulty_level  smallint check (difficulty_level between 1 and 3),
  story_content     text not null,
  reflection_question text,
  self_reflection   text,
  aha_message       text,
  practice_action   text,
  created_at        timestamptz not null default now()
);

create table if not exists public.wr_career_memory_events (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users(id) on delete cascade,
  story_id         text references public.wr_stories(story_id),
  situation_code   text references public.wr_situations(code),
  human_need       text check (human_need in ('ro_rang','ket_noi','thich_nghi','phat_trien')),
  sca_dimension    text check (sca_dimension in ('S1','S2','S3','C1','C2','C3','A1','A2','A3','A4')),
  emotion          text,
  behavior         text,
  intensity        smallint check (intensity between 1 and 5),
  reflection_text  text,
  career_stage     text,
  created_at       timestamptz not null default now()
);

-- Indexes
create index if not exists wr_situations_sca_dim_idx   on public.wr_situations (sca_dimension);
create index if not exists wr_stories_sca_dim_idx      on public.wr_stories (sca_dimension);
create index if not exists wr_career_memory_user_idx   on public.wr_career_memory_events (user_id, created_at desc);

-- RLS: content tables → authenticated read-only (no write policies)
alter table public.wr_situations   enable row level security;
alter table public.wr_stories      enable row level security;

drop policy if exists "wr_situations_public_read"  on public.wr_situations;
drop policy if exists "wr_stories_public_read"     on public.wr_stories;

create policy "wr_situations_public_read"
  on public.wr_situations
  for select
  using (auth.role() = 'authenticated');

create policy "wr_stories_public_read"
  on public.wr_stories
  for select
  using (auth.role() = 'authenticated');

-- RLS: wr_career_memory_events → owner-only 4 policies (same pattern as wr_checkins)
alter table public.wr_career_memory_events enable row level security;

drop policy if exists "wr_career_memory_events_owner_select" on public.wr_career_memory_events;
drop policy if exists "wr_career_memory_events_owner_insert" on public.wr_career_memory_events;
drop policy if exists "wr_career_memory_events_owner_update" on public.wr_career_memory_events;
drop policy if exists "wr_career_memory_events_owner_delete" on public.wr_career_memory_events;

create policy "wr_career_memory_events_owner_select"
  on public.wr_career_memory_events
  for select
  using (auth.uid() = user_id);

create policy "wr_career_memory_events_owner_insert"
  on public.wr_career_memory_events
  for insert
  with check (auth.uid() = user_id);

create policy "wr_career_memory_events_owner_update"
  on public.wr_career_memory_events
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "wr_career_memory_events_owner_delete"
  on public.wr_career_memory_events
  for delete
  using (auth.uid() = user_id);

-- SEED_START (generated by gen_wr_seed_sql.py)

-- wr_situations seed
insert into public.wr_situations
  (code, text, sca_dimension, human_need, expected_outcome, sca_perspective, wave)
values
  ('S1-sit-01', 'Không rõ mình được kỳ vọng điều gì', 'S1', 'ro_rang', 'Tôi muốn biết rõ mình cần đạt được điều gì để được coi là làm tốt', 'Khi không biết tiêu chí hoàn thành của công việc là gì, người làm giỏi đến đâu cũng khó yên tâm. Cảm giác mơ hồ này thường không phải do bạn mà do kỳ vọng chưa được nói rõ từ đầu hoặc kỳ vọng bị leo thang.', 2),
  ('S1-sit-02', 'Không rõ trách nhiệm thuộc về ai', 'S1', 'ro_rang', 'Tôi muốn biết ai chịu trách nhiệm việc gì để không bị kẹt ở giữa', 'Khi ranh giới không rõ, ai cũng có thể làm và ai cũng có thể không làm. Bạn bị kẹt ở giữa không phải vì thiếu năng lực mà vì chưa ai vẽ rõ vai trò của mình cũng', 2),
  ('S1-sit-03', 'Vai trò chồng chéo với người khác', 'S1', 'ro_rang', 'Tôi muốn có ranh giới đủ rõ để làm việc không bị giẫm chân nhau', 'Giẫm chân nhau không có nghĩa là ai sai mà là phạm vi chưa được phân định rõ để mỗi người biết mình phụ trách đến đâu. Ma sát này không phải vấn đề cá nhân.', 2),
  ('S1-sit-04', 'Công việc thay đổi liên tục, không ổn định', 'S1', 'ro_rang', 'Tôi muốn có đủ ổn định để lên kế hoạch và làm việc có chiều sâu', 'Khi ưu tiên liên tục thay đổi mà không có giải thích, bạn không thể đầu tư thật sự vào bất cứ điều gì. Đó là lý do bạn luôn bận nhưng ít khi cảm thấy mình đã làm được gì.', 2),
  ('S1-sit-05', 'Không biết thế nào là làm tốt', 'S1', 'ro_rang', 'Tôi muốn có tiêu chí cụ thể để biết khi nào mình thực sự đã làm tốt', 'Thiếu tiêu chí rõ ràng, người làm tốt và người làm qua loa nhìn từ ngoài không khác nhau là mấy. Điều đó không công bằng với người thực sự nỗ lực.', 2),
  ('S1-sit-06', 'Không biết ưu tiên điều gì trước', 'S1', 'ro_rang', 'Tôi muốn có thứ tự ưu tiên rõ ràng để tập trung đúng chỗ', 'Khi mọi thứ đều quan trọng, thực chất không có gì quan trọng hơn cái gì. Bạn không thiếu kỷ luật mà thiếu một hệ thống giúp mình nhìn thấy đâu là việc thật sự cần làm trước.', 2),
  ('S2-sit-01', 'Khó phối hợp với phòng ban khác', 'S2', 'ro_rang', 'Tôi muốn có quy ước làm việc chung để phối hợp suôn sẻ hơn', 'Phối hợp khó không phải vì người ta không muốn hợp tác mà vì mỗi bên đang chạy theo một bộ quy tắc khác nhau mà không ai biết. Cần một ngôn ngữ chung trước khi có thể làm việc cùng nhau thật sự.', 3),
  ('S2-sit-02', 'Người khác làm chậm tiến độ của tôi', 'S2', 'ro_rang', 'Tôi muốn có quy trình rõ để không bị phụ thuộc mà không kiểm soát được', 'Khi tiến độ của bạn phụ thuộc vào người khác nhưng không có điểm bàn giao rõ ràng, bạn chỉ có thể chờ và lo mà không có cách nào chủ động hơn được.', 3),
  ('S2-sit-03', 'Không biết tìm ai khi cần hỗ trợ', 'S2', 'ro_rang', 'Tôi muốn biết rõ ai là người tôi cần liên hệ trong từng tình huống', 'Mất thời gian tìm đúng người không phải do bạn không biết hỏi mà là tổ chức chưa làm rõ ai phụ trách điều gì khi có vấn đề phát sinh.', 3),
  ('S2-sit-04', 'Làm việc nhóm không hiệu quả', 'S2', 'ro_rang', 'Tôi muốn nhóm có cách làm việc chung đủ rõ để cùng nhau tiến được', 'Nhóm giỏi không tự nhiên phối hợp tốt mà họ có quy ước chung và cùng hiểu quy ước đó. Khi thiếu nền tảng đó, cả nhóm có thể nỗ lực mà vẫn không đi cùng hướng.', 3),
  ('S2-sit-05', 'Thường xuyên phải làm lại vì hiểu sai', 'S2', 'ro_rang', 'Tôi muốn có cách xác nhận yêu cầu rõ ràng trước khi bắt tay làm', 'Phải làm lại nhiều lần không phải bạn nghe kém hay không chú ý mà là chưa có bước xác nhận hiểu chung trước khi triển khai. Lỗi xảy ra ở bước đầu tiên, không phải bước cuối.', 3),
  ('S3-sit-01', 'Không biết tìm thông tin ở đâu', 'S3', 'ro_rang', 'Tôi muốn biết rõ kênh nào chứa loại thông tin nào để không mất công tìm vòng', 'Khi không có bản đồ thông tin rõ ràng, người mới hay người cũ đều phải tự mày mò. Thời gian mất đi không phải vì lười mà vì hệ thống chưa chỉ rõ ai cần tìm gì ở đâu.', 3),
  ('S3-sit-02', 'Thông tin đến quá muộn', 'S3', 'ro_rang', 'Tôi muốn được cập nhật đúng lúc để không phải quyết định trong mù mờ', 'Ra quyết định thiếu thông tin không phải bạn vội vàng mà thông tin đến sau khi bạn đã phải hành động rồi. Cảm giác bị động này xuất phát từ nhịp cập nhật chưa được thiết kế đủ kịp thời.', 3),
  ('S3-sit-03', 'Thông tin mâu thuẫn nhau', 'S3', 'ro_rang', 'Tôi muốn có nguồn thông tin đáng tin để không phải tự đoán đâu là đúng', 'Khi nhiều kênh song song cùng nói về một việc theo những cách khác nhau, bạn không thể tin ai cả và phải tự quyết định dựa trên phán đoán cá nhân thay vì sự thật chung.', 3),
  ('S3-sit-04', 'Không được cập nhật khi có thay đổi', 'S3', 'ro_rang', 'Tôi muốn được biết khi có gì thay đổi ảnh hưởng đến công việc của mình', 'Chỉ biết có thay đổi sau khi đã bị ảnh hưởng là cảm giác bị để ngoài dù mình vẫn đang làm đúng công việc của mình. Vấn đề không phải bạn không hỏi mà là chưa có ai có trách nhiệm chủ động thông báo.', 3),
  ('S3-sit-05', 'Luôn cảm thấy mình bị động', 'S3', 'ro_rang', 'Tôi muốn có đủ thông tin để chủ động thay vì liên tục phản ứng với những gì xảy ra', 'Bị động không phải tính cách mà là kết quả tự nhiên khi thông tin luôn đến sau khi cần. Bạn không thể chủ động nếu môi trường xung quanh không cung cấp đủ để lên kế hoạch trước.', 3),
  ('C1-sit-01', 'Không tin đồng nghiệp sẽ hoàn thành việc', 'C1', 'ket_noi', 'Tôi muốn có thể tin tưởng người làm cùng mà không cần phải kiểm tra từng bước', 'Khi bạn phải kiểm tra liên tục mới yên tâm, đó không phải bạn hay lo. Đó là dấu hiệu niềm tin trong nhóm đang thiếu nền tảng thực sự, thường do lịch sử thất hứa tích lũy theo thời gian.', 1),
  ('C1-sit-02', 'Không được cấp trên tin tưởng', 'C1', 'ket_noi', 'Tôi muốn được trao đủ quyền tự chủ tương xứng với năng lực của mình', 'Khi cấp trên không trao quyền, cảm giác đó nặng hơn là chỉ bực bội. Nó như thông điệp ngầm rằng năng lực của mình chưa đủ để tin. Nhưng đôi khi vấn đề không phải ở bạn mà ở một nền văn hoá chưa biết cách trao quyền thực sự.', 1),
  ('C1-sit-03', 'Bị kiểm soát quá mức', 'C1', 'ket_noi', 'Tôi muốn được làm việc với đủ không gian để phát huy năng lực thực sự của mình', 'Bị kiểm soát quá mức làm mòn động lực ngay cả với người giỏi nhất. Khi không ai tin bạn đủ để để bạn tự quyết, bạn dần ngừng chủ động. Không phải vì lười mà vì chủ động rồi cũng không có tác dụng.', 1),
  ('C1-sit-04', 'Cảm thấy phải tự làm mọi thứ', 'C1', 'ket_noi', 'Tôi muốn có thể dựa vào người khác thực sự thay vì luôn phải tự lo', 'Khi giao việc tốn công hơn tự làm, người làm sẽ chọn ôm hết về mình. Không phải vì muốn kiểm soát mà vì chi phí tin tưởng đang cao hơn lợi ích hợp tác.', 1),
  ('C2-sit-01', 'Không dám lên tiếng', 'C2', 'ket_noi', 'Tôi muốn có thể nói thật mà không lo bị đánh giá hay bị thiệt', 'Im lặng khi biết có vấn đề là điều nặng nề. Bạn không thiếu dũng cảm mà đang bảo vệ mình trong một môi trường chưa đủ an toàn để nói thật. Đó là phản ứng lành mạnh trước một điều kiện không lành mạnh.', 1),
  ('C2-sit-02', 'Không được lắng nghe', 'C2', 'ket_noi', 'Tôi muốn ý kiến của mình được xem xét thực sự chứ không chỉ được nghe cho có', 'Cảm giác nói mà không ai thật sự nghe là một trong những thứ làm người ta kiệt sức nhất ở chỗ làm. Không phải bạn nói sai mà văn hoá nhóm chưa tạo ra không gian để ý kiến của mọi người thực sự được đón nhận.', 1),
  ('C2-sit-03', 'Ý kiến bị bỏ qua', 'C2', 'ket_noi', 'Tôi muốn thấy đóng góp của mình tạo ra sự khác biệt dù nhỏ', 'Khi đóng góp liên tục bị bỏ qua, người ta không chỉ ngừng đóng góp mà còn ngừng tin rằng mình có giá trị ở đây. Đây là mất mát lớn cho cả bạn lẫn nhóm.', 1),
  ('C2-sit-04', 'Sợ phản hồi cấp trên', 'C2', 'ket_noi', 'Tôi muốn có thể mang vấn đề lên cấp trên mà không sợ bị phán xét hay bất lợi', 'Sợ phản hồi cấp trên không phải bạn yếu hay thiếu tự tin. Đó là phản ứng hợp lý khi kinh nghiệm trước đó cho thấy lên tiếng có thể có hậu quả. Tổ chức nào mà cấp dưới im lặng, thường không phải vì không có gì để nói.', 1),
  ('C2-sit-05', 'Tiếng nói của mình không có giá trị', 'C2', 'ket_noi', 'Tôi muốn cảm thấy sự có mặt của mình tạo ra đóng góp thực sự cho nhóm', 'Cảm giác tiếng nói không có trọng lượng tích lũy âm thầm và đến một lúc người ta không còn cố gắng nữa. Không phải vì bỏ cuộc mà vì không còn thấy đủ lý do để tiếp tục đầu tư.', 1),
  ('C3-sit-01', 'Có mâu thuẫn nhưng không thể nói ra', 'C3', 'ket_noi', 'Tôi muốn có thể giải quyết bất đồng mà không làm hỏng mối quan hệ', 'Giữ mâu thuẫn trong lòng không phải bạn ngại va chạm mà bạn đang cẩn thận bảo vệ một mối quan hệ quan trọng. Vấn đề là khi không có không gian an toàn để nói, mâu thuẫn không biến mất mà chỉ đi sâu hơn.', 3),
  ('C3-sit-02', 'Tránh các cuộc trò chuyện khó', 'C3', 'ket_noi', 'Tôi muốn có thể nói thẳng những điều khó mà không tạo ra căng thẳng không cần thiết', 'Tránh cuộc trò chuyện khó không phải hèn. Đó là quyết định hợp lý khi bạn chưa biết nói thế nào mà không làm mọi thứ tệ hơn. Kỹ năng đó có thể học được nhưng cần có môi trường đủ an toàn để thử.', 3),
  ('C3-sit-03', 'Phản hồi dễ trở thành tranh cãi', 'C3', 'ket_noi', 'Tôi muốn trao đổi phản hồi mang tính xây dựng thay vì bảo vệ lập trường', 'Khi phản hồi dễ bị đọc là công kích, cả hai bên đều phòng thủ trước khi kịp lắng nghe. Điều này không phải vì ai đó khó tính mà vì chưa có chuẩn mực chung về cách đưa và nhận phản hồi an toàn.', 3),
  ('C3-sit-04', 'Không hiểu nhau dù đã trao đổi', 'C3', 'ket_noi', 'Tôi muốn đảm bảo sau khi trao đổi xong cả hai thực sự hiểu nhau đúng nghĩa', 'Nói nhiều mà không hiểu nhau không phải ai thiếu năng lực giao tiếp mà là chưa có thói quen dừng lại kiểm tra xem mình có thực sự đang hiểu cùng một điều không.', 3),
  ('C3-sit-05', 'Bầu không khí căng thẳng kéo dài', 'C3', 'ket_noi', 'Tôi muốn môi trường làm việc đủ thoải mái để tập trung thật sự thay vì liên tục ở trạng thái căng', 'Căng thẳng kéo dài ngốn năng lượng ngay cả khi bạn không làm gì sai. Đó là dấu hiệu nhiều thứ đang không được nói ra và không được xử lý, không phải chỉ một người hay một vấn đề.', 3),
  ('A1-sit-01', 'Không hiểu mục tiêu chung của tổ chức', 'A1', 'phat_trien', 'Tôi muốn hiểu tổ chức đang đi đâu để biết mình đang đóng góp vào điều gì', 'Làm việc mà không thấy bức tranh lớn giống như đang ghép puzzle nhưng không ai cho xem hình mẫu. Bạn có thể làm đúng từng mảnh nhưng không biết chúng đang tạo ra gì.', 1),
  ('A1-sit-02', 'Không biết công việc mình đóng góp điều gì', 'A1', 'phat_trien', 'Tôi muốn thấy rõ công việc của mình tạo ra giá trị gì cho người khác hoặc cho mục tiêu lớn hơn', 'Khi không thấy công việc của mình tạo ra điều gì có nghĩa, dần dần bạn chỉ hoàn thành nhiệm vụ chứ không còn thực sự đầu tư. Đó là dấu hiệu bình thường khi sợi dây kết nối với mục tiêu chung bị đứt.', 1),
  ('A1-sit-03', 'Làm rất nhiều nhưng không thấy ý nghĩa', 'A1', 'phat_trien', 'Tôi muốn cảm thấy công việc có ý nghĩa thực sự chứ không chỉ là hoàn thành nhiệm vụ', 'Bận mà trống rỗng là một trong những cảm giác mệt mỏi nhất. Không phải vì bạn làm ít mà vì bạn không thấy lý do thực sự cho những gì mình đang làm. Đây không phải vấn đề thái độ.', 1),
  ('A1-sit-04', 'Mục tiêu thay đổi liên tục mà không giải thích', 'A1', 'phat_trien', 'Tôi muốn hiểu lý do khi mục tiêu thay đổi để có thể điều chỉnh đúng hướng thay vì bị cuốn', 'Khi hướng đi thay đổi liên tục mà không có giải thích, bạn không thể điều chỉnh mà chỉ có thể chạy theo. Cảm giác mất phương hướng đó không phải bạn không thích nghi được mà không ai chỉ rõ hướng mới là gì và tại sao.', 1),
  ('A1-sit-05', 'Muốn chuyển việc vì không còn thấy phù hợp', 'A1', 'phat_trien', 'Tôi muốn làm rõ liệu đây là vấn đề với tổ chức này, với nghề, hay với công việc cụ thể', 'Muốn rời đi có thể là tín hiệu bạn cần thay đổi hoặc cũng có thể là dấu hiệu bạn đã lâu không thấy ý nghĩa trong những gì mình đang làm. Hai điều đó cần được phân biệt trước khi quyết định bước tiếp theo.', 1),
  ('A2-sit-01', 'Luôn bận nhưng không hiệu quả', 'A2', 'phat_trien', 'Tôi muốn bận vào đúng việc quan trọng thay vì bận vì liên tục phải phản ứng với mọi thứ', 'Bận mà không hiệu quả là dấu hiệu bạn đang phản ứng nhiều hơn là chủ động. Không phải bạn chậm hay thiếu tập trung mà nhịp làm việc xung quanh không bảo vệ thời gian cho những việc thực sự quan trọng.', 2),
  ('A2-sit-02', 'Công việc liên tục bị gián đoạn', 'A2', 'thich_nghi', 'Tôi muốn có đủ khối thời gian liên tục để làm việc có chiều sâu', 'Làm việc sâu cần thời gian liên tục và điều đó không thể có khi mọi thứ liên tục cắt ngang. Bạn không thiếu kỷ luật mà thiếu một môi trường bảo vệ được không gian tập trung.', 2),
  ('A2-sit-03', 'Quá tải công việc', 'A2', 'thich_nghi', 'Tôi muốn khối lượng công việc được phân bổ hợp lý với năng lực và thời gian thực tế của mình', 'Quá tải kéo dài không phải vấn đề cá nhân cần giải quyết bằng cách cố thêm. Đó là dấu hiệu tải công việc chưa được nhìn thấy và cân bằng một cách có chủ ý trong nhóm.', 2),
  ('A2-sit-04', 'Luôn trong trạng thái chạy theo deadline', 'A2', 'thich_nghi', 'Tôi muốn lên kế hoạch đủ tốt để không liên tục rơi vào trạng thái khủng hoảng', 'Khi mọi deadline đều gấp, không phải bạn không biết lên kế hoạch mà là không có đủ thời gian và sự ổn định để lên kế hoạch thực sự. Khủng hoảng liên tục là dấu hiệu hệ thống, không phải cá nhân.', 2),
  ('A3-sit-01', 'Không biết mình đang tiến bộ hay thụt lùi', 'A3', 'phat_trien', 'Tôi muốn có cách nhìn thấy rõ mình đang phát triển như thế nào theo thời gian', 'Khi không có gì để nhìn lại, rất khó thấy mình đã đi được bao xa. Cảm giác đứng yên thường không phải bạn không tiến mà là bạn chưa có cách nhìn thấy sự tiến bộ của mình.', 1),
  ('A3-sit-02', 'Liên tục lặp lại cùng một vấn đề', 'A3', 'thich_nghi', 'Tôi muốn hiểu nguyên nhân gốc rễ để thoát ra khỏi vòng lặp này', 'Lặp lại cùng vấn đề không phải bạn không học hỏi mà là chưa có không gian để thực sự nhìn lại và hiểu tại sao. Kinh nghiệm không tự động thành bài học mà cần được xử lý.', 1),
  ('A3-sit-03', 'Không hiểu nguyên nhân của sự thất vọng', 'A3', 'phat_trien', 'Tôi muốn hiểu điều gì thực sự đang xảy ra thay vì chỉ cảm thấy không ổn', 'Thất vọng thường không phải vì bạn yếu hay sai. Nó thường đến từ nhu cầu phát triển và được ghi nhận chưa được đáp ứng. Hiểu được điều đó là bước đầu tiên để thay đổi được gì đó.', 1),
  ('A3-sit-04', 'Đưa ra quyết định theo cảm xúc', 'A3', 'thich_nghi', 'Tôi muốn có thể quyết định sáng suốt hơn khi cảm xúc đang lên cao', 'Quyết định theo cảm xúc thường xảy ra khi bạn không có không gian để dừng lại và nhìn rõ hơn. Không phải bạn không lý trí mà là cảm xúc đang lớn hơn khả năng xử lý trong thời điểm đó.', 1),
  ('A3-sit-05', 'Cảm thấy bị mắc kẹt', 'A3', 'thich_nghi', 'Tôi muốn thấy được lối ra hoặc ít nhất là hiểu rõ mình đang thực sự ở đâu', 'Cảm giác mắc kẹt nặng nhất là khi bạn không thấy lối ra. Không phải vì không có mà vì bạn đang ở trong đó quá lâu mà không có dịp nhìn từ bên ngoài.', 1),
  ('A4-sit-01', 'Mắc lại cùng một sai lầm', 'A4', 'phat_trien', 'Tôi muốn rút ra bài học thực sự để không phải trả giá cho cùng sai lầm nhiều lần', 'Mắc lại cùng sai lầm không có nghĩa bạn không cố mà là trải nghiệm chưa được chuyển thành bài học cụ thể có thể hành động. Hiểu rồi mà vẫn lặp lại, thường là do hiểu chưa đủ sâu.', 2),
  ('A4-sit-02', 'Học nhiều nhưng khó áp dụng', 'A4', 'phat_trien', 'Tôi muốn biến những gì học được thành thay đổi thực sự trong cách làm việc của mình', 'Học nhiều mà ít thay đổi được không phải bạn không chịu áp dụng mà là thiếu vòng lặp từ học sang thử sang điều chỉnh thực tế. Kiến thức không tự biến thành kỹ năng nếu không qua thực hành có phản hồi.', 2),
  ('A4-sit-03', 'Không biến trải nghiệm thành bài học', 'A4', 'phat_trien', 'Tôi muốn có cách tổng kết những gì đã trải qua để tích lũy được sự khôn ngoan thực sự', 'Trải nghiệm và bài học là hai thứ khác nhau. Bạn có thể có nhiều năm kinh nghiệm mà vẫn cảm thấy mình không học được gì nhiều nếu những gì đã qua chưa bao giờ được nhìn lại đủ sâu.', 2),
  ('A4-sit-04', 'Muốn thăng tiến nhưng thiếu định hướng', 'A4', 'phat_trien', 'Tôi muốn có bức tranh rõ về những gì cần phát triển để đạt được mục tiêu nghề nghiệp của mình', 'Muốn đi lên nhưng không biết đi theo hướng nào là cảm giác dễ khiến người ta nản. Không phải bạn thiếu tham vọng mà bạn thiếu một hệ thống giúp nhìn thấy khoảng cách giữa nơi mình đang đứng và nơi muốn đến.', 2),
  ('A4-sit-05', 'Muốn chuyển nghề nhưng chưa rõ con đường', 'A4', 'phat_trien', 'Tôi muốn hiểu rõ mình đang có gì và cần gì trước khi quyết định bước tiếp theo', 'Bước ra khỏi ngành quen là một quyết định lớn và càng khó hơn khi bạn chưa nhìn rõ mình đang có những giá trị gì có thể mang sang. Chuyển nghề thành công thường bắt đầu từ việc hiểu mình trước khi tìm con đường.', 2)
on conflict (code) do nothing;

-- wr_stories seed
insert into public.wr_stories
  (story_id, title, sca_dimension, human_need, situation,
   emotion_tags, behavior_tags, career_stages, difficulty_level,
   story_content, reflection_question, self_reflection, aha_message, practice_action)
values
  ('A1-01', 'Tôi đang đi rất nhanh, nhưng đi đâu?', 'A1', 'thich_nghi', 'Không biết mình đang đi đúng hướng không',
   ARRAY['hoang mang', 'nghi ngờ', 'mất phương hướng'], ARRAY['tìm kiếm định hướng', 'đổi mục tiêu'], ARRAY[]::text[], NULL,
   'Bạn vẫn hoàn thành công việc.
Bạn vẫn đạt KPI.
Bạn vẫn được đánh giá tốt.
Nhưng mỗi khi ai đó hỏi:
"Bạn muốn mình ở đâu sau 3 năm nữa?"
Bạn không biết trả lời thế nào.', 'Bạn có đang bận rộn hơn là có định hướng không?', 'Điều gì khiến bạn tin rằng mình đang đi đúng hướng?', 'Mất phương hướng không phải là đứng yên.
Đôi khi nó là di chuyển rất nhanh mà không biết vì sao mình đang chạy.', 'Viết ra 3 điều bạn muốn có trong sự nghiệp 3 năm tới.'),
  ('A1-02', 'Tôi muốn nghỉ việc, nhưng không biết muốn điều gì khác', 'A1', 'thich_nghi', 'Muốn chuyển việc',
   ARRAY['chán nản', 'tò mò', 'kỳ vọng'], ARRAY['tìm việc mới', 'cập nhật CV'], ARRAY[]::text[], NULL,
   'Bạn thường xuyên nghĩ tới việc nghỉ việc.
Nhưng khi tự hỏi:
"Nếu nghỉ rồi thì mình muốn gì?"
Bạn không có câu trả lời rõ ràng.', 'Bạn đang muốn rời khỏi điều gì hay đang hướng tới điều gì?', 'Điều gì đang khiến bạn muốn thay đổi?', 'Rời khỏi một nơi không đồng nghĩa với việc đã biết nơi mình muốn đến.', 'Liệt kê điều bạn muốn có ở công việc tiếp theo.'),
  ('A1-03', 'Tôi làm rất nhiều nhưng không thấy ý nghĩa', 'A1', 'thich_nghi', 'Không thấy ý nghĩa công việc',
   ARRAY['trống rỗng', 'mất động lực'], ARRAY['làm cho xong', 'giảm cam kết'], ARRAY[]::text[], NULL,
   'Bạn hoàn thành mọi việc cần làm.
Nhưng cuối tuần nhìn lại.
Bạn khó trả lời câu hỏi:
"Tuần này mình đã tạo ra điều gì có ý nghĩa?"', 'Điều gì làm bạn cảm thấy công việc của mình đáng để tiếp tục?', 'Lần gần nhất bạn cảm thấy tự hào về công việc là khi nào?', 'Động lực bền vững thường đến từ ý nghĩa chứ không chỉ từ thành tích.', 'Ghi lại một khoảnh khắc bạn cảm thấy công việc của mình tạo ra giá trị.'),
  ('A1-04', 'Thành công của tôi có còn là điều tôi muốn?', 'A1', 'thich_nghi', 'Mục tiêu thay đổi',
   ARRAY['phân vân', 'hụt hẫng'], ARRAY['xem xét lại mục tiêu'], ARRAY[]::text[], NULL,
   'Bạn từng rất muốn đạt được vị trí hiện tại.
Bây giờ bạn đã có nó.
Nhưng cảm giác hào hứng lại không xuất hiện như mong đợi.', 'Có mục tiêu nào bạn đang theo đuổi chỉ vì từng muốn nó trong quá khứ?', 'Bạn đã thay đổi như thế nào trong vài năm gần đây?', 'Mục tiêu cũ không phải lúc nào cũng phù hợp với con người hiện tại.', 'Xem lại một mục tiêu nghề nghiệp bạn từng đặt ra cách đây 3 năm.'),
  ('A1-05', 'Tôi không biết điều gì thực sự quan trọng với mình', 'A1', 'thich_nghi', 'Thiếu ưu tiên nghề nghiệp',
   ARRAY['quá tải lựa chọn', 'bối rối'], ARRAY['trì hoãn quyết định'], ARRAY[]::text[], NULL,
   'Có quá nhiều lựa chọn.
Lương cao.
Công việc thú vị.
Cơ hội học hỏi.
Cân bằng cuộc sống.
Bạn muốn tất cả.
Và vì thế rất khó ra quyết định.', 'Nếu chỉ được giữ lại 3 điều quan trọng nhất trong công việc, đó sẽ là gì?', 'Điều gì bạn sẵn sàng đánh đổi và điều gì không?', 'Sự rõ ràng thường đến khi chúng ta biết điều gì là quan trọng nhất.', 'Xếp hạng 5 yếu tố nghề nghiệp quan trọng nhất với bạn.'),
  ('A1-06', 'Tôi đang phát triển hay chỉ đang bận?', 'A1', 'thich_nghi', 'Không chắc mình đang tiến bộ',
   ARRAY['sốt ruột', 'nghi ngờ'], ARRAY['học liên tục', 'so sánh bản thân'], ARRAY[]::text[], NULL,
   'Lịch làm việc của bạn kín hơn bao giờ hết.
Nhưng khi nhìn lại 6 tháng qua.
Bạn không chắc mình đang trưởng thành hay chỉ đang làm nhiều hơn.', 'Điều gì cho bạn thấy mình đang phát triển?', 'Bạn học được điều gì mới trong 90 ngày gần đây?', 'Khối lượng công việc không phải lúc nào cũng phản ánh sự phát triển.', 'Ghi lại 3 kỹ năng bạn đã cải thiện trong năm nay.'),
  ('A1-07', 'Tôi không còn thấy mình thuộc về nơi này', 'A1', 'thich_nghi', 'Mất kết nối với mục tiêu tổ chức',
   ARRAY['xa cách', 'mất ý nghĩa'], ARRAY['giảm tham gia', 'tìm cơ hội khác'], ARRAY[]::text[], NULL,
   'Ngày trước bạn hiểu vì sao công ty tồn tại.
Ngày trước bạn tin vào điều mình đang làm.
Bây giờ công việc vẫn vậy.
Nhưng cảm giác kết nối thì không còn.', 'Điều gì đã thay đổi?', 'Bạn còn thấy mình đang đóng góp vào điều gì lớn hơn không?', 'Con người thường rời bỏ ý nghĩa trước khi rời bỏ công việc.', 'Viết ra điều mà công việc hiện tại đang đóng góp cho người khác.'),
  ('A1-08', 'Tôi muốn nhiều hơn, nhưng không biết là gì', 'A1', 'thich_nghi', 'Khát vọng mơ hồ',
   ARRAY['bồn chồn', 'khao khát'], ARRAY['khám phá cơ hội mới'], ARRAY[]::text[], NULL,
   'Bạn cảm thấy mình có thể làm được nhiều hơn.
Nhưng không biết "nhiều hơn" cụ thể là gì.', 'Nếu không sợ thất bại, bạn sẽ thử điều gì?', 'Bạn đang thiếu điều gì nhất trong công việc hiện tại?', 'Nhiều người không thiếu năng lực.
Họ thiếu ngôn ngữ để mô tả điều mình thực sự muốn.', 'Hoàn thành câu:
"Tôi muốn công việc của mình mang lại nhiều ______ hơn."'),
  ('A1-09', 'Tôi đang sống theo định nghĩa thành công của ai?', 'A1', 'thich_nghi', 'Áp lực kỳ vọng',
   ARRAY['áp lực', 'mâu thuẫn nội tâm'], ARRAY['theo đuổi mục tiêu của người khác'], ARRAY[]::text[], NULL,
   'Bạn đạt được những thứ từng được gọi là thành công.
Nhưng đôi lúc vẫn cảm thấy trống rỗng.', 'Mục tiêu hiện tại là của bạn hay của người khác?', 'Bạn đang cố gắng chứng minh điều gì?', 'Không phải mọi thành công đều là thành công của chính mình.', 'Viết lại định nghĩa thành công cá nhân của bạn ở thời điểm hiện tại.'),
  ('A1-10', 'Nếu tiếp tục như thế này thêm 3 năm nữa thì sao?', 'A1', 'thich_nghi', 'Đánh giá hướng đi hiện tại',
   ARRAY['lo lắng', 'hy vọng'], ARRAY['suy nghĩ về tương lai', 'lập kế hoạch'], ARRAY[]::text[], NULL,
   'Hãy tưởng tượng không có thay đổi lớn nào xảy ra.
Bạn vẫn làm công việc hiện tại.
Vẫn ở môi trường hiện tại.
Vẫn theo cách hiện tại.', 'Viễn cảnh đó khiến bạn thấy hào hứng hay lo lắng?', 'Điều gì xuất hiện đầu tiên trong suy nghĩ của bạn?', 'Tương lai thường không được tạo ra trong một quyết định lớn.
Nó được tạo ra từ những lựa chọn lặp lại mỗi ngày.', 'Viết ra một thay đổi nhỏ bạn muốn thực hiện trong 30 ngày tới.
A2 – Execution Rhythm
Human Need
Adaptability
SCA Dimension
A2 – Execution Rhythm
Câu hỏi cốt lõi
Tôi có đang biến điều mình biết thành điều mình làm không?'),
  ('A2-01', 'Tôi biết phải làm gì nhưng vẫn chưa làm', 'A2', 'thich_nghi', 'Trì hoãn hành động',
   ARRAY['áy náy', 'chần chừ'], ARRAY['trì hoãn', 'né tránh'], ARRAY[]::text[], NULL,
   'Bạn đã suy nghĩ về việc này nhiều lần.
Bạn biết nó quan trọng.
Bạn biết mình nên bắt đầu.
Nhưng tuần này qua tuần khác.
Nó vẫn nằm trong danh sách dự định.', 'Điều gì đang ngăn bạn bắt đầu?', 'Bạn đang thiếu động lực, thời gian hay sự rõ ràng?', 'Đôi khi điều cản trở hành động không phải là khó khăn.
Mà là sự trì hoãn kéo dài.', 'Xác định bước nhỏ nhất bạn có thể làm trong 24 giờ tới.'),
  ('A2-02', 'Tôi có quá nhiều kế hoạch', 'A2', 'thich_nghi', 'Quá tải ưu tiên',
   ARRAY['rối rắm', 'quá tải'], ARRAY['chuyển đổi liên tục giữa các việc'], ARRAY[]::text[], NULL,
   'Danh sách việc cần làm ngày càng dài.
Ý tưởng ngày càng nhiều.
Nhưng tiến độ lại không tương xứng.', 'Bạn đang thiếu nguồn lực hay thiếu tập trung?', 'Điều gì thực sự quan trọng nhất lúc này?', 'Khi mọi thứ đều là ưu tiên, thực chất không có gì là ưu tiên.', 'Chọn một việc duy nhất quan trọng nhất tuần này.'),
  ('A2-03', 'Tôi bắt đầu rất tốt nhưng không duy trì được', 'A2', 'thich_nghi', 'Mất đà thực hiện',
   ARRAY['hụt hẫng', 'thất vọng'], ARRAY['bỏ dở thói quen'], ARRAY[]::text[], NULL,
   'Bạn từng rất quyết tâm.
Một tuần.
Hai tuần.
Rồi mọi thứ quay lại như cũ.', 'Điều gì khiến bạn dừng lại?', 'Bạn đang cố gắng quá sức hay thiếu hệ thống hỗ trợ?', 'Tiến bộ bền vững thường đến từ nhịp độ ổn định hơn là bùng nổ ngắn hạn.', 'Giảm mục tiêu hiện tại xuống mức bạn chắc chắn làm được.'),
  ('A2-04', 'Tôi luôn bận nhưng không hoàn thành điều quan trọng', 'A2', 'thich_nghi', 'Bận rộn nhưng kém hiệu quả',
   ARRAY['căng thẳng', 'bất lực'], ARRAY['chữa cháy', 'phản ứng'], ARRAY[]::text[], NULL,
   'Ngày nào cũng đầy lịch.
Việc nào cũng có lý do chính đáng.
Nhưng điều quan trọng nhất vẫn chưa tiến triển.', 'Điều gì đang chiếm thời gian của bạn?', 'Bạn đang phản ứng với công việc hay chủ động dẫn dắt nó?', 'Bận rộn không đồng nghĩa với tiến bộ.', 'Ghi lại 3 việc tiêu tốn nhiều thời gian nhất tuần qua.'),
  ('A2-05', 'Tôi liên tục thay đổi hướng đi', 'A2', 'thich_nghi', 'Thiếu nhất quán',
   ARRAY['hứng khởi ngắn hạn', 'phân tán'], ARRAY['đổi mục tiêu liên tục'], ARRAY[]::text[], NULL,
   'Bạn rất dễ hào hứng với điều mới.
Nhưng cũng nhanh chóng chuyển sang điều khác.', 'Bạn đang khám phá hay đang né tránh cam kết?', 'Điều gì khiến bạn khó kiên trì?', 'Không phải mọi ý tưởng mới đều cần được theo đuổi ngay lập tức.', 'Hoàn thành một việc dang dở trước khi bắt đầu việc mới.'),
  ('A2-06', 'Tôi chờ đến khi sẵn sàng', 'A2', 'thich_nghi', 'Chủ nghĩa hoàn hảo',
   ARRAY['lo lắng', 'sợ sai'], ARRAY['chuẩn bị quá mức'], ARRAY[]::text[], NULL,
   'Bạn muốn chuẩn bị kỹ hơn.
Học thêm chút nữa.
Chờ thời điểm phù hợp hơn.
Và rồi nhiều tháng trôi qua.', 'Điều gì khiến bạn chưa bắt đầu?', 'Bạn đang chuẩn bị hay đang trì hoãn?', 'Rất ít người cảm thấy hoàn toàn sẵn sàng trước khi bắt đầu điều mới.', 'Làm phiên bản đầu tiên thay vì phiên bản hoàn hảo.'),
  ('A2-07', 'Tôi có quá nhiều việc dang dở', 'A2', 'thich_nghi', 'Thiếu hoàn tất',
   ARRAY['tiếc nuối', 'mất động lực'], ARRAY['bỏ dở giữa chừng'], ARRAY[]::text[], NULL,
   'Có nhiều việc đã bắt đầu.
Nhưng ít việc thực sự hoàn thành.', 'Điều gì thường xảy ra ở giai đoạn giữa?', 'Bạn mất hứng thú hay gặp trở ngại?', 'Hoàn thành thường tạo ra nhiều giá trị hơn bắt đầu.', 'Chọn một việc đang dang dở và hoàn tất trong tuần này.'),
  ('A2-08', 'Tôi không thấy kết quả nên muốn bỏ cuộc', 'A2', 'thich_nghi', 'Thiếu kiên trì',
   ARRAY['nghi ngờ', 'nản chí'], ARRAY['bỏ cuộc sớm'], ARRAY[]::text[], NULL,
   'Bạn đã cố gắng.
Nhưng kết quả chưa xuất hiện.
Và bạn bắt đầu nghi ngờ.', 'Bạn đang đánh giá quá trình hay chỉ nhìn kết quả?', 'Điều gì đã thay đổi dù chưa có kết quả rõ ràng?', 'Nhiều thay đổi quan trọng diễn ra âm thầm trước khi có kết quả nhìn thấy được.', 'Ghi lại những tín hiệu tiến bộ nhỏ trong tuần này.'),
  ('A2-09', 'Tôi liên tục bị kéo khỏi điều quan trọng', 'A2', 'thich_nghi', 'Dễ bị phân tâm',
   ARRAY['xao nhãng', 'quá tải'], ARRAY['multitasking', 'đổi việc liên tục'], ARRAY[]::text[], NULL,
   'Bạn bắt đầu ngày với một kế hoạch rõ ràng.
Nhưng đến cuối ngày.
Bạn đã làm rất nhiều việc khác.', 'Điều gì thường làm bạn mất tập trung?', 'Những gián đoạn đó đến từ bên ngoài hay bên trong?', 'Khả năng tập trung là một trong những năng lực thực thi quan trọng nhất.', 'Dành 30 phút mỗi ngày cho việc quan trọng nhất.'),
  ('A2-10', 'Điều gì giúp tôi thực sự hành động?', 'A2', 'thich_nghi', 'Tìm hiểu động lực thực thi',
   ARRAY['tò mò', 'chủ động'], ARRAY['xây dựng thói quen', 'tối ưu cách làm việc'], ARRAY[]::text[], NULL,
   'Có những việc bạn làm rất đều đặn.
Có những việc mãi không bắt đầu.', 'Điều gì tạo ra khác biệt?', 'Bạn hành động tốt nhất khi có điều kiện nào?', 'Mỗi người có một nhịp thực thi riêng.
Hiểu được nhịp đó giúp tạo ra tiến bộ bền vững.', 'Quan sát thời điểm bạn làm việc hiệu quả nhất trong tuần này.'),
  ('A3-01', 'Chuyện này sao lại xảy ra lần nữa?', 'A3', 'thich_nghi', 'Lặp lại cùng một vấn đề',
   ARRAY['thất vọng', 'bất lực', 'bối rối'], ARRAY['phản ứng theo thói quen', 'lặp lại hành vi'], ARRAY[]::text[], NULL,
   'Đây không phải lần đầu.
Người khác.
Dự án khác.
Hoàn cảnh khác.
Nhưng cảm giác quen thuộc đến lạ.
Bạn lại thất vọng theo cách cũ.', 'Có điều gì đang lặp lại trong trải nghiệm công việc của bạn?', 'Bạn đã gặp tình huống tương tự bao nhiêu lần?', 'Khi một trải nghiệm liên tục quay lại, đôi khi nó đang cố dạy chúng ta điều gì đó.', 'Viết ra một vấn đề đã xuất hiện ít nhất 3 lần trong năm qua.'),
  ('A3-02', 'Tôi biết mình mệt nhưng không biết vì sao', 'A3', 'thich_nghi', 'Mệt mỏi không rõ nguyên nhân',
   ARRAY['kiệt sức', 'trống rỗng', 'mất năng lượng'], ARRAY['giảm động lực', 'thu mình'], ARRAY[]::text[], NULL,
   'Bạn ngủ đủ.
Công việc không quá tải.
Mọi thứ nhìn từ bên ngoài vẫn ổn.
Nhưng bạn vẫn thấy cạn năng lượng.', 'Điều gì đang lấy đi năng lượng của bạn?', 'Lần gần nhất bạn thực sự cảm thấy nhiều năng lượng là khi nào?', 'Kiệt sức không chỉ đến từ làm quá nhiều.
Đôi khi nó đến từ làm quá lâu những điều không còn tạo ý nghĩa.', 'Ghi lại điều làm bạn có năng lượng và điều làm bạn mất năng lượng trong tuần này.'),
  ('A3-03', 'Tôi phản ứng mạnh hơn mức cần thiết', 'A3', 'thich_nghi', 'Phản ứng cảm xúc quá mức',
   ARRAY['tức giận', 'tổn thương', 'khó chịu'], ARRAY['phản ứng bốc đồng'], ARRAY[]::text[], NULL,
   'Một góp ý nhỏ.
Một email ngắn.
Một cuộc họp bình thường.
Nhưng bạn mang cảm giác khó chịu đó suốt cả ngày.', 'Điều gì trong tình huống đó khiến bạn phản ứng mạnh?', 'Nó làm bạn nhớ tới trải nghiệm nào khác?', 'Đôi khi điều làm chúng ta đau không phải sự kiện hiện tại.
Mà là ý nghĩa chúng ta gắn cho nó.', 'Lần tới khi cảm xúc xuất hiện mạnh, hãy hỏi:
"Điều gì thực sự đang bị chạm tới?"'),
  ('A3-04', 'Tôi luôn bận nhưng không thấy tiến bộ', 'A3', 'thich_nghi', 'Không nhìn thấy sự phát triển',
   ARRAY['nghi ngờ', 'sốt ruột'], ARRAY['so sánh bản thân', 'làm nhiều hơn'], ARRAY[]::text[], NULL,
   'Bạn làm rất nhiều.
Nhưng khi nhìn lại 6 tháng qua.
Bạn không biết mình đã thay đổi điều gì.', 'Nếu phải kể một thay đổi tích cực của mình trong năm nay, bạn sẽ kể điều gì?', 'Bạn đang đo sự phát triển bằng điều gì?', 'Những điều không được ghi nhận thường rất khó được nhìn thấy.', 'Ghi lại 3 điều bạn làm tốt hơn so với 6 tháng trước.'),
  ('A3-05', 'Tôi cứ ra quyết định theo cảm xúc', 'A3', 'thich_nghi', 'Ra quyết định cảm tính',
   ARRAY['lo lắng', 'hưng phấn', 'dao động'], ARRAY['quyết định vội vàng'], ARRAY[]::text[], NULL,
   'Mỗi khi gặp áp lực.
Bạn muốn nghỉ việc.
Mỗi khi được khen.
Bạn thấy mọi thứ đều ổn.
Tâm trạng thay đổi.
Quyết định cũng thay đổi theo.', 'Bạn thường ra quyết định quan trọng trong trạng thái cảm xúc nào?', 'Những quyết định tốt nhất của bạn thường xuất hiện khi nào?', 'Cảm xúc là dữ liệu.
Nhưng không nên là người lái xe.', 'Trước quyết định lớn, hãy ghi lại điều bạn đang cảm thấy.'),
  ('A3-06', 'Tôi không còn nhớ mình đã học được gì', 'A3', 'thich_nghi', 'Trải nghiệm không được tích lũy',
   ARRAY['tiếc nuối', 'mơ hồ'], ARRAY['quên bài học', 'không ghi nhận'], ARRAY[]::text[], NULL,
   'Bạn đã tham gia nhiều dự án.
Giải quyết nhiều vấn đề.
Vượt qua nhiều thử thách.
Nhưng nếu ai đó hỏi:
"Bạn học được gì từ năm qua?"
Bạn khó trả lời.', 'Những bài học nào đang bị bạn bỏ quên?', 'Điều gì đáng được ghi lại hơn?', 'Trải nghiệm chỉ trở thành trí tuệ khi được nhìn lại.', 'Viết lại một bài học quan trọng từ tháng vừa qua.'),
  ('A3-07', 'Tôi cảm thấy bị mắc kẹt', 'A3', 'thich_nghi', 'Không biết bước tiếp theo',
   ARRAY['bế tắc', 'mất phương hướng'], ARRAY['trì hoãn', 'đứng yên'], ARRAY[]::text[], NULL,
   'Bạn không gặp khủng hoảng.
Nhưng cũng không thấy tiến lên.
Mọi thứ giống như đang đứng yên.', 'Bạn đang mắc kẹt ở đâu?', 'Điều gì khiến bạn chưa thể bước tiếp?', 'Cảm giác mắc kẹt thường xuất hiện trước khi có một thay đổi quan trọng.', 'Xác định một bước nhỏ bạn có thể thực hiện trong tuần này.'),
  ('A3-08', 'Tôi luôn nghĩ mình phải làm tốt hơn', 'A3', 'thich_nghi', 'Tự phê bình quá mức',
   ARRAY['tự trách', 'áp lực'], ARRAY['phủ nhận thành tựu'], ARRAY[]::text[], NULL,
   'Dù đạt kết quả tốt.
Bạn vẫn chỉ nhìn thấy điều chưa đủ tốt.', 'Bạn có đang đối xử với bản thân nghiêm khắc hơn người khác?', 'Nếu là đồng nghiệp của mình, bạn sẽ nói gì?', 'Sự phát triển cần phản hồi trung thực.
Không cần sự chỉ trích liên tục.', 'Ghi lại một điều bạn làm tốt hôm nay.'),
  ('A3-09', 'Tôi đang tránh nhìn vào điều gì?', 'A3', 'thich_nghi', 'Né tránh sự thật khó chịu',
   ARRAY['lo sợ', 'căng thẳng'], ARRAY['né tránh', 'trì hoãn'], ARRAY[]::text[], NULL,
   'Có một vấn đề bạn đã nhận ra từ lâu.
Nhưng bạn liên tục trì hoãn việc đối diện với nó.', 'Có điều gì bạn biết nhưng chưa muốn thừa nhận?', 'Điều gì khiến việc đó khó khăn?', 'Điều khó nhìn nhất thường là điều cần được nhìn thấy nhất.', 'Viết ra một sự thật bạn đang né tránh.'),
  ('A3-10', 'Nếu dừng lại 10 phút để nhìn lại thì sao?', 'A3', 'thich_nghi', 'Không có thời gian nhìn lại',
   ARRAY['quá tải', 'xao nhãng'], ARRAY['liên tục bận rộn'], ARRAY[]::text[], NULL,
   'Bạn luôn bận.
Luôn có việc tiếp theo.
Luôn có deadline tiếp theo.
Nhưng đã lâu rồi bạn không tự hỏi:
"Mình thực sự đang thế nào?"', 'Lần cuối bạn dành thời gian để nhìn lại bản thân là khi nào?', 'Điều gì xuất hiện nếu bạn dừng lại vài phút?', 'Không phải lúc nào chúng ta cũng cần làm nhiều hơn.
Đôi khi chúng ta cần quan sát nhiều hơn.', 'Dành 10 phút cuối ngày để trả lời:
"Hôm nay điều gì đáng nhớ nhất?"
A4 – Learning Loop
Human Need
Adaptability
SCA Dimension
A4 – Learning Loop
Câu hỏi cốt lõi
Tôi có đang biến trải nghiệm thành sự phát triển không?'),
  ('A4-01', 'Tôi cứ mắc lại cùng một lỗi', 'A4', 'thich_nghi', 'Lặp lại sai lầm cũ',
   ARRAY['tiếc nuối', 'thất vọng'], ARRAY['lặp lại hành vi'], ARRAY[]::text[], NULL,
   'Bạn nhận ra mình vừa gặp lại một vấn đề quen thuộc.
Điều đáng tiếc không phải là nó xảy ra.
Mà là bạn đã từng hứa sẽ không để điều đó lặp lại.', 'Có bài học nào bạn đã nhìn thấy nhưng chưa thực sự áp dụng?', 'Điều gì khiến nó tiếp tục lặp lại?', 'Biết một bài học không đồng nghĩa với việc đã học được nó.', 'Viết ra một hành động cụ thể để tránh lặp lại tình huống này.'),
  ('A4-02', 'Tôi đã vượt qua chuyện đó như thế nào?', 'A4', 'thich_nghi', 'Nhìn lại thành công',
   ARRAY['tự hào', 'biết ơn'], ARRAY['củng cố hành vi tích cực'], ARRAY[]::text[], NULL,
   'Có một vấn đề từng khiến bạn rất áp lực.
Nhưng hôm nay nó không còn ảnh hưởng như trước.', 'Bạn đã thay đổi điều gì để vượt qua nó?', 'Điều gì giúp bạn trưởng thành hơn?', 'Những điều từng rất khó thường chứa nhiều bài học nhất.', 'Viết lại một điều bạn từng làm được mà trước đây nghĩ là không thể.'),
  ('A4-03', 'Tôi học được gì từ thất bại này?', 'A4', 'thich_nghi', 'Thất bại trong công việc',
   ARRAY['buồn bã', 'thất vọng'], ARRAY['điều chỉnh cách làm'], ARRAY[]::text[], NULL,
   'Mọi chuyện không diễn ra như mong đợi.
Bạn có thể tự trách mình.
Hoặc có thể học từ nó.', 'Nếu thất bại này là một người thầy, nó đang dạy bạn điều gì?', 'Điều gì bạn sẽ làm khác đi lần sau?', 'Thất bại chỉ thực sự vô nghĩa khi chúng ta không học được gì từ nó.', 'Viết ra 3 bài học từ trải nghiệm này.'),
  ('A4-04', 'Tôi đang phát triển theo cách nào?', 'A4', 'thich_nghi', 'Không nhận ra sự tiến bộ',
   ARRAY['nghi ngờ', 'thiếu tự tin'], ARRAY['so sánh bản thân'], ARRAY[]::text[], NULL,
   'Chúng ta thường nhìn vào điều chưa có.
Và quên nhìn vào điều đã thay đổi.', 'Bạn giỏi hơn chính mình của 1 năm trước ở điểm nào?', 'Những kỹ năng hoặc góc nhìn nào đã thay đổi?', 'Tiến bộ thường diễn ra chậm đến mức khó nhận thấy.', 'Liệt kê 5 điều bạn làm tốt hơn trước đây.'),
  ('A4-05', 'Tôi đã bỏ lỡ tín hiệu nào?', 'A4', 'thich_nghi', 'Sự việc diễn ra không như mong đợi',
   ARRAY['tiếc nuối', 'cảnh giác'], ARRAY['quan sát nhiều hơn'], ARRAY[]::text[], NULL,
   'Khi nhìn lại.
Bạn nhận ra đã có những dấu hiệu từ rất sớm.
Nhưng lúc đó bạn không chú ý.', 'Những tín hiệu nào bạn đã bỏ qua?', 'Nếu gặp lại tình huống tương tự, bạn sẽ quan sát điều gì?', 'Kinh nghiệm giúp chúng ta nhìn thấy những điều trước đây mình bỏ lỡ.', 'Ghi lại các dấu hiệu cảnh báo sớm bạn muốn nhớ.'),
  ('A4-06', 'Tôi đang học hay chỉ đang trải nghiệm?', 'A4', 'thich_nghi', 'Trải nghiệm nhiều nhưng ít thay đổi',
   ARRAY['mơ hồ', 'hụt hẫng'], ARRAY['tham gia nhưng ít tổng kết'], ARRAY[]::text[], NULL,
   'Bạn tham gia nhiều dự án.
Nhiều khóa học.
Nhiều cơ hội.
Nhưng cảm giác phát triển không tương xứng.', 'Bạn đang tích lũy trải nghiệm hay đang tích lũy bài học?', 'Điều gì đã thay đổi trong cách bạn làm việc?', 'Trải nghiệm chỉ tạo ra giá trị khi được chuyển hóa thành nhận thức hoặc hành động.', 'Chọn một trải nghiệm gần đây và viết ra điều bạn học được.'),
  ('A4-07', 'Tôi có đang lặp lại điều hiệu quả?', 'A4', 'thich_nghi', 'Không duy trì được thành công',
   ARRAY['tiếc nuối', 'hoài niệm'], ARRAY['mất thói quen tốt'], ARRAY[]::text[], NULL,
   'Bạn từng có một giai đoạn làm việc rất tốt.
Nhiều năng lượng.
Nhiều tiến bộ.
Nhưng rồi mọi thứ biến mất.', 'Điều gì đã giúp bạn thành công lúc đó?', 'Bạn còn duy trì những điều đó không?', 'Học hỏi không chỉ là tránh sai lầm.
Mà còn là lặp lại những gì hiệu quả.', 'Viết ra 3 điều bạn muốn tái tạo từ giai đoạn tốt nhất của mình.'),
  ('A4-08', 'Điều này đang dạy tôi điều gì về bản thân?', 'A4', 'thich_nghi', 'Tìm ý nghĩa từ trải nghiệm',
   ARRAY['tò mò', 'khám phá'], ARRAY['tự quan sát'], ARRAY[]::text[], NULL,
   'Một sự kiện vừa xảy ra.
Tốt hoặc xấu.
Nhưng điều đáng quan tâm hơn là:
Nó đang cho bạn biết điều gì về chính mình?', 'Bạn hiểu thêm điều gì về bản thân sau trải nghiệm này?', 'Điều gì làm bạn bất ngờ nhất?', 'Mỗi trải nghiệm đều là một tấm gương.', 'Viết một điều mới bạn vừa khám phá về bản thân.'),
  ('A4-09', 'Tôi đã thay đổi quyết định như thế nào?', 'A4', 'thich_nghi', 'Ra quyết định tốt hơn theo thời gian',
   ARRAY['tự tin', 'trưởng thành'], ARRAY['ra quyết định có chủ đích'], ARRAY[]::text[], NULL,
   'Có những quyết định bạn sẽ không còn đưa ra giống như vài năm trước.', 'Điều gì đã thay đổi trong cách bạn suy nghĩ?', 'Kinh nghiệm nào ảnh hưởng mạnh nhất đến điều đó?', 'Trưởng thành thường thể hiện qua cách chúng ta ra quyết định.', 'So sánh cách bạn xử lý một vấn đề hiện tại với 3 năm trước.'),
  ('A4-10', 'Nếu nhìn lại năm nay như một chương sách', 'A4', 'thich_nghi', 'Tổng kết hành trình phát triển',
   ARRAY['biết ơn', 'chiêm nghiệm'], ARRAY['tổng kết', 'lập kế hoạch'], ARRAY[]::text[], NULL,
   'Hãy tưởng tượng năm nay là một chương trong cuốn sách nghề nghiệp của bạn.', 'Tên chương đó sẽ là gì?', 'Bài học lớn nhất của chương này là gì?', 'Sự phát triển không nằm ở số năm làm việc.
Mà nằm ở số bài học được tích lũy từ những năm đó.', 'Viết tiêu đề và bài học lớn nhất của năm nay.'),
  ('C1-01', 'Tôi lại phải làm thay', 'C1', 'ket_noi', 'Đồng nghiệp không hoàn thành phần việc',
   ARRAY['thất vọng', 'bực bội'], ARRAY['làm thay', 'kiểm soát'], ARRAY[]::text[], NULL,
   'Bạn đã giao việc.
Đã thống nhất deadline.
Đã kiểm tra tiến độ.
Nhưng đến phút cuối.
Bạn vẫn phải nhảy vào xử lý.', 'Điều gì khiến bạn cảm thấy khó tin tưởng trong tình huống này?', 'Đây là trường hợp cá biệt hay một trải nghiệm lặp lại?', 'Niềm tin không mất đi trong một lần thất hứa.
Nó mất đi khi điều đó trở thành thói quen.', 'Ghi lại một tình huống bạn cảm thấy mình phải "gánh thay" người khác.'),
  ('C1-02', 'Tôi luôn phải kiểm tra lại', 'C1', 'ket_noi', 'Không yên tâm giao việc',
   ARRAY['lo lắng', 'căng thẳng'], ARRAY['micromanage', 'kiểm tra liên tục'], ARRAY[]::text[], NULL,
   'Bạn giao việc.
Nhưng vẫn liên tục theo dõi.
Liên tục nhắc nhở.
Liên tục kiểm tra.', 'Điều gì khiến bạn khó buông quyền kiểm soát?', 'Bạn đang thiếu niềm tin hay đang thiếu thông tin?', 'Không phải mọi sự kiểm soát đều xuất phát từ trách nhiệm.
Đôi khi nó xuất phát từ sự thiếu tin tưởng.', 'Xác định một việc bạn có thể trao quyền nhiều hơn trong tuần này.'),
  ('C1-03', 'Người ta nói một đằng làm một nẻo', 'C1', 'ket_noi', 'Lời nói và hành động không nhất quán',
   ARRAY['hoài nghi', 'mất niềm tin'], ARRAY['giảm hợp tác'], ARRAY[]::text[], NULL,
   'Trong cuộc họp.
Mọi người đều đồng ý.
Sau cuộc họp.
Mọi thứ diễn ra theo cách hoàn toàn khác.', 'Bạn phản ứng thế nào khi lời nói và hành động không khớp nhau?', 'Điều đó ảnh hưởng gì đến cách bạn hợp tác?', 'Trust được xây bằng sự nhất quán, không phải bằng lời hứa.', 'Quan sát một người mà bạn cảm thấy đáng tin và ghi lại điều họ làm khác biệt.'),
  ('C1-04', 'Tôi không biết có thể nhờ ai', 'C1', 'ket_noi', 'Thiếu người hỗ trợ',
   ARRAY['cô đơn', 'bất an'], ARRAY['tự xoay sở'], ARRAY[]::text[], NULL,
   'Bạn gặp một vấn đề khó.
Nhưng không biết ai là người có thể giúp.
Hoặc không chắc ai sẽ sẵn lòng giúp.', 'Bạn có cảm thấy mình đang đơn độc trong công việc không?', 'Ai là người bạn có thể tìm đến khi gặp khó khăn?', 'Trust không chỉ là tin người khác làm việc.
Trust còn là tin rằng mình sẽ không phải đối mặt một mình.', 'Liệt kê 3 người bạn có thể tìm đến khi cần hỗ trợ.'),
  ('C1-05', 'Tôi giữ lại vì sợ bị thất vọng', 'C1', 'ket_noi', 'Không muốn kỳ vọng vào người khác',
   ARRAY['phòng vệ', 'thất vọng'], ARRAY['ôm việc', 'làm một mình'], ARRAY[]::text[], NULL,
   'Bạn chọn tự làm.
Không phải vì nhanh hơn.
Mà vì không muốn thất vọng thêm một lần nữa.', 'Bạn đang bảo vệ hiệu quả công việc hay đang bảo vệ cảm xúc của mình?', 'Điều gì khiến bạn ngừng kỳ vọng vào người khác?', 'Đôi khi sự thiếu tin tưởng khiến chúng ta cô lập chính mình.', 'Xác định một việc nhỏ bạn có thể chia sẻ với người khác.'),
  ('C1-06', 'Tôi không chắc cấp trên có giữ lời', 'C1', 'ket_noi', 'Mất niềm tin vào lãnh đạo',
   ARRAY['hoài nghi', 'mất động lực'], ARRAY['giảm cam kết'], ARRAY[]::text[], NULL,
   'Những cam kết đã được đưa ra.
Nhưng rồi không xảy ra.
Một lần.
Rồi nhiều lần.', 'Điều gì làm bạn mất niềm tin nhất?', 'Bạn còn tin những cam kết đó không?', 'Trust trong tổ chức thường được xây hoặc mất từ những điều rất nhỏ.', 'Ghi lại một cam kết đã được thực hiện đúng và một cam kết chưa được thực hiện.'),
  ('C1-07', 'Tôi ngại nhờ giúp đỡ', 'C1', 'ket_noi', 'Không tin người khác sẽ hỗ trợ',
   ARRAY['ngần ngại', 'cô lập'], ARRAY['tự làm mọi việc'], ARRAY[]::text[], NULL,
   'Bạn đang quá tải.
Nhưng vẫn chọn tự xoay sở.
Không phải vì không cần giúp đỡ.
Mà vì không tin việc nhờ giúp sẽ có ích.', 'Điều gì khiến bạn ngần ngại tìm kiếm hỗ trợ?', 'Lần gần nhất bạn nhận được sự giúp đỡ hữu ích là khi nào?', 'Trust không chỉ thể hiện qua việc cho đi.
Nó còn thể hiện qua khả năng nhận hỗ trợ.', 'Nhờ một người hỗ trợ bạn trong một việc cụ thể tuần này.'),
  ('C1-08', 'Tôi không biết người khác đang nghĩ gì', 'C1', 'ket_noi', 'Thiếu minh bạch',
   ARRAY['nghi ngờ', 'bất an'], ARRAY['suy diễn', 'giữ khoảng cách'], ARRAY[]::text[], NULL,
   'Không ai nói gì.
Mọi thứ vẫn diễn ra bình thường.
Nhưng bạn luôn cảm thấy mình đang bỏ lỡ điều gì đó.', 'Bạn có đủ thông tin để cảm thấy an tâm không?', 'Điều gì đang khiến bạn nghi ngờ?', 'Trust phát triển tốt nhất trong môi trường có sự minh bạch.', 'Xác định một thông tin bạn cần để làm việc hiệu quả hơn.'),
  ('C1-09', 'Tôi từng tin, nhưng giờ không còn nữa', 'C1', 'ket_noi', 'Niềm tin bị tổn thương',
   ARRAY['tổn thương', 'thất vọng'], ARRAY['phòng thủ'], ARRAY[]::text[], NULL,
   'Có thời điểm bạn rất tin tưởng ai đó.
Nhưng một trải nghiệm nào đó đã thay đổi điều đó.', 'Điều gì khiến niềm tin đó thay đổi?', 'Bạn đang mất niềm tin vào một người hay vào một kiểu trải nghiệm?', 'Một trải nghiệm tiêu cực có thể ảnh hưởng đến cách chúng ta nhìn nhiều mối quan hệ khác.', 'Phân biệt giữa con người cụ thể và trải nghiệm cụ thể.'),
  ('C1-10', 'Tôi cảm thấy an tâm khi làm việc cùng họ', 'C1', 'ket_noi', 'Trải nghiệm tin cậy tích cực',
   ARRAY['an tâm', 'tin tưởng'], ARRAY['hợp tác', 'trao quyền'], ARRAY[]::text[], NULL,
   'Có những người mà chỉ cần biết họ tham gia.
Bạn đã thấy nhẹ nhõm hơn.
Không phải vì họ hoàn hảo.
Mà vì bạn biết họ sẽ làm điều họ nói.', 'Ai là người khiến bạn cảm thấy yên tâm nhất khi làm việc cùng?', 'Điều gì tạo nên cảm giác đó?', 'Trust không phải là một cảm giác mơ hồ.
Nó được xây từ những hành vi rất cụ thể và lặp lại.', 'Ghi lại 3 hành vi khiến bạn cảm thấy tin tưởng một người.'),
  ('C2-01', 'Ý tưởng của bạn biến mất trong cuộc họp', 'C2', 'ket_noi', 'Không được lắng nghe',
   ARRAY['thất vọng', 'hụt hẫng', 'bất lực'], ARRAY['im lặng', 'rút lui', 'né phát biểu'], ARRAY[]::text[], NULL,
   'Bạn đã chuẩn bị khá kỹ.
Khi cuộc họp bắt đầu, bạn chia sẻ ý tưởng của mình.
Không ai phản hồi.
Cuộc trò chuyện tiếp tục như thể điều đó chưa từng được nói ra.
Mười phút sau, một người khác nhắc lại ý tưởng tương tự.
Lần này mọi người hào hứng.', 'Tình huống này quen thuộc với bạn đến đâu?', 'Lần gần nhất bạn cảm thấy tiếng nói của mình không được nhìn thấy là khi nào?', 'Đôi khi điều khiến chúng ta im lặng không phải vì thiếu ý tưởng.
Mà vì nhiều lần lên tiếng nhưng không tạo ra khác biệt.', 'Tuần này hãy ghi lại một lần bạn muốn lên tiếng nhưng đã chọn im lặng.'),
  ('C2-02', 'Cuộc họp kết thúc nhưng điều quan trọng nhất vẫn chưa được nói ra', 'C2', 'ket_noi', 'Không dám lên tiếng',
   ARRAY['lo lắng', 'dè chừng', 'bất an'], ARRAY['giữ ý kiến', 'né phản biện'], ARRAY[]::text[], NULL,
   'Bạn nhận ra có một rủi ro lớn trong kế hoạch.
Bạn đã nghĩ đến việc nói ra.
Rồi lại tự nhủ:
"Chắc mọi người cũng biết rồi."
"Chắc mình đang nghĩ quá."
Cuộc họp kết thúc.
Không ai nhắc đến vấn đề đó.', 'Bạn đã bao nhiêu lần giữ lại điều mình thực sự muốn nói?', 'Điều gì thường khiến bạn ngần ngại lên tiếng?', 'Nhiều tổ chức không thiếu ý tưởng.
Họ thiếu những người cảm thấy đủ an toàn để nói ra điều mình thấy.', 'Viết ra một điều bạn đang giữ lại nhưng nghĩ rằng đội ngũ nên biết.'),
  ('C2-03', 'Bạn đồng ý dù trong lòng không đồng ý', 'C2', 'ket_noi', 'Ngại phản biện',
   ARRAY['căng thẳng', 'lo mất lòng'], ARRAY['đồng ý cho xong', 'né tranh luận'], ARRAY[]::text[], NULL,
   'Bạn biết phương án được chọn chưa phải lựa chọn tốt nhất.
Nhưng mọi người đều đồng ý.
Bạn không muốn trở thành người duy nhất phản đối.
Bạn gật đầu.
Cuộc họp tiếp tục.', 'Bạn có thường đồng ý chỉ để tránh tranh luận không?', 'Điều gì khiến bạn khó nói ra quan điểm khác biệt?', 'Sự đồng thuận không phải lúc nào cũng là dấu hiệu của sự đồng lòng.
Đôi khi nó chỉ là dấu hiệu của sự im lặng tập thể.', 'Lần tới khi có ý kiến khác, hãy thử đặt một câu hỏi thay vì phản đối trực tiếp.'),
  ('C2-04', 'Bạn bị ngắt lời giữa chừng', 'C2', 'ket_noi', 'Tiếng nói bị xem nhẹ',
   ARRAY['khó chịu', 'tổn thương'], ARRAY['giảm tham gia', 'thu mình'], ARRAY[]::text[], NULL,
   'Bạn đang trình bày.
Một người khác cắt ngang.
Cuộc trò chuyện chuyển hướng.
Không ai quay lại phần bạn đang nói.
Bạn dừng lại.', 'Điều đó khiến bạn cảm thấy thế nào?', 'Sau những trải nghiệm như vậy, bạn có thay đổi cách tham gia cuộc họp không?', 'Một vài trải nghiệm nhỏ lặp đi lặp lại có thể làm giảm sự tham gia nhiều hơn chúng ta nghĩ.', 'Quan sát xem tuần này có ai bị ngắt lời trong cuộc họp hay không.'),
  ('C2-05', 'Bạn muốn góp ý nhưng sợ làm mất lòng', 'C2', 'ket_noi', 'Ngại phản hồi người khác',
   ARRAY['lo lắng', 'do dự'], ARRAY['giữ lại phản hồi'], ARRAY[]::text[], NULL,
   'Bạn thấy một đồng nghiệp đang gặp khó khăn.
Bạn biết một góp ý nhỏ có thể giúp họ cải thiện.
Nhưng bạn lo rằng họ sẽ hiểu sai ý mình.
Cuối cùng bạn không nói gì.', 'Bạn có thường giữ lại góp ý vì sợ ảnh hưởng mối quan hệ không?', 'Bạn học được điều gì về phản hồi từ môi trường làm việc trước đây?', 'Nhiều người không né phản hồi vì thiếu quan tâm.
Họ né vì quá quan tâm đến mối quan hệ.', 'Hãy thử đưa ra một phản hồi tích cực và cụ thể trong tuần này.'),
  ('C2-06', 'Bạn nhận lỗi thay vì giải thích', 'C2', 'ket_noi', 'Sợ bị đánh giá',
   ARRAY['xấu hổ', 'lo sợ'], ARRAY['nhận lỗi', 'né giải thích'], ARRAY[]::text[], NULL,
   'Một vấn đề xảy ra.
Có nhiều nguyên nhân.
Nhưng bạn cảm thấy việc giải thích sẽ chỉ khiến mọi thứ phức tạp hơn.
Bạn nhận lỗi.
Rồi kết thúc câu chuyện thật nhanh.', 'Bạn có thường chọn im lặng để tránh bị đánh giá không?', 'Bạn sợ điều gì nhất khi mắc lỗi?', 'Khi con người sợ bị phán xét, họ thường chọn bảo vệ hình ảnh hơn là chia sẻ sự thật.', 'Ghi lại lần gần nhất bạn mắc lỗi và điều bạn đã học được từ nó.'),
  ('C2-07', 'Bạn có câu hỏi nhưng không hỏi', 'C2', 'ket_noi', 'Ngại đặt câu hỏi',
   ARRAY['ngại ngùng', 'thiếu tự tin'], ARRAY['giả vờ hiểu', 'không hỏi'], ARRAY[]::text[], NULL,
   'Mọi người dường như đều hiểu.
Chỉ có bạn cảm thấy chưa rõ.
Bạn muốn hỏi.
Nhưng lại sợ câu hỏi của mình quá đơn giản.
Bạn im lặng.', 'Bạn có thường giả vờ đã hiểu để tránh cảm giác ngại ngùng không?', 'Điều gì khiến bạn khó đặt câu hỏi?', 'Những câu hỏi không được hỏi thường tạo ra những sai lầm tốn kém hơn nhiều.', 'Tuần này hãy chủ động hỏi một điều bạn thực sự chưa hiểu.'),
  ('C2-08', 'Bạn được mời góp ý nhưng không tin rằng điều đó tạo ra thay đổi', 'C2', 'ket_noi', 'Tiếng nói không tạo ảnh hưởng',
   ARRAY['thất vọng', 'hoài nghi'], ARRAY['bỏ qua khảo sát', 'không tham gia'], ARRAY[]::text[], NULL,
   'Khảo sát.
Workshop.
Townhall.
Mọi người được mời chia sẻ ý kiến.
Bạn từng tham gia.
Nhưng chưa thấy điều gì thay đổi.
Lần này bạn bỏ qua.', 'Bạn còn tin rằng tiếng nói của mình có thể tạo ra khác biệt không?', 'Điều gì khiến niềm tin đó giảm đi?', 'Người ta không ngừng lên tiếng vì thiếu ý kiến.
Họ ngừng lên tiếng vì thiếu bằng chứng rằng ý kiến của mình có giá trị.', 'Viết ra một thay đổi nhỏ mà bạn mong muốn nhất trong môi trường làm việc của mình.'),
  ('C2-09', 'Bạn luôn là người cuối cùng phát biểu', 'C2', 'ket_noi', 'Tự kiểm duyệt bản thân',
   ARRAY['lo lắng', 'dè dặt'], ARRAY['chờ người khác phát biểu'], ARRAY[]::text[], NULL,
   'Bạn có ý kiến.
Nhưng luôn chờ người khác nói trước.
Bạn muốn chắc rằng ý tưởng của mình không quá khác biệt.
Đôi khi cuộc họp kết thúc trước khi tới lượt bạn.', 'Bạn thường phát biểu để đóng góp hay để tránh sai?', 'Điều gì xảy ra nếu bạn là người nói đầu tiên?', 'Sự tự tin không phải lúc nào cũng đến trước hành động.
Đôi khi nó xuất hiện sau nhiều lần dám thử.', 'Trong cuộc họp tiếp theo, hãy thử phát biểu sớm hơn bình thường.'),
  ('C2-10', 'Bạn đã từng rất tích cực, nhưng bây giờ không còn nữa', 'C2', 'ket_noi', 'Rút lui khỏi sự tham gia',
   ARRAY['mất động lực', 'thờ ơ'], ARRAY['ít đóng góp', 'ít chia sẻ'], ARRAY[]::text[], NULL,
   'Ngày đầu tiên vào công ty.
Bạn đầy ý tưởng.
Bạn muốn đóng góp.
Bạn muốn thay đổi điều gì đó.
Bây giờ bạn vẫn làm việc chăm chỉ.
Nhưng không còn nhiệt tình tham gia như trước.', 'Điều gì đã thay đổi?', 'Bạn bắt đầu rút lui từ thời điểm nào?', 'Sự tham gia không mất đi trong một ngày.
Nó giảm dần sau nhiều lần cảm thấy tiếng nói của mình không còn ý nghĩa.', 'Nhớ lại một thời điểm bạn từng rất chủ động. Khi đó điều gì khác so với hiện tại?'),
  ('C3-01', 'Tôi biết có vấn đề nhưng không muốn nói', 'C3', 'ket_noi', 'Né tránh cuộc trò chuyện khó',
   ARRAY['lo lắng', 'e ngại'], ARRAY['im lặng', 'né tránh'], ARRAY[]::text[], NULL,
   'Có một vấn đề đang tồn tại.
Bạn nhìn thấy nó.
Nhưng bạn quyết định im lặng.
Không phải vì không quan tâm.
Mà vì không biết nói thế nào.', 'Có điều gì bạn đang tránh nhắc tới không?', 'Điều gì khiến cuộc trò chuyện đó trở nên khó khăn?', 'Điều không được nói ra thường không tự biến mất.', 'Viết xuống điều bạn muốn nói nhưng chưa từng nói.'),
  ('C3-02', 'Mỗi lần góp ý đều trở thành tranh cãi', 'C3', 'ket_noi', 'Đối thoại phòng thủ',
   ARRAY['bực bội', 'thất vọng'], ARRAY['phản bác', 'tự vệ'], ARRAY[]::text[], NULL,
   'Bạn muốn góp ý.
Nhưng người đối diện lập tức giải thích hoặc phản bác.', 'Điều gì thường xảy ra khi bạn đưa ra phản hồi?', 'Bạn đang cố chứng minh hay đang cố hiểu nhau?', 'Một cuộc đối thoại tốt bắt đầu bằng sự tò mò, không phải sự đúng sai.', 'Trong cuộc trò chuyện tiếp theo, thử hỏi thêm một câu trước khi đưa ra ý kiến.'),
  ('C3-03', 'Chúng tôi chỉ nói về công việc, không nói về vấn đề', 'C3', 'ket_noi', 'Trao đổi bề mặt',
   ARRAY['xa cách', 'dè dặt'], ARRAY['tránh chủ đề nhạy cảm'], ARRAY[]::text[], NULL,
   'Cuộc họp diễn ra đều đặn.
Công việc vẫn được cập nhật.
Nhưng những điều thực sự quan trọng lại không xuất hiện.', 'Có chủ đề nào mọi người luôn tránh nhắc đến không?', 'Điều gì khiến chủ đề đó trở nên nhạy cảm?', 'Không phải mọi cuộc trao đổi đều tạo ra sự hiểu nhau.', 'Xác định một chủ đề quan trọng nhưng ít được nhắc tới.'),
  ('C3-04', 'Tôi không cảm thấy mình được hiểu', 'C3', 'ket_noi', 'Thiếu lắng nghe',
   ARRAY['cô đơn', 'không được thấu hiểu'], ARRAY['ngắt lời', 'phản ứng vội'], ARRAY[]::text[], NULL,
   'Bạn đã cố giải thích.
Nhưng cảm giác như người khác chỉ chờ để phản hồi.', 'Lần gần nhất bạn cảm thấy được lắng nghe là khi nào?', 'Điều gì tạo ra cảm giác đó?', 'Được lắng nghe thường quan trọng hơn được đồng ý.', 'Quan sát một cuộc trò chuyện và đếm số lần bạn thực sự lắng nghe.'),
  ('C3-05', 'Chúng tôi luôn hiểu khác nhau về cùng một việc', 'C3', 'ket_noi', 'Hiểu lầm kéo dài',
   ARRAY['bối rối', 'khó chịu'], ARRAY['diễn giải khác nhau'], ARRAY[]::text[], NULL,
   'Sau cuộc họp.
Mỗi người lại hiểu một kiểu.', 'Bạn có thường xuyên phải làm rõ lại những gì đã thống nhất không?', 'Điều gì đang bị bỏ sót trong quá trình trao đổi?', 'Đối thoại không chỉ là nói.
Mà còn là tạo ra cùng một sự hiểu biết.', 'Sau cuộc trao đổi quan trọng, thử tóm tắt lại điều bạn hiểu.'),
  ('C3-06', 'Tôi sợ làm người khác khó chịu', 'C3', 'ket_noi', 'Ngại phản hồi thẳng thắn',
   ARRAY['sợ mất lòng', 'lo lắng'], ARRAY['giữ ý kiến cho riêng mình'], ARRAY[]::text[], NULL,
   'Bạn nhận ra một vấn đề.
Nhưng không muốn nói vì sợ ảnh hưởng mối quan hệ.', 'Bạn thường giữ lại điều gì khi giao tiếp?', 'Điều gì bạn đang cố bảo vệ?', 'Sự tử tế không đồng nghĩa với việc tránh sự thật.', 'Chọn một phản hồi nhỏ nhưng chân thành để chia sẻ.'),
  ('C3-07', 'Cuộc họp kết thúc nhưng vấn đề vẫn còn', 'C3', 'ket_noi', 'Đối thoại không dẫn tới chuyển động',
   ARRAY['hụt hẫng', 'hoài nghi'], ARRAY['họp nhiều', 'thay đổi ít'], ARRAY[]::text[], NULL,
   'Mọi người đã trao đổi rất nhiều.
Nhưng sau đó không có gì thay đổi.', 'Bạn có cảm thấy các cuộc trao đổi dẫn đến hành động không?', 'Điều gì đang bị thiếu?', 'Đối thoại tốt tạo ra hiểu biết.
Đối thoại xuất sắc tạo ra chuyển động.', 'Xác định hành động cụ thể tiếp theo sau một cuộc trao đổi.'),
  ('C3-08', 'Tôi luôn phải đoán ý người khác', 'C3', 'ket_noi', 'Giao tiếp gián tiếp',
   ARRAY['mơ hồ', 'bất an'], ARRAY['nói vòng', 'đoán ý'], ARRAY[]::text[], NULL,
   'Không ai nói thẳng.
Mọi người dùng những câu rất an toàn.', 'Bạn có thường phải suy đoán điều người khác thực sự muốn nói không?', 'Điều đó ảnh hưởng thế nào tới công việc?', 'Sự rõ ràng giúp tiết kiệm rất nhiều năng lượng cảm xúc.', 'Thử diễn đạt nhu cầu của mình rõ ràng hơn một chút.'),
  ('C3-09', 'Chúng tôi nói chuyện nhưng không kết nối', 'C3', 'ket_noi', 'Thiếu đối thoại thực chất',
   ARRAY['xa cách', 'trống rỗng'], ARRAY['giao tiếp xã giao'], ARRAY[]::text[], NULL,
   'Mọi người giao tiếp thường xuyên.
Nhưng vẫn cảm thấy xa cách.', 'Điều gì còn thiếu trong các cuộc trao đổi hiện tại?', 'Bạn có thực sự biết người đối diện đang nghĩ gì không?', 'Tần suất giao tiếp không đồng nghĩa với chất lượng giao tiếp.', 'Đặt một câu hỏi sâu hơn trong cuộc trò chuyện tiếp theo.'),
  ('C3-10', 'Cuộc trò chuyện nào đang cần diễn ra?', 'C3', 'ket_noi', 'Đối thoại bị trì hoãn',
   ARRAY['căng thẳng', 'ngập ngừng'], ARRAY['trì hoãn đối thoại'], ARRAY[]::text[], NULL,
   'Có những cuộc trò chuyện mà bạn biết mình cần có.
Nhưng vẫn chưa bắt đầu.', 'Cuộc trò chuyện nào bạn đang trì hoãn?', 'Điều gì khiến bạn chưa sẵn sàng?', 'Nhiều bước ngoặt quan trọng bắt đầu từ một cuộc đối thoại can đảm.', 'Viết ra câu mở đầu cho cuộc trò chuyện đó.'),
  ('S1-01', 'Tôi không biết thế nào mới là làm tốt', 'S1', 'ro_rang', 'Kỳ vọng không rõ ràng',
   ARRAY['mơ hồ', 'lo lắng', 'thiếu tự tin'], ARRAY['hỏi lại', 'đoán ý'], ARRAY[]::text[], NULL,
   'Bạn cố gắng hoàn thành công việc.
Nhưng luôn có cảm giác:
"Mình có đang làm đúng điều người khác mong đợi không?"', 'Bạn có biết thế nào là một kết quả tốt trong công việc hiện tại không?', 'Ai là người định nghĩa thành công cho vai trò của bạn?', 'Khi kỳ vọng không rõ ràng, rất khó để cảm thấy tự tin.', 'Viết ra 3 kết quả quan trọng nhất mà vai trò của bạn cần tạo ra.'),
  ('S1-02', 'Việc gì cũng đến tay tôi', 'S1', 'ro_rang', 'Ranh giới vai trò mơ hồ',
   ARRAY['quá tải', 'bực bội'], ARRAY['ôm việc', 'làm thay'], ARRAY[]::text[], NULL,
   'Bạn thường xuyên nhận thêm việc.
Không phải vì đó là trách nhiệm của mình.
Mà vì không ai rõ ai sẽ làm.', 'Bạn có đang gánh những việc đáng lẽ thuộc về người khác?', 'Điều gì khiến việc đó tiếp tục xảy ra?', 'Sự mơ hồ về vai trò thường tạo ra quá tải.', 'Ghi lại một việc bạn nghĩ không thuộc vai trò của mình.'),
  ('S1-03', 'Tôi không biết ưu tiên điều gì', 'S1', 'ro_rang', 'Ưu tiên xung đột',
   ARRAY['rối rắm', 'áp lực'], ARRAY['chuyển việc liên tục'], ARRAY[]::text[], NULL,
   'Có quá nhiều việc cần làm.
Mọi việc đều được gọi là "quan trọng".', 'Bạn có biết điều gì quan trọng nhất trong vai trò hiện tại không?', 'Nếu chỉ hoàn thành một việc tuần này, đó nên là việc gì?', 'Vai trò rõ ràng giúp tạo ra ưu tiên rõ ràng.', 'Xác định 1 KPI quan trọng nhất của vai trò hiện tại.'),
  ('S1-04', 'Tôi luôn cảm thấy mình chưa đủ tốt', 'S1', 'ro_rang', 'Tiêu chí đánh giá không rõ',
   ARRAY['nghi ngờ bản thân'], ARRAY['làm quá mức'], ARRAY[]::text[], NULL,
   'Bạn làm việc chăm chỉ.
Nhưng vẫn không chắc mình đang làm tốt hay không.', 'Bạn đang đánh giá bản thân bằng tiêu chí nào?', 'Tiêu chí đó có thực sự rõ ràng không?', 'Sự không chắc chắn kéo dài thường đến từ việc thiếu tiêu chuẩn rõ ràng.', 'Liệt kê các tiêu chí đánh giá thành công của vai trò hiện tại.'),
  ('S1-05', 'Tôi nhận được những chỉ đạo trái ngược nhau', 'S1', 'ro_rang', 'Kỳ vọng xung đột',
   ARRAY['căng thẳng', 'bối rối'], ARRAY['chiều lòng nhiều phía'], ARRAY[]::text[], NULL,
   'Một người yêu cầu làm nhanh.
Người khác yêu cầu làm kỹ.
Bạn cố làm cả hai.', 'Bạn đang phải đáp ứng bao nhiêu kỳ vọng khác nhau?', 'Kỳ vọng nào thực sự quan trọng?', 'Không phải mọi kỳ vọng đều có giá trị ngang nhau.', 'Xác định ai là stakeholder quan trọng nhất trong vai trò của bạn.'),
  ('S1-06', 'Tôi không hiểu tại sao mình phải làm việc này', 'S1', 'ro_rang', 'Mất kết nối với mục đích công việc',
   ARRAY['chán nản', 'mất động lực'], ARRAY['làm cho xong'], ARRAY[]::text[], NULL,
   'Bạn hoàn thành nhiệm vụ.
Nhưng không thấy ý nghĩa của nó.', 'Bạn có hiểu công việc này đóng góp điều gì không?', 'Ai hưởng lợi từ công việc bạn đang làm?', 'Con người thường gắn kết hơn khi hiểu mục đích phía sau công việc.', 'Viết ra ai được hưởng lợi từ công việc của bạn.'),
  ('S1-07', 'Tôi không biết mình có quyền quyết định đến đâu', 'S1', 'ro_rang', 'Phạm vi trách nhiệm không rõ',
   ARRAY['do dự', 'lo lắng'], ARRAY['né quyết định'], ARRAY[]::text[], NULL,
   'Bạn muốn chủ động.
Nhưng sợ vượt quá quyền hạn.', 'Bạn có biết mình được phép quyết định điều gì không?', 'Điều gì khiến bạn do dự?', 'Thiếu rõ ràng về quyền hạn làm giảm sự chủ động.', 'Liệt kê 3 việc bạn có thể tự quyết định mà không cần xin phép.'),
  ('S1-08', 'Vai trò của tôi đang thay đổi', 'S1', 'ro_rang', 'Vai trò chuyển đổi',
   ARRAY['bất an', 'mất cân bằng'], ARRAY['thích nghi bị động'], ARRAY[]::text[], NULL,
   'Công việc hiện tại không còn giống lúc bạn bắt đầu.
Nhưng không ai thực sự nói rõ điều đó.', 'Vai trò của bạn đã thay đổi như thế nào?', 'Bạn có đang được kỳ vọng khác trước không?', 'Vai trò luôn tiến hóa, nhưng kỳ vọng không phải lúc nào cũng được cập nhật.', 'So sánh vai trò hiện tại với 1 năm trước.'),
  ('S1-09', 'Tôi không biết điều gì là đủ', 'S1', 'ro_rang', 'Kỳ vọng vô hạn',
   ARRAY['kiệt sức', 'áp lực'], ARRAY['làm việc quá mức'], ARRAY[]::text[], NULL,
   'Dù làm được bao nhiêu.
Luôn có thêm điều cần làm.', 'Bạn có biết đâu là điểm hoàn thành hợp lý không?', 'Ai đang định nghĩa "đủ"?', 'Không có giới hạn rõ ràng thường dẫn đến kiệt sức.', 'Xác định tiêu chuẩn "đủ tốt" cho một nhiệm vụ quan trọng.'),
  ('S1-10', 'Tôi thực sự được thuê để làm gì?', 'S1', 'ro_rang', 'Mất rõ ràng về vai trò cốt lõi',
   ARRAY['mất phương hướng'], ARRAY['phân tán nguồn lực'], ARRAY[]::text[], NULL,
   'Sau nhiều năm làm việc.
Bạn nhận ra mình dành phần lớn thời gian cho những việc không phải lý do ban đầu mình được tuyển.', 'Nếu mô tả vai trò hiện tại bằng một câu, bạn sẽ viết gì?', 'Bạn có đang làm đúng công việc mình được kỳ vọng làm không?', 'Sự rõ ràng bắt đầu từ việc hiểu vai trò cốt lõi của mình.', 'Viết lại Job Description của chính mình bằng ngôn ngữ đơn giản.
S2 – Collaboration Capability
Human Need
Clarity
SCA Dimension
S2 – Năng lực phối hợp
Câu hỏi cốt lõi
Tôi có biết cách phối hợp với người khác để công việc được hoàn thành không?'),
  ('S2-01', 'Tôi không biết nên tìm ai để giải quyết việc này', 'S2', 'ro_rang', 'Thiếu rõ ràng về đầu mối',
   ARRAY['bối rối', 'lạc hướng'], ARRAY['hỏi nhiều nơi'], ARRAY[]::text[], NULL,
   'Bạn gặp một vấn đề.
Nhưng không biết ai là người phù hợp để hỗ trợ.
Bạn hỏi nhiều nơi.
Mỗi người chỉ bạn sang một người khác.', 'Khi gặp khó khăn, bạn có biết tìm ai không?', 'Điều gì khiến việc tìm đúng người trở nên khó khăn?', 'Phối hợp hiệu quả bắt đầu từ việc biết ai đang nắm điều gì.', 'Liệt kê 3 người bạn thường tìm đến khi cần hỗ trợ.'),
  ('S2-02', 'Tôi luôn phải chờ người khác', 'S2', 'ro_rang', 'Phụ thuộc trong quy trình',
   ARRAY['sốt ruột', 'bất lực'], ARRAY['chờ đợi', 'trì hoãn'], ARRAY[]::text[], NULL,
   'Bạn đã hoàn thành phần việc của mình.
Nhưng dự án vẫn đứng yên.
Vì đang chờ một người khác.', 'Điều gì thường làm công việc bị chậm lại?', 'Bạn có nhìn thấy toàn bộ quy trình không?', 'Nút thắt thường nằm ở điểm giao nhau giữa các vai trò.', 'Xác định bước nào trong quy trình thường gây chậm trễ nhất.'),
  ('S2-03', 'Chúng tôi làm cùng một việc mà không biết', 'S2', 'ro_rang', 'Chồng chéo trách nhiệm',
   ARRAY['khó chịu', 'lãng phí'], ARRAY['làm trùng việc'], ARRAY[]::text[], NULL,
   'Sau nhiều ngày làm việc.
Bạn phát hiện đồng nghiệp cũng đang làm cùng một việc tương tự.', 'Bạn có thường gặp tình huống công việc bị trùng lặp không?', 'Điều gì khiến điều đó xảy ra?', 'Sự phối hợp yếu thường tạo ra lãng phí vô hình.', 'Quan sát một công việc có nhiều người cùng tham gia.'),
  ('S2-04', 'Việc bị đẩy qua đẩy lại', 'S2', 'ro_rang', 'Không rõ trách nhiệm',
   ARRAY['bực bội', 'căng thẳng'], ARRAY['đùn đẩy trách nhiệm'], ARRAY[]::text[], NULL,
   'Khi có vấn đề phát sinh.
Không ai chắc mình là người cần xử lý.', 'Khi có sự cố, mọi người phản ứng thế nào?', 'Ai là người chịu trách nhiệm cuối cùng?', 'Công việc dễ bị đình trệ khi quyền sở hữu không rõ ràng.', 'Xác định ai là người sở hữu kết quả cuối cùng của một nhiệm vụ quan trọng.'),
  ('S2-05', 'Chúng tôi hiểu khác nhau về cùng một mục tiêu', 'S2', 'ro_rang', 'Thiếu đồng bộ',
   ARRAY['thất vọng', 'rời rạc'], ARRAY['làm việc lệch hướng'], ARRAY[]::text[], NULL,
   'Mỗi người đều nỗ lực.
Nhưng hướng đi lại khác nhau.', 'Mọi người có đang nhìn cùng một mục tiêu không?', 'Điều gì thường bị hiểu khác nhau?', 'Phối hợp không phải làm cùng nhau.
Mà là đi cùng hướng.', 'Thử hỏi đồng nghiệp mục tiêu quan trọng nhất hiện tại là gì.'),
  ('S2-06', 'Tôi luôn phải nhắc lại nhiều lần', 'S2', 'ro_rang', 'Thiếu cơ chế phối hợp',
   ARRAY['mệt mỏi', 'áp lực'], ARRAY['nhắc việc liên tục'], ARRAY[]::text[], NULL,
   'Bạn đã trao đổi.
Nhưng vẫn phải nhắc lại.
Rồi lại nhắc thêm lần nữa.', 'Điều gì thường bị bỏ sót trong quá trình phối hợp?', 'Thông tin đang được quản lý bằng hệ thống hay trí nhớ?', 'Vấn đề không phải con người quên.
Mà là hệ thống chưa hỗ trợ họ nhớ.', 'Xác định một việc đang phụ thuộc quá nhiều vào việc nhắc nhở thủ công.'),
  ('S2-07', 'Tôi không hiểu công việc của người khác', 'S2', 'ro_rang', 'Thiếu hiểu biết liên chức năng',
   ARRAY['xa cách', 'hiểu lầm'], ARRAY['làm việc theo silo'], ARRAY[]::text[], NULL,
   'Bạn biết rất rõ công việc của mình.
Nhưng không hiểu người khác đang chịu áp lực gì.', 'Bạn hiểu bao nhiêu về công việc của các nhóm khác?', 'Điều gì sẽ thay đổi nếu bạn hiểu họ hơn?', 'Sự cảm thông trong công việc thường bắt đầu từ sự hiểu biết.', 'Tìm hiểu một quy trình của bộ phận khác.'),
  ('S2-08', 'Mỗi lần phối hợp đều rất mệt', 'S2', 'ro_rang', 'Chi phí phối hợp cao',
   ARRAY['quá tải', 'kiệt sức'], ARRAY['họp nhiều', 'trao đổi lặp'], ARRAY[]::text[], NULL,
   'Một việc đơn giản.
Nhưng cần rất nhiều cuộc họp và trao đổi.', 'Điều gì làm việc phối hợp trở nên tốn năng lượng?', 'Khó khăn nằm ở con người hay quy trình?', 'Khi cấu trúc rõ ràng, việc phối hợp trở nên nhẹ nhàng hơn.', 'Ghi lại những bước phối hợp gây mất thời gian nhất.'),
  ('S2-09', 'Chúng tôi phụ thuộc quá nhiều vào một người', 'S2', 'ro_rang', 'Điểm nghẽn phối hợp',
   ARRAY['lo lắng', 'phụ thuộc'], ARRAY['tập trung kiến thức vào một người'], ARRAY[]::text[], NULL,
   'Có một người biết mọi thứ.
Khi người đó bận hoặc nghỉ phép.
Mọi việc gần như dừng lại.', 'Có ai đang trở thành điểm nghẽn trong hệ thống không?', 'Điều gì khiến hệ thống phụ thuộc vào họ?', 'Một hệ thống khỏe không phụ thuộc vào một cá nhân duy nhất.', 'Xác định kiến thức hoặc quy trình cần được chia sẻ nhiều hơn.'),
  ('S2-10', 'Điều gì giúp chúng tôi phối hợp tốt nhất?', 'S2', 'ro_rang', 'Nhận diện điều kiện phối hợp hiệu quả',
   ARRAY['tin tưởng', 'nhẹ nhõm'], ARRAY['chủ động phối hợp'], ARRAY[]::text[], NULL,
   'Có những thời điểm mọi việc diễn ra rất trơn tru.
Mọi người hiểu nhau.
Công việc tiến triển nhanh.', 'Điều gì đang hiện diện khi việc phối hợp hiệu quả?', 'Điều đó có thể được tạo ra thường xuyên hơn không?', 'Những gì hoạt động tốt cũng đáng được quan sát như những gì chưa tốt.', 'Ghi lại một trải nghiệm phối hợp hiệu quả gần đây.
S3 – Information Flow
Human Need
Clarity
SCA Dimension
S3 – Dòng chảy thông tin
Câu hỏi cốt lõi
Tôi có thể tiếp cận đúng thông tin vào đúng thời điểm để làm tốt công việc của mình không?'),
  ('S3-01', 'Tôi không biết tìm thông tin ở đâu', 'S3', 'ro_rang', 'Khó tìm thông tin',
   ARRAY['bối rối', 'mất kiên nhẫn'], ARRAY['tìm kiếm nhiều nơi'], ARRAY[]::text[], NULL,
   'Bạn biết thông tin đó tồn tại.
Nhưng không biết nằm ở đâu.
Bạn phải hỏi nhiều người hoặc tìm rất lâu.', 'Bạn có thường mất thời gian để tìm thông tin không?', 'Thông tin nào bạn phải đi tìm nhiều nhất?', 'Khi thông tin khó tiếp cận, năng lượng thường bị tiêu hao trước khi công việc bắt đầu.', 'Ghi lại một thông tin bạn đã mất nhiều thời gian để tìm trong tuần qua.'),
  ('S3-02', 'Tôi phát hiện thông tin quá muộn', 'S3', 'ro_rang', 'Thông tin đến trễ',
   ARRAY['hụt hẫng', 'bị động'], ARRAY['phản ứng muộn'], ARRAY[]::text[], NULL,
   'Bạn đang làm việc theo một hướng.
Rồi phát hiện có một thay đổi quan trọng đã diễn ra từ trước.', 'Bạn có thường biết tin sau người khác không?', 'Điều đó ảnh hưởng thế nào đến công việc của bạn?', 'Không chỉ chất lượng thông tin quan trọng.
Thời điểm nhận được thông tin cũng quan trọng.', 'Xác định loại thông tin bạn cần nhận sớm hơn.'),
  ('S3-03', 'Mỗi người nói một kiểu', 'S3', 'ro_rang', 'Thông tin không nhất quán',
   ARRAY['hoang mang', 'nghi ngờ'], ARRAY['xác minh nhiều lần'], ARRAY[]::text[], NULL,
   'Bạn hỏi ba người.
Nhận được ba câu trả lời khác nhau.', 'Điều này quen thuộc với bạn đến đâu?', 'Điều gì khiến mọi người hiểu khác nhau?', 'Sự thiếu nhất quán thường tạo ra nhiều nhầm lẫn hơn việc thiếu thông tin.', 'Quan sát một thông tin đang được diễn giải khác nhau trong tổ chức.'),
  ('S3-04', 'Tôi không biết thông tin nào là mới nhất', 'S3', 'ro_rang', 'Phiên bản thông tin không rõ',
   ARRAY['lo lắng', 'thiếu chắc chắn'], ARRAY['dùng sai tài liệu'], ARRAY[]::text[], NULL,
   'Có nhiều file.
Nhiều tài liệu.
Nhiều nguồn.
Nhưng không ai chắc đâu là bản chính thức.', 'Bạn có từng làm việc trên thông tin đã lỗi thời?', 'Điều gì khiến việc cập nhật trở nên khó khăn?', 'Thông tin cũ thường tạo ra quyết định sai.', 'Kiểm tra một tài liệu bạn đang sử dụng thường xuyên.'),
  ('S3-05', 'Tôi phải hỏi cùng một câu hỏi nhiều lần', 'S3', 'ro_rang', 'Kiến thức không được lưu giữ',
   ARRAY['mệt mỏi', 'lặp lại'], ARRAY['hỏi lại liên tục'], ARRAY[]::text[], NULL,
   'Mỗi lần cần thông tin.
Bạn lại phải hỏi lại từ đầu.', 'Điều gì thường xuyên phải được giải thích lặp đi lặp lại?', 'Tại sao kiến thức đó chưa được ghi nhận?', 'Một hệ thống tốt giúp thông tin ở lại ngay cả khi con người thay đổi.', 'Ghi lại một kiến thức nên được lưu trữ thay vì truyền miệng.'),
  ('S3-06', 'Tôi bị ngập trong quá nhiều thông tin', 'S3', 'ro_rang', 'Quá tải thông tin',
   ARRAY['quá tải', 'mất tập trung'], ARRAY['đọc nhiều', 'xử lý ít'], ARRAY[]::text[], NULL,
   'Tin nhắn.
Email.
Thông báo.
Tài liệu.
Mọi thứ đều quan trọng.', 'Bạn có cảm thấy khó theo kịp lượng thông tin hiện tại không?', 'Thông tin nào thực sự hữu ích với bạn?', 'Nhiều thông tin không đồng nghĩa với nhiều sự rõ ràng.', 'Loại bỏ một nguồn thông tin không còn giá trị.'),
  ('S3-07', 'Có những thứ chỉ một vài người biết', 'S3', 'ro_rang', 'Thông tin bị giữ lại',
   ARRAY['bất công', 'khó chịu'], ARRAY['phụ thuộc người khác'], ARRAY[]::text[], NULL,
   'Bạn nhận ra một số người luôn có lợi thế.
Không phải vì họ giỏi hơn.
Mà vì họ biết nhiều hơn.', 'Có thông tin nào không dễ tiếp cận với tất cả mọi người không?', 'Điều đó ảnh hưởng thế nào đến sự công bằng?', 'Thông tin là một dạng quyền lực trong hệ thống.', 'Xác định một thông tin nên được chia sẻ rộng hơn.'),
  ('S3-08', 'Tôi không hiểu bức tranh toàn cảnh', 'S3', 'ro_rang', 'Thiếu ngữ cảnh',
   ARRAY['mất kết nối', 'mơ hồ'], ARRAY['làm theo chỉ dẫn'], ARRAY[]::text[], NULL,
   'Bạn biết việc mình cần làm.
Nhưng không hiểu tại sao nó quan trọng.', 'Bạn có hiểu công việc của mình kết nối với mục tiêu lớn hơn thế nào không?', 'Điều gì còn thiếu trong bức tranh hiện tại?', 'Thông tin chỉ có ý nghĩa khi được đặt trong ngữ cảnh phù hợp.', 'Hỏi thêm về mục tiêu hoặc lý do phía sau một nhiệm vụ.'),
  ('S3-09', 'Tôi không biết điều gì đã thay đổi', 'S3', 'ro_rang', 'Thiếu cập nhật',
   ARRAY['bất ngờ', 'bị động'], ARRAY['chạy theo thay đổi'], ARRAY[]::text[], NULL,
   'Một quy trình mới xuất hiện.
Một quyết định mới được đưa ra.
Nhưng bạn không hề biết.', 'Bạn có thường xuyên bất ngờ trước những thay đổi không?', 'Thông tin thay đổi đang được truyền đi như thế nào?', 'Thay đổi không được truyền đạt thường tạo ra kháng cự.', 'Quan sát một thay đổi gần đây và cách nó được truyền thông.'),
  ('S3-10', 'Điều gì giúp tôi luôn có đủ thông tin?', 'S3', 'ro_rang', 'Nhận diện dòng chảy thông tin hiệu quả',
   ARRAY['chủ động', 'tự tin'], ARRAY['tìm kiếm và chia sẻ thông tin'], ARRAY[]::text[], NULL,
   'Có những thời điểm bạn cảm thấy rất rõ ràng.
Bạn biết điều gì đang diễn ra.
Bạn biết mình cần làm gì.', 'Điều gì tạo ra cảm giác đó?', 'Bạn nhận thông tin từ đâu?', 'Sự rõ ràng thường xuất hiện khi thông tin đúng được tiếp cận đúng lúc.', 'Ghi lại nguồn thông tin hữu ích nhất với bạn hiện nay.')
on conflict (story_id) do nothing;

-- SEED_END
