-- Bản tiếng Anh của 30 bài đọc trong Thư viện Nội dung Cảm xúc.
--
-- ---------------------------------------------------------------------------
-- LUẬT DỊCH ĐÃ ÁP
--
-- 1. GIỮ GIỌNG, KHÔNG GIỮ CÚ PHÁP. Bản gốc viết theo lối tiếng Việt: câu dài,
--    nhiều mệnh đề nối bằng dấu phẩy, chủ ngữ thường được lược. Dịch sát cú
--    pháp ra tiếng Anh cho những câu chạy dài không ngắt được. Nên ngắt lại
--    theo nhịp tiếng Anh, miễn giữ đúng điều đang được nói và giữ giọng "mời,
--    không chấm" của app.
--
-- 2. KHÔNG THÊM CHỦ NGỮ "YOU" VÀO CHỖ BẢN GỐC CỐ Ý KHÔNG CÓ. Bản gốc nói về
--    một hiện tượng chung ("nhiều người vẫn tiếp tục kiểm tra") chứ không chỉ
--    tay vào người đọc. Đổi sang "you keep checking" là biến một quan sát thành
--    một lời phán. Chỉ câu hỏi cuối bài mới xưng "you" — đúng như bản gốc.
--
-- 3. GIỮ NGUYÊN SỐ ĐOẠN VÀ VỊ TRÍ DÒNG TRỐNG. `MoodContent.paragraphs` tách
--    `body` theo dòng trống để dựng khối văn bản; gộp hai đoạn làm một là đổi
--    bố cục màn đọc.
--
-- Đây là bản dịch máy đọc lại bằng tay, chưa qua người bản ngữ. Nội dung không
-- đổi nghĩa, nhưng nhịp câu nên được đọc lại trước khi phát hành rộng.

-- ---------------------------------------------------------------------------
-- stress — Căng thẳng
-- ---------------------------------------------------------------------------

update public.wr_mood_content set
  title_en = 'When the pressure comes from wanting to control everything',
  body_en = E'Some days the tension comes from a deadline that moved up, a hard meeting, a big decision waiting to be made. Other days it arrives with no clear reason at all. Nothing large happens; there is just a heaviness that runs from morning to night.\n\nLook a little closer and a fair part of this kind of tension comes from trying to control things that were never fully in anyone''s hands. How a meeting turns out. How other people react. Whether a project stays on schedule, even after your own part is finished. Not only carrying your own share of the worry, but quietly taking on the worry for things you cannot decide.\n\nThis is not a sign of weakness or poor discipline. Wanting control is usually a natural reflex when there is a lot of uncertainty around. The less safe the coming days feel, the more people tend to hold tight to whatever they believe they can control, even when that grip is mostly an illusion of safety.\n\nA small, familiar example: after handing a piece of work to a colleague, many people keep checking in, keep reminding, or quietly redo that piece their own way. Not really out of distrust, but because the settled feeling only arrives when everything matches the picture in their head. The price of that settled feeling is attention split across too many things at once, instead of gathered where it is actually needed.\n\nOne way to recognise this kind of pressure is to ask how far the thing you are worried about actually falls within your reach. Some things you can affect directly. Some you can only contribute to, with the rest resting on other people or on circumstance. And some sit outside your reach no matter how much you want them not to. These three usually get folded into one single block of worry, so the energy spreads evenly instead of gathering where it could make a real difference.\n\nLetting go of control is not always easy, least of all with the things you genuinely care about. But sometimes just naming which part of the current worry can be affected, and which part cannot, is enough for the tension to ease a little. Among the things weighing on you right now, which part can you actually affect?'
where id = '30f9d62e-3c9d-4450-9329-31b4f7639f0c';

update public.wr_mood_content set
  title_en = 'Tension is not the enemy, only a signal',
  body_en = E'Sometimes tension arrives with guilt attached, as if you should not be feeling this, as if you should be handling it better. The feeling gets read as a weakness to hide rather than as an ordinary thing happening inside.\n\nBut tension, most of the time, is not the enemy. It is a signal, like a warning light on a dashboard, saying that something needs more attention than it is currently getting.\n\nThis is not to say tension is pleasant or something to welcome. Only that seeing it as a signal rather than an enemy changes the natural response. Instead of trying to put the feeling out as fast as possible, there is a small pause to ask what the signal is pointing at.\n\nA familiar situation: before an important presentation, the heartbeat picks up, the hands go slightly cold, the mind runs through everything that could happen. Read as a sign of weakness, the usual response is to push it down and act as though nothing is there. Read as a signal that this genuinely matters to you, the same energy can be redirected rather than fought.\n\nOne way to tell them apart is to ask where the signal is pointing. Some kinds say a boundary is being crossed, as when too much work lands in too short a stretch. Some say something genuinely important is on the table, as before a big decision. And some are simply the body reacting to uncertainty, needing no particular action right away.\n\nNot every signal calls for an immediate solution. Sometimes noticing it and naming what it is reporting is already enough for the tension to stop taking up all the room inside.'
where id = '4508365e-7208-43bb-8ffd-40d75f5e8f16';

update public.wr_mood_content set
  title_en = 'When everything is urgent at once',
  body_en = E'Some days everything seems to ask for attention at the same moment: an email that needs an answer now, a meeting pulled earlier than planned, a colleague asking for an opinion right this minute. None of it is especially large, but together it creates a stifled feeling that is hard to name.\n\nThat feeling usually gets read as too much work. Most of the time, though, the problem is not the quantity. It is that all of it arrives at once, with no gap between one thing and the next for the mind to change state.\n\nThe brain does not switch between tasks as quickly as people assume. Every move from one thing to another needs a short stretch to reorient, even just a few seconds, so the attention given to the last thing can be set down and the attention for the new one gathered up. When several things land together, that gap gets squeezed to almost nothing, and the overwhelm that follows is not because the work is hard but because there was never enough time to change state properly — so each thing gets handled while part of the mind is still caught on the one before.\n\nA familiar situation: deep in writing an important passage, a message pops up, then a call comes in, then someone stops by the desk with a quick question. After all three are dealt with, coming back to the passage takes a few more minutes just to remember what you meant to write.\n\nOne way to ease this is, when several things arrive together, to let yourself take them in order rather than all at once — even when each one only takes a moment to finish — and to accept that the rest will have to wait a little longer, even though the urge to settle everything immediately is still there. A useful question is which of these actually needs an answer now, and which is only creating a sense of urgency without being urgent, because not everything that arrives at the same moment carries the same weight.\n\nYou cannot always choose the order in which work gets handled. But knowing the stifled feeling comes from the pile-up rather than the difficulty can make it a little easier to hold, instead of blaming yourself for not being fast enough.'
where id = 'b3c842f6-0d8c-485e-ae96-743c5d6a46a4';

update public.wr_mood_content set
  title_en = 'Tension from the fear of letting someone down',
  body_en = E'There is a kind of tension that comes not from the size of the workload but from the fear that someone will be disappointed — a manager, a colleague who is counting on you, or sometimes just an imagined picture of what other people will think.\n\nThis kind is usually quieter than the others, because it is not tied to a particular deadline or a clear task. It sits behind everything, working its way into how each small piece of work is approached, so that every decision carries an unspoken question: will this leave someone disappointed?\n\nThis is not a sign of weakness or of low confidence. It usually grows out of caring about relationships and about other people''s trust, which is a good thing in itself. It only turns into constant pressure when it is carried too far, so that every action gets weighed first through someone else''s lens instead of your own.\n\nA familiar situation: about to send a report, reading it over and over — not because there is still an error, but out of worry about what the person receiving it will make of it. The time spent settling that worry can end up being longer than the time the content actually needed.\n\nOne way to find the line is to ask whether you are trying to do well for the sake of the work itself, or out of concern for one particular person''s reaction. Both motives are reasonable, but when the second takes over, energy tends to go into defending against something that may never happen instead of into doing the work well.\n\nOther people being disappointed is sometimes unavoidable, however hard you have tried. Knowing that in advance does not make the worry stop, but it can make it sit a little lighter each time it shows up.'
where id = 'a4082c2a-38ed-455b-944d-9689740a5e85';

update public.wr_mood_content set
  title_en = 'When the body speaks before you catch up',
  body_en = E'Sometimes the body notices something is off before the mind has words for it. A headache turns up before a difficult meeting. The shoulders tighten in the middle of the afternoon for no clear reason. The stomach turns ahead of a conversation that has not happened yet.\n\nThese reactions usually get ignored, or treated as a nuisance to clear quickly — a painkiller, a coffee, and back to work. But the body rarely reacts for nothing. Most of the time it is responding to something the mind has not yet processed consciously.\n\nBody and mind are not as separate as they are usually described. The nervous system reacts to strain much faster than conscious thought, which means the body can already be responding to a situation while the mind is still busy elsewhere and has not yet registered the problem.\n\nA familiar situation: feeling uneasy all morning without knowing why, until you remember there is a meeting this afternoon that you have been quietly avoiding. The body knew first; the mind took a while to catch up.\n\nOne way to work with this is, when the body sends an unusual signal for no clear reason, to take a moment and ask what has been waiting to be dealt with that you have not really faced. The answer does not always come right away, but asking is already a way of listening to the body rather than only trying to quiet it.\n\nThe body is not a machine to be kept running smoothly at any cost. More often it is the earliest messenger, arriving before the mind notices there is something that needs attention.'
where id = '7b3b47fe-a5bc-4fae-8381-e41bf8d06cb7';

-- ---------------------------------------------------------------------------
-- tired — Mệt mỏi
-- ---------------------------------------------------------------------------

update public.wr_mood_content set
  title_en = 'Running on empty is not weakness',
  body_en = E'A question tends to surface when the exhaustion has gone on a while: whether you have less endurance than other people. It usually arrives with a little shame attached, as though being this tired were a sign of not being strong enough, not disciplined enough, or not managing time as well as everyone else seems to.\n\nBut exhaustion is not a measure of endurance. It is the natural result of spending more energy than gets put back over a long enough stretch — however strong the will, however deep the experience, however much someone loves the work.\n\nNobody holds an unlimited reserve. Body and mind both need time to recover, the way a muscle needs rest between sessions to avoid injury. Running at high intensity for long stretches without matching rest brings exhaustion not because someone is weak, but because that is how the body answers a long imbalance between what is given out and what comes back in.\n\nA familiar situation: after a big project ends well, instead of relief many people find themselves more worn out than ever, sometimes falling ill straight afterwards. This is not coincidence. The body held itself together for the whole run of the project, keeping everything moving regardless of the tiredness underneath, and once the pressure lifts, all of that stored tiredness finally has room to show — sometimes more strongly than anything felt while still busy.\n\nOne way to tell real exhaustion from an ordinary tired day is to notice whether the feeling survives several days of rest. Ordinary tiredness usually eases after one good night. Exhaustion is often still there even after a short break, because it is not only lost sleep — it is an energy debt built up over a long time, and one or two nights cannot clear it.\n\nSeeing exhaustion as a debt to be paid down gradually, rather than a personal failing to fix immediately, can be a starting point for treating yourself more gently through this stretch, and for letting recovery run at the pace it actually needs instead of being pushed to go faster.'
where id = '652f55e4-0b9f-44e9-b42c-f922425b0a7c';

update public.wr_mood_content set
  title_en = 'When to stop, when to keep going',
  body_en = E'One of the hardest questions when you are tired is not how to stop being tired. It is how to tell whether this is the moment to rest, or whether a little more effort would carry you through.\n\nThe difficulty comes from tiredness having no clear edge. There is no reading that says precisely when to stop, unlike a car running low on fuel with a gauge that tells the driver in good time to pull into the nearest station.\n\nMost people grow up with the message that a bit more effort is always the right choice, that stopping partway means lacking persistence or giving up too easily. That message is not entirely wrong. It just does not account for the kinds of tiredness where pushing makes things worse rather than better — and for the fact that the time spent pushing on can produce far less than stopping at the right moment and coming back later in better shape.\n\nA concrete example: writing a report, reading the same paragraph three times and still not taking in what you just wrote. Sitting for another half hour usually adds no quality, only frustration, and sometimes means rewriting it from scratch the next day — so the total time spent ends up longer than if you had stopped a little sooner.\n\nOne frame that can help is the difference between tired-from-hard and tired-from-empty. Tired-from-hard usually carries a little charge with it, a sense of getting closer to something even if slowly, like working a difficult puzzle where each small step still registers. Tired-from-empty usually carries a hollowness instead, no clear sense of moving forward or back, only a heaviness spreading through the body. The first is often worth a little more effort, because the reward ahead can still be felt. The second is usually the moment to stop, even for fifteen minutes, so some energy has a chance to return before carrying on.\n\nLearning to tell these two apart is not a skill that arrives all at once. It grows clearer each time you pay attention to yourself, and each time you read it right you also learn a little more about how your body and mind are answering the pace the work is currently keeping.'
where id = 'd4af3e18-4343-4c2d-90ac-f0e3b11d359d';

update public.wr_mood_content set
  title_en = 'Tired from always being the one who decides',
  body_en = E'There is a particular tiredness reserved for people who are always in the position of deciding — whether large decisions about direction, or the constant small choices through the day about what to do first, who to answer first, who carries which part.\n\nThis kind rarely gets recognised, because it does not come from doing a lot. It comes from choosing without pause. Every choice, however small, spends a certain amount of mental energy, and that energy is not unlimited within a single day.\n\nThe phenomenon is sometimes called decision fatigue. It sets in when the number of choices to be made goes past what the mind can comfortably handle in a stretch of time. It has nothing to do with how hard each decision is, and everything to do with the total number of times a choice had to be made — even choosing between two things that are almost equivalent. Towards the end of a long run of decisions, the quality of the choices tends to fall, not from lack of ability, but because the energy for weighing things up has been largely spent on the ones that came before.\n\nA familiar situation: at the end of a working day full of meetings that needed direction, getting home with nothing left to decide what to have for dinner — a far simpler choice than anything handled all day. That is not laziness. The part of the brain that makes decisions has been running at full capacity since early on.\n\nOne way to lighten this load is, for choices that do not matter much, to let yourself decide quickly rather than weighing them as carefully as the big ones, so the energy is saved for what genuinely needs deeper thought. Not every decision deserves the same amount of deliberation, and sorting in advance which are the important ones and which can simply be picked is itself a way of conserving energy across a long day.\n\nBeing the one who decides is not a burden to be given up; often it comes with the role. But recognising it as real tiredness rather than a personal weakness can be a first step towards sharing it out, or towards simplifying the small choices that never needed to be so careful.'
where id = '71689bcc-1d2e-4264-aca8-547b8914ef13';

update public.wr_mood_content set
  title_en = 'Sleeping enough and still not feeling restored',
  body_en = E'There is a particular confusion in having slept enough hours, even slept well, and still waking without any sense of recovery — carrying the same heaviness as before going to bed.\n\nThis tends to leave people puzzled, because by everything commonly understood, enough sleep is the main condition for getting energy back. When it does not work out that way, it is easy to start feeling something is wrong with you, or to wonder whether you are overstating how tired you really are.\n\nBut sleep only addresses one part of tiredness, the physical part. There are other kinds — from holding emotions in over a long stretch, from constantly adjusting yourself to fit the surroundings, from carrying an unresolved worry in your head — that plain sleep, however deep and however long, simply cannot reach.\n\nA familiar situation: after a tense week over a difficult working relationship, having caught up fully on sleep over the weekend, the heaviness is still there on Monday morning — because the source of the tiredness was never lost sleep, but the thing still unresolved.\n\nOne way to tell them apart is to ask whether the tiredness eases after a good night. If it does, it is probably ordinary physical tiredness. If almost nothing changes, something else may be going on, something not physical, that needs to be looked at a different way.\n\nNot all tiredness can be solved with physical rest. Sometimes the first step is simply recognising that this kind needs a different sort of care, not one more night of sleep.'
where id = '89c5acd9-6ed3-4042-8322-1036fb138caa';

update public.wr_mood_content set
  title_en = 'Drained by conversations, not only by work',
  body_en = E'There is a kind of exhaustion that rarely gets mentioned. It comes not from the volume of work but from conversations — particularly the ones that demand staying alert, being careful with every sentence, or constantly weighing how the other person is reacting.\n\nThis kind is easy to overlook, because talking is not usually counted as real work next to writing a report or working through figures. But for many people, especially anyone inclined to be attuned to other people''s feelings, a long meeting with several opposing views can cost far more energy than a day of working alone.\n\nThe brain devotes more resources to social interaction than is usually recognised: reading facial expressions, adjusting tone, weighing each word before it is said, all while tracking the content of the conversation and preparing the next response, more or less at the same time. Doing all of that continuously for hours, especially in conversations that are sensitive or involve several parties, makes the drained feeling entirely understandable — not an overreaction, and not a sign of poor communication skills.\n\nA familiar situation: after a day of back-to-back meetings, with nothing especially demanding intellectually, still feeling completely wrung out by evening, wanting only to be alone and not to speak to anyone else — even people you are close to — although no single conversation that day was actually tense or difficult.\n\nOne way to look after yourself after days like that is to acknowledge this as real tiredness, needing a quiet stretch to recover, the way a muscle needs rest after heavy use. That stretch does not have to be filled with anything else, including activities counted as leisure that still ask for interaction with other people.\n\nBeing drained after talking does not mean disliking the people around you, and it does not mean becoming harder to reach over time. It simply means a different kind of energy has been spent, and that kind needs its own time to come back, like any other reserve in the body.'
where id = '190aa47e-7957-4baa-9e0f-34b54e0aca50';

-- ---------------------------------------------------------------------------
-- foggy — Mơ hồ
-- ---------------------------------------------------------------------------

update public.wr_mood_content set
  title_en = 'Three questions to clear up something still vague',
  body_en = E'When work is handed over without enough information, the reflex is usually to guess, then start, hoping your reading of it is right. There is another way, a little slower but usually cheaper later: stop and ask three questions before beginning.\n\nFirst, what does the finished thing need to look like. Second, who decides whether it is good enough. Third, are there limits on time or resources worth knowing up front.\n\nThese three do not need a long meeting. They fit in a short message, or a quick question before leaving the conversation. What matters is asking before starting, rather than after heading the wrong way.\n\nFor the piece of work leaving you most in the dark right now, who would those three questions go to?'
where id = 'cacbd908-47af-4b64-a3e1-899bbcc711c2';

update public.wr_mood_content set
  title_en = 'Being unclear is not a sign you lack ability',
  body_en = E'Not being sure you are doing the right thing often gets mistaken for a problem with your own ability. If I were good enough, the thinking goes, I would know what to do. But most of the fog at work does not come from lacking ability. It comes from information that was never handed over.\n\nNobody can work out a process that has never been written down, or guess someone''s expectations correctly when those expectations have never been said out loud. Clarity is a responsibility shared between the person handing over the work and the person taking it on, not something one individual has to produce out of nothing.\n\nSeeing it that way makes the fog feel less personal. It becomes a gap to be filled with a question, rather than evidence that you are not good enough.\n\nNext time something feels unclear, what changes if you treat it as a gap in the information rather than a gap in yourself?'
where id = '7819e13f-7f19-463a-aff3-dfec4dfc8391';

update public.wr_mood_content set
  title_en = 'One minute to name what is unclear',
  body_en = E'Before going back to someone about something vague, one step usually gets skipped: naming precisely what you are unsure of. Often a general sense of fog produces a general question, and the answer that comes back settles nothing.\n\nOne minute, before you ask, try writing down or saying to yourself exactly which part of this you are unsure about. Is it the scope, the person responsible, or the deadline. Separate them out instead of folding them into one large blur.\n\nWhen the question is put more precisely, the answer usually comes back more precisely too. A minute spent naming the real problem can save several unnecessary rounds of back and forth afterwards.\n\nIf you gave yourself one minute right now to name the vaguest thing you are carrying, what would it be?'
where id = '56246daa-f429-48ce-a2d3-aec227c10732';

update public.wr_mood_content set
  title_en = 'When nobody spells it out, you can be the one who asks',
  body_en = E'In many workplaces clarity does not appear on its own; someone has to go and make it. When nobody spells things out, the common reflex is to wait — hoping someone else will speak first, or that things will clear up on their own in time.\n\nBut waiting for clarity to come from someone else can keep the fog going longer than it needs to, especially when everyone is waiting the same way. A simple question, asked at the right moment, can break that circle faster than most people expect.\n\nAsking does not signal that you have failed to keep up. It usually reads the other way — as a sign of someone who genuinely wants to get it right, rather than get it done.\n\nIs there something unclear in your work right now that you are waiting for someone else to ask about, instead of asking yourself?'
where id = 'c11312c9-23f6-4d7e-b723-dd772c2635c5';

update public.wr_mood_content set
  title_en = 'A quiet stretch to let your thinking settle',
  body_en = E'When too many things are unclear at the same time, the reflex is usually to settle all of them immediately — ask every question, chase down every piece of information in one go. But sometimes what is needed first is not action. It is a quiet stretch to let what is scattered in your head arrange itself.\n\nA short quiet stretch, doing nothing, not trying to solve anything, just giving the loose thoughts room to settle. Often what actually needs asking or clearing up only becomes visible after that pause, not while everything is being handled at once.\n\nFog does not always have to be cleared right away. Sometimes it only needs a little room to become clearer on its own.\n\nIf you gave yourself a short quiet stretch right now, what would rise most clearly out of the pile?'
where id = 'eab5faf9-3443-490c-a626-213c8d8d16db';

-- ---------------------------------------------------------------------------
-- outofsync — Lệch nhau
-- ---------------------------------------------------------------------------

update public.wr_mood_content set
  title_en = 'When you are always the last to know',
  body_en = E'There is a particular feeling in being the last to hear things, again and again — after everyone else has discussed it, decided it, and moved on to the next thing. It is not only inconvenient in terms of information. It quietly starts you wondering whether you are really part of the team at all.\n\nMost of the time, being late to the news does not come from being deliberately left out. It usually comes from information travelling through uneven channels: some people sit closer to the source than others, not because they are favoured, but because their role naturally places them nearer that flow.\n\nUnderstanding that does not make the discomfort disappear, but it does separate two things — the feeling of being left behind, and the reality of how information is moving. Those two are not always the same.\n\nNext time you notice you are the last to know, what would help you sit closer to that flow?'
where id = '4d50b8e9-c594-413f-ad77-2d51ce0c12f7';

update public.wr_mood_content set
  title_en = 'Three breaths before sending that message',
  body_en = E'On realising you have missed something important, the first reflex is usually a message typed in a hurry, carrying some irritation that has not yet settled. That message can still be sent, but how it reads will be very different with three breaths in between.\n\nBefore typing, try breathing in slowly, holding for a beat, then breathing out. Not to put the irritation out, but so the message about to go reflects what you actually need rather than the feeling of the moment you found out you had been left out.\n\nA clear question, carrying no reproach, usually gets a faster and fuller answer than one written while annoyed. Three breaths cannot change the fact that you missed something, but they can change how the next conversation goes.\n\nNext time you need to ask about something you missed, what will you use those three breaths for before you type?'
where id = 'b1a4f21b-0c04-4c97-9693-01692b51d157';

update public.wr_mood_content set
  title_en = 'An uneven pace of work is not your fault',
  body_en = E'Some weeks the work piles up until there is no room to breathe, and other weeks go strangely quiet — nobody gets in touch, nothing new comes in. Between those two extremes it is easy to wonder whether you are doing something wrong, or being quietly forgotten during the silent weeks.\n\nMost of the time this unevenness has nothing to do with individual performance. It comes from how the work was planned, sometimes from decisions made at an entirely different level with no direct bearing on you. A rush or a lull is usually a consequence of how the whole system runs, not a test of any one person.\n\nSeeing that does not make the busy weeks any lighter, but it does spare you an unnecessary weight: blaming yourself for a rhythm you did not set.\n\nLooking back at the uneven stretch you have just been through, which part could you affect, and which part was only ever something to adapt to?'
where id = '239faca4-232b-4c30-9d7a-df99c998fee1';

update public.wr_mood_content set
  title_en = 'Holding focus in the middle of scattered information',
  body_en = E'When information arrives from too many places at once — this group chat, that email, a private message still unanswered — holding focus on one piece of work becomes a real challenge. Not for lack of discipline, but because attention is being pulled in too many directions at the same time.\n\nOne way to get focus back is to stop trying to handle it all at once, and instead pick one channel, one piece of work, and let the rest wait until a specific later stretch. That takes trusting that nothing is so urgent it cannot wait another half hour, which is not always easy to believe.\n\nThe scatter does not disappear on its own, but how you meet it can change. Focus is not about shutting everything out; it is about choosing the order in which things get your attention.\n\nOf everything waiting for you right now, what genuinely needs attention immediately, and what can wait a little longer?'
where id = '5c584564-d316-4064-bdd7-017ba5c42338';

update public.wr_mood_content set
  title_en = 'One confirming message can save a lot of misunderstanding',
  body_en = E'After a meeting or an important conversation, one small step usually gets skipped: confirming what was just agreed. Everyone leaves with their own version of what happened, and those versions are not always the same.\n\nA short message summarising what you understood was settled, sent right after the conversation ends, can head off a great deal of misunderstanding later. It does not need to be long or formal, only clear enough that the other person can confirm it or correct anything that does not match.\n\nThis small step gets skipped because it feels unnecessary — it has all been said already. But the space between what was said and what was remembered is exactly where most misunderstandings live.\n\nAfter the most recent conversation where you were not entirely sure everyone understood it the same way, what might a short confirming message have looked like?'
where id = '245e3a57-e611-4be3-aa99-c026119a8dd5';

-- ---------------------------------------------------------------------------
-- ok — Khá ổn
-- ---------------------------------------------------------------------------

update public.wr_mood_content set
  title_en = 'What is working well in you?',
  body_en = E'When things are going fine, attention rarely stays there long. The mind tends to move quickly on to the next thing, the next problem, the next piece that is missing. What is running well becomes almost invisible, a quiet backdrop behind everything else.\n\nThat is a reasonable way for a mind to work. It is built to find and solve problems, to keep you safe by spotting early whatever might turn risky. But it also means that most of the time attention gathers around what is not yet right, while what is running well goes largely unrecorded — even though it quietly keeps everything pointed in the right direction.\n\nThis is not ingratitude or shallowness. It is a natural tilt, the way eyes catch movement more easily than stillness, or ears catch an odd sound more easily than familiar quiet. Problems stand out because they ask for a response; steadiness is usually silent and asks for nothing.\n\nA familiar situation: a process that has run smoothly for months, never mentioned by anyone, until the day it breaks and everyone starts talking about how important it is. Only then does it become clear how much has been quietly working all along, unnoticed and unacknowledged until it stopped working.\n\nOne way to rebalance attention is to ask now and then what is running well that you barely have to think about. It might be an easy working relationship where you do not have to weigh every word. It might be a habit that has settled in and saves time without needing to be reconsidered each day. It might be a skill that has become natural enough to stop feeling hard, though it was once a real challenge. These usually go unnamed, even while they quietly hold the days together.\n\nNo long list is needed. Sometimes noticing one thing that is working well is enough to shift how today looks, and a gentle reminder that not everything needs fixing.'
where id = '902f1d1d-b550-4658-8096-9b38f1eb152b';

update public.wr_mood_content set
  title_en = 'Steadiness is an achievement too',
  body_en = E'There is a slightly odd feeling in things going fine while having nothing in particular to report. No big milestone, no story worth sharing at the end-of-week meeting, just everything running as usual, day after day.\n\nIn a world that mostly celebrates turning points and success stories with a clear beginning and end, steadiness is easy to read as neutral — not bad, but not worth mentioning either, almost a pause between more important events. But steadiness, especially steadiness held onto after a hard stretch, is considerable in itself, even without a shape that makes a good story.\n\nHolding a steady state takes more effort than it looks. It needs consistency repeated daily, habits kept up with nobody watching, boundaries respected even when it means turning down something appealing right in front of you — all of it happening where nobody sees.\n\nA concrete example: after a spell of constant job changes, jumping from project to project, there comes a stretch where everything settles into an even rhythm, no drama, no crisis to put out. The feeling then is sometimes restlessness, as if something is missing, as if a familiar sensation has gone — when in fact this is exactly what was wanted during all those chaotic stretches.\n\nOne way to look at it again is to separate boredom from steadiness. Boredom usually comes with a sense of being stuck, of no way out, an unwanted stagnation. Steadiness usually comes with a sense of safety, undramatic but solid, a base from which you can plan further ahead. If what you are feeling is closer to the second, that may be a good sign rather than something to worry about or rush to change.\n\nSteadiness is not where growth stops. It can be the ground that lets the next steps, when they come, have somewhere solid to stand — instead of having to be built from scratch each time.'
where id = 'c9420aa1-4cd8-4eb3-aa74-9a91742e2fb2';

update public.wr_mood_content set
  title_en = 'Ordinary days are worth remembering',
  body_en = E'Looking back over a stretch of time, what usually comes to mind first are the big events: a difficult project, a crisis got through, a success recognised in front of the whole team. The ordinary days in between tend to pass without leaving any clear mark, even though they made up most of that time.\n\nBut most of working life is not big events. It is a run of ordinary days one after another, where most of the work actually gets done, most relationships are built through small conversations, and most skills are shaped by steady repetition rather than by rare breakthroughs.\n\nMemory tends to favour whatever stands out, as a way of saving space and staying focused on what might matter later. But that also means most of everyday experience — the small moments that make up how work actually feels — gets dropped without anyone deciding to drop it, as though it were not important enough to keep.\n\nA familiar situation: asked how last week went, the answer is usually fine, nothing special — when in fact that week held a good conversation with a colleague about a hard problem, a small issue resolved cleanly before it grew, a rare afternoon of focus where everything seemed to move.\n\nOne way to keep these ordinary days is to note down one small thing each day. It does not need to be large, only specific enough that reading it back later still brings the day into view. Not to make a good story, but so the largest part of the experience is not lost — the part quietly shaping how the work feels day to day.\n\nOrdinary days, looked back on from far enough away, usually turn out to be what made the person you are now, more than any of the big events did.'
where id = '1130fee9-d0f2-4b94-8120-3704c8e44059';

update public.wr_mood_content set
  title_en = 'You do not need a reason to feel fine',
  body_en = E'There is a common habit of only letting yourself feel fine when there is a clear reason to explain it — a project just finished well, a compliment just received, a milestone just reached.\n\nWhen there is no such reason but the feeling is there anyway, it can create a little confusion, almost a need to find a cause. And if none can be found, the good feeling gets doubted, as if it were not legitimate enough to be acknowledged.\n\nBut feeling fine does not always need a direct cause to exist. Sometimes it is simply the result of nothing weighing on you right now, a pleasant neutral state, not necessarily set off by any particular good event — the way the sky needs no special reason to be clear on a given day.\n\nA familiar situation: an ordinary morning, nothing in particular happening, but an unexplainable lightness. The first reflex is sometimes to wonder whether something has been overlooked, rather than simply taking the good feeling as it comes.\n\nOne way to depend less on finding a reason is to let the feeling exist without an explanation, and without hunting for evidence that it is justified. It can just be what it is, needing nothing more.\n\nNot every good feeling needs a story attached to count as valid or deserved. Sometimes letting yourself feel fine without a reason is its own kind of rest — rarely talked about, and no less necessary for it.'
where id = 'abbfc3a4-4268-419e-8c96-e4fd12f12a6d';

update public.wr_mood_content set
  title_en = 'When the pace slows, and nothing is wrong',
  body_en = E'There are stretches where the pace of work naturally slows: fewer meetings, fewer urgent things, more room between tasks than usual. For many people, instead of enjoying the quiet, the first response is worry — wondering whether something has been missed, or whether their work is becoming less important.\n\nMost of that worry comes from having been used to a high pace for a long time, to the point where a slower one starts to register as abnormal, when really it is a natural part of the cycle of any kind of work.\n\nNot every lull is a sign of a problem. Much work is naturally cyclical, with peak stretches and quiet ones, and the quiet stretch is not a fault to be fixed but a necessary part of getting ready for the next cycle.\n\nA familiar situation: after a busy quarter with overlapping projects, one week suddenly turns much lighter. Rather than treating it as a chance to recover, the natural reflex is sometimes to find more work to fill the gap, because idleness brings more unease than ease.\n\nOne way to see it differently is to ask whether this slower pace comes with any real sign worth worrying about, or whether it is simply a natural stretch running its course. With no specific sign, the quiet can be taken as an ordinary part of the work, not something to be filled at any cost.\n\nThe pace does not have to stay high to prove the work has value. Sometimes a slower stretch is exactly what makes the next one go better.'
where id = 'f6ddade9-8e43-4412-b72c-039b0cc169f0';

-- ---------------------------------------------------------------------------
-- happy — Đang vui
-- ---------------------------------------------------------------------------

update public.wr_mood_content set
  title_en = 'Catch this moment before it passes',
  body_en = E'Some good moments arrive fast and pass just as fast: an unexpected message of praise, an idea taken up better than expected, a working stretch where everything seems to move without much effort. While it is happening the feeling is clear, almost touchable. A few hours later it usually fades, giving way to the next thing on the list.\n\nGood feelings at work, unlike the big milestones marked on a calendar, are rarely kept on purpose. They appear, they are felt in the moment, then they go without leaving any clear trace to return to — like a passing breeze.\n\nThis is not because they do not matter. It is because the mind tends to prioritise whatever needs a next action over whatever only needs to be felt and left alone. A message of praise does not ask for an immediate response, so it is easily set aside to make room for something else waiting.\n\nA familiar situation: getting good feedback on an important presentation, feeling glad in that moment, then immediately turning to worry about the next thing on the calendar — another meeting, another deadline. By the end of the week, asked what was good about it, that feedback is no longer anywhere near the front of your memory, even though it made a whole afternoon lighter.\n\nA simple way to keep these moments is to take a little time, right as it is happening, to name specifically what is making you glad, instead of skimming past the feeling and rejoining the run of work. No large gesture or elaborate ritual is needed, only enough for the moment to be registered before it gives way to the next thing.\n\nA good feeling does not have to be large to be worth keeping. Sometimes it only needs to be noticed while it is happening, and that is already enough for it not to pass entirely unseen.'
where id = '3f8a871c-91d3-471a-b5d8-c36023fa91a7';

update public.wr_mood_content set
  title_en = 'Today''s good feeling, tomorrow''s reminder',
  body_en = E'There is a difference between having a good day and actually understanding why it was good. Most of the time, when things go smoothly, the question of why rarely comes up — nothing is pushing you to find an answer, unlike a problem that needs solving now.\n\nBut it is the good days, looked at a little more closely, that usually hold the clues about what genuinely fits you — more so than the hard ones. Difficulty tells you what is off, what to avoid or repair. Good feeling tells you what is pointing the right way, what is worth repeating more often in the days ahead.\n\nThis usually gets skipped because a good feeling creates no pressure to analyse it, unlike a problem demanding immediate attention. When things are fine, the natural reflex is to enjoy it and move on, without stopping to ask anything further, because there seems to be no reason to.\n\nA concrete example: a team meeting that goes especially well, everyone contributing ideas naturally, the mood easy enough that nobody notices how fast the time goes. Without stopping to ask what made that meeting work, it is easy to miss the very thing that made the difference next time, and slip back into the older, less effective way.\n\nOne way to keep the lesson from a good day is to ask one simple question while the feeling is still fresh: what in today helped create this. It might be preparing differently from usual. It might be someone being there who brought good energy. It might be a small decision made earlier than normal that let everything run more smoothly.\n\nA good day today is not just a good day passing through. It can be worth remembering, for when tomorrow needs a hint about how to start off in the right direction rather than feeling around from scratch.'
where id = 'ad17697d-a15f-44b0-994f-7ff58878f52c';

update public.wr_mood_content set
  title_en = 'Who deserves to know about this?',
  body_en = E'When good news comes at work, many people''s first reflex is to keep it to themselves for a while — not sharing yet, perhaps from shyness, perhaps from not being sure it is worth mentioning, or simply from being used to handling every feeling alone.\n\nBut a good feeling kept only in your head tends to fade faster than one shared with someone. Not because it needs anyone else''s recognition to be real, but because telling it to someone usually reinforces the experience once more, lets it be lived once more in the telling.\n\nThere is a natural hesitation about sharing good news, especially at work, out of worry that it will sound like boasting or like seeking attention that was not needed. That hesitation is not wrong, but it can also leave many worthwhile moments passing in silence, only because no sufficiently good reason to mention them could be found.\n\nA familiar situation: finishing a hard piece of work well, feeling satisfied for a few minutes, then telling yourself there is probably no need to mention it — even though this was the goal set at the start of the week and took no small effort to reach. That satisfaction, unshared, usually fades faster than it would have if it had been said out loud to someone listening.\n\nA question that can help here is who deserves to know about this. Not to fish for praise or recognition, but to pick the right person: a colleague who was alongside you through it, someone who asked after this earlier, or simply someone you want to share the good feeling with, for no reason beyond wanting them to know.\n\nSharing a small piece of good news does not need a large reason or a special occasion. Sometimes it is enough that it made you glad and that there is someone who wants to hear it.'
where id = '88ae4790-dd81-45a6-b613-245405b76296';

update public.wr_mood_content set
  title_en = 'When the work suddenly feels weightless',
  body_en = E'Some working days pass unusually lightly: tasks get finished without much strain, conversations go smoothly, time moves faster than usual without leaving any tiredness at the end.\n\nDays like that often leave a little doubt behind, as though the lightness could not be real, or a worry that tomorrow will be harder to make up for it. The good feeling from an easy working day is sometimes dimmed by that very watchfulness.\n\nBut an easy working day is not a random piece of luck to be suspicious of, and it does not have to be paid for with a hard day afterwards. Sometimes it is simply the result of several small things happening to line up at once: preparation done earlier, the right frame of mind, or just a day when everything fits together.\n\nA familiar situation: finishing a long list of work without the usual exhaustion, then wondering whether you have got something wrong, because the ease feels so different from what you are used to. That thought quietly takes away from a good feeling that could have been enjoyed whole.\n\nOne way to take days like this in fully is to let yourself feel light without looking for a reason to doubt it, and without bracing for some imagined bill to come. Today was easy; that can simply be all it is.\n\nWorking days that pass easily deserve to be enjoyed exactly as they are, without caution attached. They are as real a part of the work as the hard ones.'
where id = 'ee4bd3f3-c1c6-4e81-9278-7ba9e9e09458';

update public.wr_mood_content set
  title_en = 'A good day does not have to prove anything',
  body_en = E'After a good working day, there is sometimes an urge to tell it — to show someone how well today went, through a post, a light bit of news, or at least a story told in detail in the evening.\n\nThere is nothing wrong with the urge; sharing good things is natural. But it sometimes carries an unspoken sense that if nobody knows about it, the good feeling is somehow incomplete — as if a good day needed a witness to properly count as good.\n\nBut the value of a good working day does not depend on how many people hear about it. The satisfaction, the ease after finishing something well, the gladness when an idea lands — all of it was already complete at the moment it happened, needing no further confirmation from outside.\n\nA familiar situation: having a genuinely good working day with no occasion to tell anyone, nobody asking, no meeting where it comes up. By evening there is a vague trace of regret, as though the day had not been properly acknowledged, even though you knew perfectly well how it went.\n\nOne way to keep that good feeling whole is to let it exist just for you, needing no evidence beyond what you are feeling right now. You might write yourself a short line, not to share with anyone, only to mark that this really happened and that you noticed it fully.\n\nA good day does not have to prove anything to anyone. It only needs to be recognised by the person who lived it, and that is already enough.'
where id = '5d05e332-06cf-4a35-b8fa-c87e1a04862b';

-- ---------------------------------------------------------------------------
-- Rào chắn
--
-- `update ... where id = '…'` khớp 0 dòng thì Postgres KHÔNG báo lỗi. Gõ sai
-- một uuid ở trên là để lại đúng một bài đọc tiếng Việt giữa một màn tiếng Anh,
-- và không có gì trong quy trình bắt được nó.
-- ---------------------------------------------------------------------------
do $$
declare
  missing int;
begin
  select count(*) into missing
  from public.wr_mood_content
  where title_en is null or btrim(title_en) = ''
     or body_en is null or btrim(body_en) = '';

  if missing > 0 then
    raise exception 'wr_mood_content còn % dòng chưa có bản tiếng Anh', missing;
  end if;

  -- Số đoạn phải khớp: `MoodContent.paragraphs` tách theo dòng trống để dựng
  -- khối văn bản, nên lệch số đoạn là lệch bố cục màn đọc giữa hai ngôn ngữ.
  select count(*) into missing
  from public.wr_mood_content
  where array_length(string_to_array(body, E'\n\n'), 1)
     <> array_length(string_to_array(body_en, E'\n\n'), 1);

  if missing > 0 then
    raise exception '% dòng có số đoạn tiếng Anh khác tiếng Việt', missing;
  end if;
end $$;
