-- WorkReflection: bổ sung 11 tình huống còn thiếu để đủ 60 (10 chiều × 6).
-- Nguồn: Career Situation Library (Tầng 1) + DataSpec v3 (Tầng 3).
-- Additive & idempotent — an toàn khi chạy lại trên DB đã seed 49 dòng.

insert into public.wr_situations
  (code, text, sca_dimension, human_need, expected_outcome, sca_perspective, wave)
values
  ('S2-sit-06', 'Công việc phụ thuộc quá nhiều người', 'S2', 'ro_rang', 'Tôi muốn giảm bớt số mắt xích phải chờ để công việc của mình đi được tiếp', 'Khi một việc phải đi qua quá nhiều người mới xong, chỉ cần một mắt xích chậm là cả chuỗi dừng lại. Bạn không chậm, chỉ là bạn đang gánh rủi ro của cả một chuỗi phối hợp chưa được thiết kế gọn.', 3),
  ('S3-sit-06', 'Thiếu dữ liệu để ra quyết định', 'S3', 'ro_rang', 'Tôi muốn có đủ dữ liệu cần thiết để quyết định mà không phải phỏng đoán', 'Quyết định trong thiếu thốn dữ liệu luôn để lại cảm giác bất an, dù kết quả có tốt đi nữa. Đó không phải bạn thiếu quyết đoán mà là chưa có ai chịu trách nhiệm đưa dữ liệu đến tay người cần quyết định.', 3),
  ('C1-sit-05', 'Khó giao việc cho người khác', 'C1', 'ket_noi', 'Tôi muốn giao được việc và yên tâm rằng nó sẽ được làm đúng', 'Không giao được việc thường bị hiểu là ôm đồm. Thực ra nó là dấu hiệu bạn chưa có đủ căn cứ để tin, và xây niềm tin đó là việc của cả nhóm chứ không riêng bạn.', 1),
  ('C1-sit-06', 'Thiếu sự hỗ trợ từ đội nhóm', 'C1', 'ket_noi', 'Tôi muốn biết mình có thể dựa vào ai khi công việc vượt quá sức một người', 'Cảm giác đơn độc giữa một tập thể là điều nặng nề, vì nó khiến bạn nghi ngờ chỗ đứng của mình. Thường thì không ai cố tình bỏ rơi bạn, mà là nhóm chưa có thói quen nhìn thấy nhau khi ai đó đang quá tải.', 1),
  ('C2-sit-06', 'Sợ mắc lỗi trước tập thể', 'C2', 'ket_noi', 'Tôi muốn có thể thử và sai mà không phải trả giá bằng hình ảnh của mình', 'Sợ sai trước đám đông không phải yếu đuối. Đó là phản ứng tự nhiên khi bạn từng thấy lỗi bị đem ra mổ xẻ thay vì được xem là một phần của việc học. Nơi nào phạt lỗi công khai, nơi đó người ta ngừng thử.', 1),
  ('C3-sit-06', 'Không biết cách góp ý', 'C3', 'ket_noi', 'Tôi muốn nói được điều cần nói theo cách người kia đón nhận được', 'Không biết mở lời không phải vì bạn vụng. Góp ý là một kỹ năng cần chuẩn mực chung để dựa vào, và khi nhóm chưa có chuẩn mực đó thì ai nói trước cũng thành người gây chuyện.', 3),
  ('A1-sit-06', 'Không chắc mình đang đi đúng hướng', 'A1', 'phat_trien', 'Tôi muốn có cách kiểm chứng xem hướng đi hiện tại có thực sự đưa mình tới nơi mình muốn', 'Cảm giác không chắc chắn về hướng đi thường xuất hiện khi bạn vẫn bận rộn nhưng đã lâu không có dịp đối chiếu việc mình làm với điều mình muốn. Nghi ngờ ở đây là một tín hiệu lành mạnh, không phải dấu hiệu bạn đang sai.', 1),
  ('A2-sit-05', 'Không hoàn thành được việc quan trọng', 'A2', 'thich_nghi', 'Tôi muốn bảo vệ được thời gian cho những việc thực sự tạo ra khác biệt', 'Việc quan trọng thường không có deadline gấp, nên nó luôn thua những việc kêu to hơn. Bạn không thiếu ý chí mà đang ở trong một nhịp làm việc mà cái khẩn cấp luôn thắng cái quan trọng.', 2),
  ('A2-sit-06', 'Cảm thấy mất kiểm soát với công việc', 'A2', 'thich_nghi', 'Tôi muốn giành lại quyền chủ động với khối lượng và nhịp công việc của mình', 'Mất kiểm soát thường không đến từ một biến cố lớn mà tích lại từ nhiều việc nhỏ chen ngang. Khi mọi thứ đều do bên ngoài quyết định thời điểm, cảm giác cầm lái sẽ mất dần dù bạn vẫn đang làm rất nhiều.', 2),
  ('A3-sit-06', 'Không có thời gian nhìn lại', 'A3', 'thich_nghi', 'Tôi muốn có một khoảng dừng đều đặn để hiểu những gì mình vừa trải qua', 'Không có thời gian nhìn lại là lý do nhiều người đi rất nhanh mà không tiến xa. Trải nghiệm chỉ thành bài học khi được dừng lại xem xét, và khoảng dừng đó cần được xếp lịch chứ hiếm khi tự xuất hiện.', 1),
  ('A4-sit-06', 'Không biết bước tiếp theo để phát triển', 'A4', 'phat_trien', 'Tôi muốn biết cụ thể điều gì nên làm tiếp để tiến thêm một bậc', 'Đứng trước ngã ba mà không thấy đường nào rõ hơn đường nào là cảm giác dễ khiến người ta dậm chân. Không phải bạn thiếu năng lực mà là chưa có ai giúp bạn nhìn thấy khoảng cách giữa nơi mình đang đứng và bậc kế tiếp.', 2)
on conflict (code) do nothing;
